### ISSUE TITLE
Participate View: strict validation UI changes

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#102]
1. Title of Constraint/Required modal: "Invalid Value"
2. Add sentence below form-defined constraint message.

**Comment by pbowen-oc** [comment]
Sample:
![patient_facing_error_field_level_-_generic](https://user-images.githubusercontent.com/25179620/45570308-3449e880-b830-11e8-95f0-44054e6b60c0.png)
