### ISSUE TITLE
Add preview view for participant

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#111]
> We will need a way to preview a form as a Participant form in the same way that we can currently preview forms in general with our existing view.

The way this differs from regular previews:

* applies strict logic (so can be used to test logic?)

**Comment by MartijnR** [comment]
@pbowen-oc, do you need one that loads an existing record as well or just to view an empty form?

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, this will be used to test the form logic and behavior before it is published.

We currently only support Preview mode for an empty form and that would reminan the same for Preview as Participant mode.

**Comment by MartijnR** [comment]
Yes, makes total sense! I confused myself with view vs preview.

**Comment by MartijnR** [comment]
Has been added in `master` as  **POST /oc/api/v1/survey/preview/participant**

Documentation: https://github.com/OpenClinica/enketo-express-oc/blob/master/doc/oc-api.md#post-surveypreviewparticipant
