### ISSUE TITLE
POST /instance/edit/participant returning 400

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#112]
> Getting 400 Bad Request. Is there any required parameters other than ‘ecid' is needed for instance url to make it work or am I missing something?

**Comment by MartijnR** [comment]
Looks like API endpoint works but the view cannot obtain the instance.

**Comment by jkeremian** [comment]
Hi Marijn, all good,
I was passing in empty instance, for that was getting 400 error.

I’m good now, field submission works too.
I let you know if anything else comes up
Thanks a lot

Joe

**Comment by MartijnR** [comment]
Great! thx
