### ISSUE TITLE
RFC View: Close with empty RFC field should show error

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#119]
>Steps:
1. Open a completed form
2. Change a value
3. Without entering an RFC in the RFC box that opens at the bottom of the page, click Close

Expected:
User receives an error message and does not leave the form.

Actual:
User leaves the form without any error messages for missing RFC.

**Comment by MartijnR** [comment]
Looks like this is also reproducible for incomplete records

**Comment by pbowen-oc** [comment]
We only call the RFC URL with completed records.

**Comment by MartijnR** [comment]
Ah thanks. Are we meeting?

**Comment by MartijnR** [comment]
* [ ] figure out why incorrect id is applied to button. should be `#close-form-complete`.
