### ISSUE TITLE
View Query Only should not have Complete button

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#122]
We noticed that our view for seeing only a single item with query now has a Complete button. This should be removed. 

I think we're just passing a mini-XForm in for a review-only or read-only view. Those views should never have complete buttons (only edit mode should be able to have a complete button).

**Comment by MartijnR** [comment]
Sure. I'm just not sure which view you are using for that. Easiest is probably to let me know the webform URL (`src` attribute of the iframe). I can figure it out from that.

**Comment by pbowen-oc** [comment]
https://form.dev.openclinica.io/edit/fs/dn/c/i/::548f1111d572c70159360457f968ac39?ecid=882d53b93bfee85ff4b35ecec5baaf487d8cada11d7825ade9ad3bfa3b6631d8
