### ISSUE TITLE
Form loads showing irrelevant note in grayed out text and next button even though there is only one page

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#126]
![2018-10-17 20_57_44-openclinica](https://user-images.githubusercontent.com/25179620/47125083-68f5f900-d24f-11e8-9414-58bb1c6aed4f.png)

![2018-10-17 20_58_02-openclinica](https://user-images.githubusercontent.com/25179620/47125090-6d221680-d24f-11e8-9f09-2285fd35ee02.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=126.xml

**Comment by MartijnR** [comment]
Pages are initialized before relevancy is determined. If the first page become irrelevant during load, this is not triggering a page update.

* [ ] create pages.update function
* [ ] call this function after relevant.update during form initialization
