### ISSUE TITLE
Grid form loads without top horizontal line

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#127]
![2018-10-17 21_07_54-openclinica](https://user-images.githubusercontent.com/25179620/47125339-de15fe00-d250-11e8-848f-d2c78f40c126.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=127.xml in enketo-core

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=https://gist.githubusercontent.com/MartijnR/b3b39213c5c1cf5dcc875c831791c758/raw/a497efae1b96ba9a5bbf4f34e698657dd6c239c0/127.xml
