### ISSUE TITLE
Required select_multiple items do not show asterisk

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#134]
A select_multiple item that is required is never showing an asterisk. It is being treated as a required field apart from that (the required error message appears if I select a value and then remove it).

![2018-10-25 13_26_10-openclinica](https://user-images.githubusercontent.com/25179620/47518676-a236f600-d859-11e8-979c-7fe1f6f2fb6e.png)

**Comment by MartijnR** [comment]
* [ ] check enketo-core
* [ ] check enketo-express if not in enketo-core
* [ ] check enketo-express-oc if not in enketo-express

**Comment by MartijnR** [comment]
@pbowen-oc, please provide a 1-2 question form that reproduces the issue.

**Comment by pbowen-oc** [comment]
@MartijnR - I just sent it via email.

**Comment by pbowen-oc** [comment]
[XForm for required multi-select.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/2531307/XForm.for.required.multi-select.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::EU7dejHr?ecid=a
