### ISSUE TITLE
Pages Theme with Relevant groups not allowing user to get to second page

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#137]
Steps:
1. Open the form
2. Select the Yes radio button

Expected:
A nested group becomes relevant on the first page. A separate top-level group becomes relevant on the second page.

Actual:
The nested group becomes relevant on the first page. However, the Next button does not appear so the user is unable to get to the second page.

Note:
If you open this form as an existing record where the radio button is already set to Yes, the second page is accessible as expected. But anytime you toggle from No or null to Yes within the session, the second page does not appear.

**Comment by pbowen-oc** [comment]
[nested group relevant pages.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/2566785/nested.group.relevant.pages.xml.txt)

**Comment by MartijnR** [comment]
not in enketo-core (yay!)

in ee-oc: http://localhost:8005/preview/?form=http://localhost:3000/form/nested.group.relevant.pages/form.xml

**Comment by MartijnR** [comment]
Seems that `changebranch` event is not fired.

**Comment by MartijnR** [comment]
I am loosing my programming skills. This should have taken 10 minutes...
