### ISSUE TITLE
Show print button on smaller screens

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#140]
> We've had some requests to make the print function accessible to users on phones or tablets. We also had a user who does not see the Print icon on her smaller screen laptop. In trying to replicate this in Chrome, I found that the Print icon disappears as the screen size gets smaller. However, if I zoom out in Chrome right after the icon has disappeared, it becomes visible again. So, we have the workaround that will help with some users, but it won't be effective for our broad population of Participant users.

> So, instead of making the icon disappear on small screens, can we just make the icon get smaller?

**Comment by MartijnR** [comment]
For general Enketo Express:
* [ ] test with language selector
* [ ] test with mobile bookmark icon
* [ ] test with form logo

For OC fork:
* [ ] test with fieldsubmission feedback, in addition to above

**Comment by MartijnR** [comment]
<img width="441" alt="screen shot 2018-12-10 at 11 29 31 am" src="https://user-images.githubusercontent.com/627350/49753026-5c01ee80-fc6f-11e8-85c4-2b2f2d5c5268.png">

<img width="393" alt="screen shot 2018-12-10 at 11 32 32 am" src="https://user-images.githubusercontent.com/627350/49753032-61f7cf80-fc6f-11e8-963f-032ec98918be.png">

**Comment by MartijnR** [comment]
* [ ] move bookmark icon to right
* [ ] make print icon smaller

**Comment by MartijnR** [comment]
<img width="428" alt="screen shot 2018-12-10 at 11 44 55 am" src="https://user-images.githubusercontent.com/627350/49753558-0c242700-fc71-11e8-89cd-ce3c2ccadf48.png">

**Comment by MartijnR** [comment]
<img width="464" alt="screen shot 2018-12-10 at 1 05 04 pm" src="https://user-images.githubusercontent.com/627350/49758490-4fd05e00-fc7c-11e8-80ab-5a6e5a15a8e5.png">

**Comment by MartijnR** [comment]
The form header is very full. Not showing the brand and the offline icon + records in queue, makes a huge difference. Since OC doesn't use those, it makes sense to do something custom. Unfortunately, it is going to break (visually) whenever the Master repo changes the style.

**Comment by MartijnR** [comment]
@pbowen-oc, none of your products use the OC logo at the top, right?

**Comment by pbowen-oc** [comment]
@MartijnR - The Print button is now visible for me on iPhone, but the print feature doesn't work. After clicking the Print button and then Prepare on the settings window, the print view flashes for maybe 1 second and then disappears, so the user is unable to attempt to print that view.

**Comment by pbowen-oc** [comment]
@MartijnR - This doesn't seem to work for us on Android either. If there is no way to get Print to either trigger the mobile browser print or remain available for the user to send to the printer, can you remove the button from small devices again?
