### ISSUE TITLE
Item with relevant and constraint doesn't fire constraint as expected

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#142]
[relevant and constraint test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/2590855/relevant.and.constraint.test.xml.txt)

Steps:
1. In the attached form, select the checkbox to make the height and weight items become relevant
2. Enter 1 for each item to trigger the constraints on these items
3. Deselect the checkbox. As expected, the Height and weight items show relevant errors.
4. Select the checkbox again.

Expected:
The height and weight items should show constraint errors again since the constraint logic is still triggered.

Actual:
There are no constrain error messages displayed. The user is also able to close the form without being prompted to added autoqueries to the items with constraints firing.

**Comment by MartijnR** [comment]
* [ ] try reproducing with preview

**Comment by MartijnR** [comment]
_closeSimple and _closeRegular do not call the validation function

**Comment by MartijnR** [comment]
* [ ] simplify constraint for easier testing

**Comment by MartijnR** [comment]
Sorry, this is not done. Some tests are failing.
