### ISSUE TITLE
404 error opening form as Participant Preview

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#143]
> We're getting a 404 error when we try to preview a form as a participant using the new view you added:

> The error we are seeing in the console is:

12:03:27.689 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59 GET https://formpreview.dev.openclinica.io/preview/participant?form=https%3A//build.dev.openclinica.io/form-service/api/versions/7690643/artifacts/build.dev.openclinica.io%3Aform-participate-preview.xml&jini=true 404
t._insertNodeWithHooks @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
t._insert @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
t.attach @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
r._DOMRange.attach @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:217
t.setMembers @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
t @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
e.nonreactive @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
t @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
(anonymous) @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
e._withTemplateInstanceFunc @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
(anonymous) @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
f._withCurrentView @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
if:updater @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:59
e.Computation._compute @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
e.Computation._recompute @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
e._runFlush @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
e @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:1
postMessage (async)
u @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:1
h @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
e.Computation.invalidate @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
e.Dependency.changed @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:21
i.set @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:51
e @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:301
(anonymous) @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:301
(anonymous) @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:301
(anonymous) @ 9dae76093f2237a822093382fbd3fc881aea9bc5.js?meteor_js_resource=true:1

Can you tell if we are doing something wrong with this call or if there is an error in the endpoint?

**Comment by MartijnR** [comment]
I believe this URL (with the `form=...` query parameter) is manually crafted by OC. The issue is a missing `/i` at the end of the path.

So should be `../preview/participant/i/?form=...` instead of `../preview/?form=..`.

This may seem inconsistent, because I suspect you are not using the /i (=iframe-friendly) path for the non-Participant previews, but it's by design. The regular previews (from the master Enketo) support both regular and iframe-friendly. This custom Participant preview only supports what (I thought) is required for OC. 

So if OC is showing this preview in an iframe, just change according to the above. You may want to add the `/i` part to the non-Participant previews as well.

Otherwise, let me know and I'll just add a non-iframe-friendly Participant preview.

**Comment by pbowen-oc** [comment]
Thanks. I'll let you know if we need a change after we look into it further.

**Comment by pbowen-oc** [comment]
We are all set here. Thanks.
