### ISSUE TITLE
support annotation + multiple queries in DN widget

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#145]
Update the Query Widget to allow the user to enter an Annotation instead of a Query (probably by choosing in a dropdown). Annotations do not change the query status of the item. When the user has selected to enter an Annotation instead of a Query, there should only be a Submit button beneath the text box. They are submitted to OC as a different note type than Queries.

When a record is loaded, existing Annotations may be loaded for a Query item along with Queries, RFC entries, and value changes. Annotations should be listed in the History section with a unique icon to distinguish this item type.

**Comment by MartijnR** [comment]
* [ ] add annotation type in model
* [ ] add selector annotation + query 
* [ ] prevent status change

**Comment by MartijnR** [comment]
Should the JSON model (as described here: https://github.com/OpenClinica/enketo-express-oc/blob/master/doc/advanced-comment-widgets.md#data-structure) be changed to:

```json
{
    "queries": [ ],
    "logs": [ ],
    "annotations" : [ ] 
}
```

Or should annotations be added to the existing `"queries"` property, but with type "annotation"? I'm guessing the latter is preferable. It's totally up to what is easiest to process on the OC side though.

@pbowen-oc

**Comment by MartijnR** [comment]
Styling to figure out:

* [ ] icon in history
* [ ] display of pulldown field on large and small screens, grid and oc themes
* [ ] text to display in new pulldown

**Comment by MartijnR** [comment]
current thinking is to have different tabs for queries and annotations

related to multiple constraint isssue

**Comment by MartijnR** [comment]
* [ ] implement as tabs showing combined history on both tabs

**Comment by MartijnR** [comment]
revert for now

**Comment by MartijnR** [comment]
probably need to add new field to query, e.g. `thread_id`

**Comment by pbowen-oc** [comment]
Here is our current (not final) mockup:
<img width="801" alt="Screen Shot 2019-04-09 at 5 14 09 PM" src="https://user-images.githubusercontent.com/25179620/55837832-78fce000-5af0-11e9-888e-94b9a5201263.png">

A couple things to note:
The ID under the threads on the left would be a unique ID passed in with the query. This does not necessarily need to be in V1 of this feature.

We didn't discuss it earlier, but we'll need the ability to to open the Query Widget to All History or to a specific thread in different circumstances. For example, clicking the empty query icon form the form should open to All History. The endpoint to open the form right to a specific query should be expanded to allow us to target not just the query item but also a specific thread within it. The behavior when clicking the icon on the form for an open query is TBD (undecided whether it should open to the All History or the first New/Updated status thread.

**Comment by MartijnR** [comment]
* [ ] pass annotation/query type
* [ ] set current thread id
* [ ] create filter functions

**Comment by MartijnR** [comment]
Enketo generates guid `thread_id`. OC something like `visible_thread_id`.

**Comment by MartijnR** [comment]
design questions (gathering here, but not urgent)
* What should the 'initials' of the current user be in the history's 'initial bubbles'

**Comment by MartijnR** [comment]
exactly one new/updated query -> single bubble in new or updated color

**Comment by MartijnR** [comment]
status of whole dn question:

**Comment by MartijnR** [comment]
Outstanding design questions:
* design for history in printouts (now looks the same as history in widget except for datetime stamps)
* icon for button for small screens to switch between history and navigation

**Comment by MartijnR** [comment]
* [ ] icon larger
* [ ] in all history - align top of right pane with left pane
* [ ] if there is only one open query (new or updated), open directly to that thread

**Comment by MartijnR** [comment]
> from Jing:

Implementation demo internal feedback:
1. Right pane texts should top align with left pane 
2. When there's only one open query, the default query widget view should be response to this query with active cursor (ready to type); When there are multiple open queries, the default query widget view would be "all history"
3. make the left pane selection more prominent (add arrow to history, and think of colors)
4. Closed queries: hint text "Type here to reopen".  Corresponding button would be "Reopen". 
5. Button text: "Close this query" rather than "Close This Query"
6. Button placement: should be on the same line of dropdown
7. Dropdown list not showing
8. Mobile view: the keyboard comes up and covers query widget
9. Conversation threads call out should align with user icon, rather than at the center of the box. 
10. When adding new queries, only value changes show, other conversations do not show, to provide a more clear indicator this is new.

**Comment by MartijnR** [comment]
wrt scroll behavior

existing:
Scrolls to let bottom of dn widget match bottom of screen.

new: 
Scrollt to let top of dn widget match top  of screen.

This will mostly resolve the blocking of the keyboard on mobile screens (as much as possible anyway).

But it introduces a new issue where the linked question is hidden.

**Comment by MartijnR** [comment]
Should reason for change only be displayed in All History or also in all query and/or annotation threads?

**Comment by MartijnR** [comment]
* [ ] Respond to query

**Comment by MartijnR** [comment]
* [ ] fix relevant error regressions
* [ ]  Button cap every word "Close This Query"
* [ ]  Hint text update to: "Respond to query"
* [ ] Query window position currently obscuring item
* [ ] Secondary line align with main text
* [ ] Query length to extend to 4 lines (remove fade in text)
* [ ] show linked question without overlay if possible

**Comment by MartijnR** [comment]
@pbowen-oc all known issues are now resolved, so any loading issues you find will probably be unknown bugs

**Comment by MartijnR** [comment]
* [ ] too much vertical space in nav if comment is only one line

**Comment by MartijnR** [comment]
The 'fix' is to determine whether to give 2 lines or 4 line of space depending on the character size. This is not super accurate, and sometimes you may see an ellipsis at 2 lines though that should be very rare.
