### ISSUE TITLE
Participate view iframe double scrollbar

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#149]
Check if obvious diff. Iframe class?

**Comment by MartijnR** [comment]
I don't see any HTML or CSS markup differences between participate and non-participate fieldsubmission views.

It would be worth comparing both views to check that:
1. both views have a path that ends in `/i/::ID`
2. both views have or both do not have the jini stuff applied
3. any code changes between both views on the OC side in the parentWindow HTML/CSS that serves the Enketo form

**Comment by MartijnR** [comment]
Might be browser-specific...

**Comment by MartijnR** [comment]
x-overflow: hidden (can this be removed?)

**Comment by pbowen-oc** [comment]
Here is a video of the scrolling issue in Chrome on a Mac: 
[chrome.zip](https://github.com/OpenClinica/enketo-express-oc/files/2699719/chrome.zip)

**Comment by MartijnR** [comment]
Though I cannot reproduce scrolling issues, I am not noticing any obvious negative consequences of removing `x-overflow:hidden`, so I'll just proceed with that.

**Comment by MartijnR** [comment]
deployed in `master`

If this resolves the issue:

* [ ] change in enketo/express
* [ ] merge to `develop`

**Comment by pbowen-oc** [comment]
This seems to be working fine now
