### ISSUE TITLE
[REVERT] Likert Scale text in Grid Theme overlaps button if code text too long

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#150]
If Likert Scale items have text that wraps to a second line, it breaks the formatting of the widget, pulling the radio button down into the text.
![lickert_problem](https://user-images.githubusercontent.com/25179620/50175454-d8797a80-02ca-11e9-939a-a98392b520e1.png)

**Comment by MartijnR** [comment]
* [ ] check if specific to Grid Theme

**Comment by MartijnR** [comment]
Fixed in `develop`. It would be possible to create a temporary fix in `master` but it would be better to avoid that.

**Comment by pbowen-oc** [comment]
@MartijnR - How much effort would be involved in fixing this in master? I just need to pass the info along.

**Comment by MartijnR** [comment]
about 1 hour I think
