### ISSUE TITLE
Calculated item does not clear and hide when it becomes irrelevant

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#153]
It looks like their was a regression with the interaction of relevant logic and calculated items.  In the attached form, the BMI field becomes relevant and is calculated when the checkbox is checked. When the checkbox is unchecked, the value is recalculated to 0, but the item should be cleared and hidden since it is calculated.

[calculated item not cleared when it becomes irrelevant.txt](https://github.com/OpenClinica/enketo-express-oc/files/2700458/calculated.item.not.cleared.when.it.becomes.irrelevant.txt)

![2018-12-20 15_43_57-openclinica](https://user-images.githubusercontent.com/25179620/50309789-1fec3c00-046e-11e9-9956-d34adc46840d.png)

**Comment by MartijnR** [comment]
run locally (hosted on Centro): http://localhost:3000/form/calculated.item.not.cleared.when.it.becomes.irrelevant/form.xml

**Comment by MartijnR** [comment]
@pbowen-oc, are you experiencing this within the same session starting with a blank form? Or is this error only shown when you load a previous record?

I cannot reproduce it with an empty form. As soon as I empty either weight or height, the calculated BMI is hidden. 

Because of recent logic changes also verify that you are running the latest master please (1.72.3-608-g5fefce6).

**Comment by pbowen-oc** [comment]
@MartijnR - The version on our server is listed as 1.72.3-p. We did redeploy this afternoon after you made the change to improve scrolling.

I see this with both a blank form and an existing record.  Note that I see different behavior in two scenarios:

Scenario A Steps:
1. Check checkbox
2. Enter a value in weight item
3. Uncheck checkbox
4. Clear weight item
5. Observe that BMI disappears as expected

Scenario B Steps:
1. Check checkbox
2. Uncheck checkbox
3. Observe that BMI still appears with value 0 and relevant error message

With a blank form, I could "fix" Scenario B, by following the steps in Scenario A.

**Comment by MartijnR** [comment]
Thanks. That version number is puzzling as I'd expect to see `1.72.3-608-g5fefce6`.

But I can reproduce the issue with scenario B, so that's good!
