### ISSUE TITLE
Participate view not scrolling correctly on desktop browsers

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#156]
On desktop browsers, the 1st page of the form does not scroll. Please see the attached video:

[scroll.zip](https://github.com/OpenClinica/enketo-express-oc/files/2713666/scroll.zip)

Interestingly, it does scroll with mouse wheel but not with Page Down key nor pointer.

More interestingly this does not happen on the 2nd page for some reason.

Please note this is a new behavior after the recent scrolling fix which removed overflow-x: hidden CSS tag.

**Comment by MartijnR** [comment]
I think this will require troubleshooting on the OC side, or sharing a URL that I can reproduce with. It has to do with the iframe. (Note, I was never able to reproduce the other scrolling issue either).

(for self: http://localhost:8005/dev?iframe=http://localhost:8005/single/fs/participant/i/::f992be996b8eb0342fbab92d589d8b81)

**Comment by MartijnR** [comment]
OC fixed the double scrollbar issue on the iframe parentWindow side. That appeared to have been the cause.
