### ISSUE TITLE
Trigger event based on user activity

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#162]
We'd like to trigger an event on some user actions so that we can tell if the user is active and keep their session alive.

I'm thinking the following would be good actions to have trigger this event:
1. Submitting data (item value, query, RFC) will trigger the event.
2. Navigating to a different page will trigger the event.
3. Adding or removing a repeating group row will trigger the event.
4. Opening or closing the Query Widget will trigger the event.

This would be for the develop branch.

**Comment by MartijnR** [comment]
We could build upon the already existing (I think) edit message to be sent to the parentwindow with postMessage.

**Comment by MartijnR** [comment]
best to create a new 'active' message that is sent upon these existing events
* pageflip (2)

and to be added to Enketo Core:
* repeat creation (3 part of)

and the following new custom events in OC fork
* any newly created fieldsubmission (covers 1 and part of 3 - removal of repeat)
* showing query widget modal (4)
* hiding query widget modal (4)

**Comment by MartijnR** [comment]
regression: 'edited' event fires multiple times in Enketo Core

**Comment by MartijnR** [comment]
This is done. The message posted to the parentWindow is called 'heartbeat'. It can be received in a similar manner to other messages that OC is already collecting. (Also see here: https://github.com/enketo/enketo-iframe-demo/blob/gh-pages/index.html#L21)

**Comment by pbowen-oc** [comment]
Seems to be working as expected.
