### ISSUE TITLE
Data hidden and relevant error not triggered when repeat is made irrelevant and row other than first row has data	

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#165]
Steps:
1. Open Form with repeating group that can be irrelevant
2. Make repeating group relevant
3. Add second repeat row
4. Enter data into second repeat row (leaving first row blank)
5. Make repeat irrelevant

Expected:
Repeat remains visible and relevant error is shown.

Actual:
Repeat is hidden (including data in row 2) and no relevant error is displayed. Note that the data is not cleared, just hidden.

**Comment by MartijnR** [comment]
try in `master`

**Comment by MartijnR** [comment]
code is designed to only check index 0 (is first repeat).

**Comment by MartijnR** [comment]
after merge needs re-fix
