### ISSUE TITLE
Don't show Annotation/Draw/Signature images grayed out in View Mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#167]
The contents of an Annotation/Draw/Signature widget are grayed out when the form is opened in View mode (review-only or read-only). Regular image upload items show their images unchanged in this case. Can the Annotation/Draw/Signature widget be updated to show their images contents in true color?
![2019-01-19 00_07_39-openclinica](https://user-images.githubusercontent.com/25179620/51422603-5e653b80-1b7f-11e9-8ab5-f8054ac49b79.png)
![2019-01-19 00_08_10-openclinica](https://user-images.githubusercontent.com/25179620/51422605-5e653b80-1b7f-11e9-8af2-ec04f5839d9e.png)
![2019-01-19 00_08_57-openclinica](https://user-images.githubusercontent.com/25179620/51422604-5e653b80-1b7f-11e9-92ef-09d62702cb5b.png)

**Comment by MartijnR** [comment]
* [ ] figure out why whole background is grey (readonly group?)
