### ISSUE TITLE
Hard checks should not block navigation in readonly and note-only views

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#172]

**Comment by pbowen-oc** [comment]
@MartijnR - I finally got confirmation on this. In read-only and note-only views, hard constraint and required errors should not prevent the user from navigating through the form or using the Close button. 

In the edit view, hard constraint and required errors should prevent the user from navigating forward in the form as well as from using the Close or Complete buttons. This is the same as for the Participate view except it extends it to the Complete button which is not present in the Participate view.

**Comment by MartijnR** [comment]
only strict error messages to be shown to user in readonly and noteonly views.

**Comment by MartijnR** [comment]
empty collect: http://localhost:8005/single/fs/i/::WCThedu7?ecid=a
empty readonly: http://localhost:8005/view/fs/i/::68f5a4e3df6f224454f3e69bd4162a26?ecid=a 
edit, noteonly:
edit, readonly:
