### ISSUE TITLE
Closing a form is not redirecting back as expected

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#177]
When I close a form, I'm not being automatically redirected back as expected.
![2019-03-01 17_40_45-openclinica](https://user-images.githubusercontent.com/25179620/53670750-cf514600-3c49-11e9-931d-318a8084252c.png)
![2019-03-01 17_40_54-window](https://user-images.githubusercontent.com/25179620/53670752-d11b0980-3c49-11e9-81f8-e52ec21031e4.png)

This was present last week as well but was masked by the issue with the Close button treating all Required items as strict.

**Comment by MartijnR** [comment]
My suspicion is that I changed the postmessage event from 'submissionsuccess.enketo' to 'submissionsucces'. Will check.

**Comment by pbowen-oc** [comment]
If the issue is just the new event name we will make the change on our end to match your new naming scheme.

**Comment by MartijnR** [comment]
That is the issue plus another issue, that I will have fixed shortly.

**Comment by MartijnR** [comment]
http://localhost:8005/dev?iframe=http://localhost:8005/single/fs/i/::widgets&parentWindowOrigin=https://enketo.org

**Comment by MartijnR** [comment]
* [ ] test fix with OC's code that uses jquery
