### ISSUE TITLE
Participate Strict checks not preventing page navigation

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#183]
When we open a form in Preview mode as a Participate form or edit a form as a Participant, strict errors are not preventing the user from navigating to the next page. So, this form does not prevent me from going to the Next page even though it shows the strict style required and/or constraint message:

![2019-03-21 17_17_54-OpenClinica](https://user-images.githubusercontent.com/25179620/54785918-d5f62c00-4bfd-11e9-9377-50318b9c463f.png)

**Comment by MartijnR** [comment]
This was done deliberately in https://github.com/OpenClinica/enketo-express-oc/issues/172. So strict errors in Participate previews should block navigation, but in non-Participate previews, they should not. Is that correct @pbowen-oc ?

**Comment by pbowen-oc** [comment]
@MartijnR - I'll get back to you on this tomorrow.

**Comment by pbowen-oc** [comment]
@MartijnR - Sorry for the confusion. We want the Preview modes (both Participate and standard) to use the same behavior as Edit mode (so they should block page navigation due to strict errors). For the non-Preview read-only or review-only modes, we don't want to block page navigation.

So it looks like the change to make here is to update both Preview modes to block page navigation due to strict errors.

**Comment by MartijnR** [comment]
Sorry, I was totally confused. #172 did not include changes to previews. I think this is a bug.

**Comment by MartijnR** [comment]
I'm using a different version of the same form, and cannot reproduce the issue

<img width="1285" alt="Screen Shot 2019-03-22 at 10 54 23 AM" src="https://user-images.githubusercontent.com/627350/54839617-e0153a80-4c90-11e9-9c47-49b9e1c1365d.png">

@pbowen-oc, could you please confirm the `<iframe>` `src` attribute value to make sure we're looking at the same views?

**Comment by pbowen-oc** [comment]
I have the same type of URL in my view that is exhibiting this behavior:
![2019-03-22 16_01_00-Vital Signs](https://user-images.githubusercontent.com/25179620/54849870-dfde6480-4cbb-11e9-92ab-e8662a220520.png)

**Comment by MartijnR** [comment]
hmm. Thanks. That is very mysterious. Though it seems unlikely caused by the XForm, the next step would be to check that. Could you provide this please?

**Comment by pbowen-oc** [comment]
I could not get the XForm out of the Preview window element as I'd normally do, but I got the below file from the XForm network call.

[Participant Preview XForm.txt](https://github.com/OpenClinica/enketo-express-oc/files/2998783/Participant.Preview.XForm.txt)

**Comment by MartijnR** [comment]
That doesn't work unfortunately. I need the XForm. Can you get it from another view?

**Comment by pbowen-oc** [comment]
Here is the XForm from the Participate Edit view. It shows the same issue as Participate Preview.

[Participate xform - strict checks not blocking navigation.txt](https://github.com/OpenClinica/enketo-express-oc/files/3004130/Participate.xform.-.strict.checks.not.blocking.navigation.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/preview/participant/i/::de3da7d9b064af10531540dd1f28918b (Centro)

**Comment by MartijnR** [comment]
I do:

1. Open form
2. Answer yes to 'Was temperature measured'
3. Click next

I see the modal dialog and am blocked from navigation to the next page (exactly like the screenshot I posted above).

So @pbowen-oc, if these 3 steps have a different result for you with the same form, there is a setting, update or build issue probably. Do you see anything in the console?

I'm on `version: 1.76.0-670-gc7336db`

**Comment by pbowen-oc** [comment]
[form-participate-preview.txt](https://github.com/OpenClinica/enketo-express-oc/files/3005310/form-participate-preview.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/preview/participant/i/?form=http://localhost:3000/form/Strict.checks.not.blocking.navigation/form.xml

**Comment by MartijnR** [comment]
Figured out how to reproduce this. I have to explicitly set `"validate page": false` in config json. Will check if that is a bug.
