### ISSUE TITLE
Item with Strict Required and Strict Constraint shows Required error message when it should show Constraint error message

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#184]
Steps:
1. Find an empty item with a strict required and a strict constraint
2. Enter a value that violates the constraint

Expected:
The value is reverted to empty. The popup window shows the constraint error message.

Actual:
The value is reverted as expected, but the popup window shows the required error message not the constraint error message.

Starting from empty value and entering out of range value shows the required error message (incorrectly):
![2019-03-22 19_50_11-Window](https://user-images.githubusercontent.com/25179620/54858646-76bb1900-4cdc-11e9-8ca3-8e25c0270eb1.png)
![2019-03-22 19_50_29-Window](https://user-images.githubusercontent.com/25179620/54858649-791d7300-4cdc-11e9-8d7f-92d3f093c0ca.png)
![2019-03-22 19_50_59-Window](https://user-images.githubusercontent.com/25179620/54858650-7a4ea000-4cdc-11e9-8fab-d99ef04bef4a.png)

Starting from valid value (100) and entering out of range value shows the constraint error message as expected:
![2019-03-22 19_51_25-Window](https://user-images.githubusercontent.com/25179620/54858653-7c186380-4cdc-11e9-900c-d1df8158ee67.png)
![2019-03-22 19_51_37-Window](https://user-images.githubusercontent.com/25179620/54858656-7d499080-4cdc-11e9-8199-291c1fbf3b37.png)
![2019-03-22 19_51_45-Window](https://user-images.githubusercontent.com/25179620/54858658-7f135400-4cdc-11e9-9f4d-5bbc97e91d46.png)

**Comment by MartijnR** [comment]
The problem is that clearing the value triggers a second strict violation (of the required), so both modals are shown with a few milliseconds in between.

**Comment by MartijnR** [comment]
actually, it is even worse: The required modal is shown in an infinite loop that Chrome eventually terminates. Hence the flickering

**Comment by pbowen-oc** [comment]
@MartijnR - We deployed the latest today, but I'm still seeing the issue. It actually seems to be slightly slower in showing me the error message. The entire preview window is going black briefly before the required error is shown (when the constraint error is expected). Here's what I'm seeing after I try to change temperature form null to 999:
![2019-03-27 19_59_07-Window](https://user-images.githubusercontent.com/25179620/55120164-39cf9780-50cb-11e9-8ac8-537636486558.png)

The console errors in that screenshot are followed by a large number of these in the console:
![2019-03-27 20_00_39-Window](https://user-images.githubusercontent.com/25179620/55120205-5c61b080-50cb-11e9-8362-eb6d9740869c.png)

If I change to 999 from anything except null, it seems to work as expected and with no additional errors in the console.

**Comment by MartijnR** [comment]
Yes, that looks like a deployment issue. That maximum call stack message is the infinite loop.

**Comment by pbowen-oc** [comment]
I think we have fixed the deployment issue on our end and it appears to be working as expected.
