### ISSUE TITLE
Make Xform available from participate/preview (and regular participate view if not working).

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#185]
e.g. for troubleshooting #183

**Comment by MartijnR** [comment]
already working

from: 

http://localhost:8005/preview/participant/i/::bdeea51e03ed8d98a24a06de7d15544b 

to:

http://localhost:8005/xform/::bdeea51e03ed8d98a24a06de7d15544b

**Comment by pbowen-oc** [comment]
Can you show me how to do this later? Our URL looks different for previews and I'm unsure how to make this work.

**Comment by MartijnR** [comment]
yes, sure. Maybe your url has `?form=http://url.to.form` ? In that case that `http://url.to.form` is the XForm.
