### ISSUE TITLE
Image upload items have clear icon in review-only mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#188]
Image upload items currently have a "clear" icon in review-only mode. The icon doesn't do anything, but it gives the impression that the value is editable.  It should not be present in read-only or review-only modes.

![screenshot-1](https://user-images.githubusercontent.com/25179620/54961683-13c5be00-4f38-11e9-852f-b8a5d4ef64eb.png)

**Comment by MartijnR** [comment]
yes, makes sense to change that in all widgets

**Comment by MartijnR** [comment]
http://localhost:8005/view/::c89e9303f524188382c4252ff9461228

**Comment by pbowen-oc** [comment]
I'm seeing that review-only (i.e., notes-only) has no clear icon for Draw, Signature, and Annotation widgets, but I'm still seeing it for regular image, audio, video, file upload widgets.

For those items, clicking this icon is actually clearing the file.

We need to make sure there is no way to clear an uploaded/drawn file from review-only and read-only modes.

**Comment by MartijnR** [comment]
```
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9 xmlns:oc=\"http://openclinica.org/xforms\" o:complete=\"true\"><page1><wh_y>1</wh_y></page1><page2><media_yn>1</media_yn></page2></demo-vitals-grid-v9>&instance_id=b&ecid=a" http://localhost:8005/oc/api/v1/instance/view
```

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/611

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=https://gist.githubusercontent.com/MartijnR/0373972e73e569094a94ad1868c0b264/raw/8dbdc7eda94695b55105815c837904e940e03e26/upload-relevant.xml
