### ISSUE TITLE
Call to open form directly to a Query is not opening Query Widget

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#189]
When we open a form via our links to jump directly to a query, the form is opening but the Query Widget itself is not opening.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::YYpM?ecid=a&go_to=//temp_yn_comment

**Comment by MartijnR** [comment]
needs fix in enketo-core

**Comment by MartijnR** [comment]
* [ ] check gotohidden functionality after enketo-core changes
