### ISSUE TITLE
space + date shows as correct but not stored in model?

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#196]
confirmed

**Comment by MartijnR** [comment]
the month-year widget resets to empty if a space is added.

**Comment by MartijnR** [comment]
Another issue is when typing "2000-02-03 ." the value remains shown but is invalid and not recorded in model.

**Comment by MartijnR** [comment]
fixed in master and develop

**Comment by pbowen-oc** [comment]
@MartijnR - The fix was to first trim leading and trailing whitespace, if present, and to then reject any value that is not the expected format. Is that correct?

**Comment by MartijnR** [comment]
Yes, that was one of the fixes. The other one was deeper down in the engine to reject any character before or after the date (to avoid the same issue with e.g. a dot character added at the end).
