### ISSUE TITLE
date(concat('2019', '-', '12', '-', '15')) string value has time + tz component

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#197]
A day earlier or later doesn't. So something odd going on.

**Comment by MartijnR** [comment]
Caused by hack to strip time component and DST.

Possible fix: 

Convert to current time zone first, before checking for midnight and stripping timezone component.

**Comment by pbowen-oc** [comment]
![2019-04-16 15_51_24-Window](https://user-images.githubusercontent.com/25179620/56239709-b79a1980-605f-11e9-8413-6bde4394f297.png)
![2019-04-16 15_50_58-Window](https://user-images.githubusercontent.com/25179620/56239710-b79a1980-605f-11e9-9292-042c3b98f2f8.png)

**Comment by MartijnR** [comment]
* [ ] try to run full form above (won't pass ODK validate)

**Comment by MartijnR** [comment]
* [ ] deploy fix when npm publishing works again

**Comment by MartijnR** [comment]
fixed in `master`. Will also merge into develop later today, if I don't forget (am trying to squeeze in another issue first)

**Comment by MartijnR** [comment]
* [ ] create simpler form that passes ODK Validate
* [ ] reproduce in Enketo Core
* [ ] figure out if same as #197
* [ ] run enketo-xpathjs tests in FF
