### ISSUE TITLE
Repeating Group with relevant expression is not working as expected

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#199]
The attached form has an RG with a relevant expression. The RG has repeat_count = 4. When the form is first loaded (see screenshot below from Preview), the RG is visible even though the relevant condition hasn't been met yet. Additionally, the RG displays with a relevant error message. Also, the RG has a calculated item that is not populating in the first row (but it is working for rows 2-4)

I also tried the same form but with the repeat_count removed. In that case, the RG did not display on form load. However, If I triggered it to display by selecting Yes in the radio button that triggers it and then added a row to the RG, when I then deselected the radio button  the RG remained visible and showed the relevant error message.

The RG has one calculate item and one calculated text item. The expectation is that if the RG becomes irrelevant and only calculated items in it have values than the RG should not be displayed.

![2019-04-17 12_31_23-OpenClinica](https://user-images.githubusercontent.com/25179620/56304999-516bd000-610d-11e9-8a3a-7d82185be048.png)

[RG relevant test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3090618/RG.relevant.test.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::Z769N6Jy?ecid=1

**Comment by MartijnR** [comment]
For some reason, the relevant check in the calculate module is not doing what it is doing.

* [ ] run in Enketo Express to see if customization is the cause

**Comment by pbowen-oc** [comment]
Just an FYI that this is occurring for us in Production, too, so it seems have been around for a while.
