### ISSUE TITLE
Extra entry for value changed from "" to "" when calculated item becomes irrelevant

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#201]
Steps:
1. Make a calculated item be relevant
2. Add a query to the item
3. Make the item be irrelevant (ensure the item is actually able to be hidden)
4. Make the item be relevant again
5. Click the Query Widget

Expected:
There is an autoquery that closed the query when it was hidden. If the item had a non-null value when it was hidden, there will also be an entry for value changes from something to null.

Actual:
In addition to the expected entries, there is also an entry for a value change from null to null when the item was hidden.

![2019-04-22 15_14_49-Window](https://user-images.githubusercontent.com/25179620/56520431-68962d80-6512-11e9-940f-b41ef8e69879.png)

**Comment by MartijnR** [comment]
fixed in `master`

**Comment by pbowen-oc** [comment]
@MartijnR - Can you merge this into develop, too?

**Comment by MartijnR** [comment]
yes, done now
