### ISSUE TITLE
Form fails to load correctly in Safari

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#204]
We have a form that fails to load correctly in Safari on a Mac. It seems to work as expected in Chrome. However, it loads with an error message in Safari, the query text fields are laid out separately (not part of a query widget), and data isn't submitted.

[Safari error XForm from Dev.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3113625/Safari.error.XForm.from.Dev.xml.txt)

[PhysicalExam.pab.zip](https://github.com/OpenClinica/enketo-express-oc/files/3113627/PhysicalExam.pab.zip)

![image (7)](https://user-images.githubusercontent.com/25179620/56682583-d9b41d00-6699-11e9-8833-35b30b29b9cd.png)

![safari-issue](https://user-images.githubusercontent.com/25179620/56682547-c30dc600-6699-11e9-9ded-7b7d8af50cee.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::cSI10CuT?ecid=1

**Comment by MartijnR** [comment]
* [ ] fix in Enketo-core
* [ ] deploy in master and develop

**Comment by MartijnR** [comment]
deployed fix in `master`. 

Will soon also merge into `develop`

**Comment by pbowen-oc** [comment]
Was this error due to the usage of repeat_count?

**Comment by MartijnR** [comment]
Yes, and perhaps other repeat usage as well. It was a simple syntax error that Chrome apparently (and unhelpfully allows) and Safari is (correctly) strict about.

**Comment by MartijnR** [comment]
in develop as well now
