### ISSUE TITLE
Required asterisk doesn't disappear after data entry into radio button item

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#206]
The required field asterisk for a radio button item is not disappear after data is entered for the item. This is working correctly for dropdown items. Note that the radio button field does not display a required error message in this state, it is just the asterisk that is the issue.

See AE Serious question at the end of this group:
![2019-04-29 15_04_06-](https://user-images.githubusercontent.com/25179620/56920526-6d6a5c80-6a91-11e9-9d5c-57da85a58e40.png)

[radio button required asterisk doesn't disappear.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3128859/radio.button.required.asterisk.doesn.t.disappear.xml.txt)

[Kitchen_Sink-PAB1.zip](https://github.com/OpenClinica/enketo-express-oc/files/3128861/Kitchen_Sink-PAB1.zip)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::EdSCUheK?ecid=1

**Comment by MartijnR** [comment]
fixed in master and develop
