### ISSUE TITLE
Firefox date item clear button out of place

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#207]
In a grid form, Firefox is showing a date item's clear button in the column for the next item to the right:

[RG relevant test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3129145/RG.relevant.test.xml.txt)

![Reset-Year](https://user-images.githubusercontent.com/25179620/56925888-6d248e00-6a9e-11e9-917b-ca82af624015.png)

**Comment by MartijnR** [comment]
* [ ] fix in enketo-core

**Comment by MartijnR** [comment]
This issue is not present in enketo-core. It is introduced in enketo-express

* [ ] fix in enketo-express

**Comment by MartijnR** [comment]
https://github.com/philipwalton/flexbugs/issues/152

**Comment by MartijnR** [comment]
* [ ] merge into this fork (includes other core fixes)

**Comment by MartijnR** [comment]
fixed in both master and develop
