### ISSUE TITLE
Hidden repeating group displayed with relevant error on load if it has previous query history

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#208]
[strict xform test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3133484/strict.xform.test.xml.txt)

In this XForm (or my earlier, non-strict variants), if I open the form as new, select Yes for the Blood Pressure question on page 2 (which makes an RG some items relevant and calculates some values) and then select No and close the form, when I reopen the form the hidden group is displayed with a relevant error with no values displayed. Expected behavior is no error displayed and no values displayed.

Note: This issue is only observed upon reopening the form after selecting Yes then No in a prior form editing session. It does not occur in the same session as when the user selects Yes then No.

![2019-04-30 19_35_08-OpenClinica](https://user-images.githubusercontent.com/25179620/57000040-dc25e380-6b7f-11e9-9289-be9853c42ad9.png)

We had previously addressed an issue like this but I don't recall if it was primarily fixed on your end or ours. I pulled the instance from the browser but it doesn't appear very user-friendly. Hopefully that can show which side this issue comes from.

[instance for unexpected relevant error on reopen form.txt](https://github.com/OpenClinica/enketo-express-oc/files/3133506/instance.for.unexpected.relevant.error.on.reopen.form.txt)

It also may be related to https://github.com/OpenClinica/enketo-express-oc/issues/199. That issue still appears to be resolved in our develop build based on the small test forms attached. Of note, the form attached to that issue does not exhibit this same problem.

I'm observing this in our production environment and also with the latest develop build.

**Comment by pbowen-oc** [comment]
I reproduced this with a somewhat smaller version of the form by cutting a bunch of the end off (same steps as above):

[strict xform test version 23a.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3133565/strict.xform.test.version.23a.xml.txt)

[instance for unexpected relevant error on reopen form - version 23a.txt](https://github.com/OpenClinica/enketo-express-oc/files/3133566/instance.for.unexpected.relevant.error.on.reopen.form.-.version.23a.txt)

![2019-04-30 20_27_08-OpenClinica](https://user-images.githubusercontent.com/25179620/57001380-607b6500-6b86-11e9-9321-1cfe699c34ac.png)

**Comment by MartijnR** [comment]
Thanks for sending the instance as well. 

I see some populated dn nodes under `bp_rg`.

```xml
<bp_rg enk:last-used-ordinal=\"1\" enk:ordinal=\"1\">
            <bp_rg_num_init></bp_rg_num_init>
            <bp_rg_num></bp_rg_num>
            <bp_row></bp_row>
            <bp_pos></bp_pos>
            <bp_sys></bp_sys>
            <bp_sys_val></bp_sys_val>
            <bp_sys_count></bp_sys_count>
            <bp_dia></bp_dia>
            <bp_dia_val></bp_dia_val>
            <bp_dia_count></bp_dia_count>
            <bp_ratio></bp_ratio>
            <bp_ratio_hidden></bp_ratio_hidden>
            <bp_dt_prec></bp_dt_prec>
            <bp_dt_ymd></bp_dt_ymd>
            <bp_dt_ym></bp_dt_ym>
            <bp_dt_y></bp_dt_y>
            <bp_dt></bp_dt>
            <bp_dia_count_comment></bp_dia_count_comment>
            <bp_row_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:37.426 Z\"},{\"type\":\"audit\",\"message\":\"Value changed from \\\"1\\\" to \\\"\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:44.869 Z\"}]}</bp_row_comment>
            <bp_dt_ym_comment></bp_dt_ym_comment>
            <bp_dt_prec_comment></bp_dt_prec_comment>
            <bp_sys_comment></bp_sys_comment>
            <bp_ratio_hidden_comment></bp_ratio_hidden_comment>
            <bp_sys_val_comment></bp_sys_val_comment>
            <bp_dt_y_comment></bp_dt_y_comment>
            <bp_rg_num_comment></bp_rg_num_comment>
            <bp_rg_num_init_comment></bp_rg_num_init_comment>
            <bp_pos_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"Standing\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:37.659 Z\"},{\"type\":\"audit\",\"message\":\"Value changed from \\\"Standing\\\" to \\\"\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:45.108 Z\"}]}</bp_pos_comment>
            <bp_dia_val_comment></bp_dia_val_comment>
            <bp_ratio_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"0\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:37.896 Z\"},{\"type\":\"audit\",\"message\":\"Value changed from \\\"0\\\" to \\\"\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:45.350 Z\"}]}</bp_ratio_comment>
            <bp_dt_comment></bp_dt_comment>
            <bp_sys_count_comment></bp_sys_count_comment>
            <bp_dt_ymd_comment></bp_dt_ymd_comment>
            <bp_dia_comment></bp_dia_comment>
        </bp_rg>
```

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=vitals-1_2(3)&ecid=1&instance=<demo-vitals-grid-v22-strict xmlns:enk=\"http://enketo.org/xforms\"><page1><temp_yn>2</temp_yn></page1><page2><bp_yn>2</bp_yn><bp_rg enk:last-used-ordinal=\"1\" enk:ordinal=\"1\"><bp_row_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:37.426 Z\"},{\"type\":\"audit\",\"message\":\"Value changed from \\\"1\\\" to \\\"\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:44.869 Z\"}]}</bp_row_comment></bp_rg><bp_rg_review enk:last-used-ordinal=\"1\" enk:ordinal=\"1\"><bp_review_pos_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"1\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:40.796 Z\"},{\"type\":\"audit\",\"message\":\"Value changed from \\\"1\\\" to \\\"\\\"\",\"user\":\"pbowenadm\",\"assigned_to\":\"pbowenadm\",\"date_time\":\"2019-05-01 00:19:48.157 Z\"}]}</bp_review_pos_comment></bp_rg_review></page2></demo-vitals-grid-v22-strict>&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit
```

**Comment by MartijnR** [comment]
The check for whether bg_review_pos_comment is a dn (and is to be ignored) is failing because there are currently no repeats in the view.

**Comment by MartijnR** [comment]
2 implemented

**Comment by MartijnR** [comment]
in master. develop branch to follow
