### ISSUE TITLE
VAS item with strict required shows Required popup upon first value selection

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#209]
If a VAS item has a strict Required defined (such as for our Participate view), when the first value is entered for the item (so going form null to some other value), it is showing the Strict Required popup and showing several errors in the console:
Uncaught RangeError: Maximum call stack size exceeded.
    at as.strictRequiredCheckHandler

![2019-05-09 15_24_55-demo-vitals-grid-v22-strict xls  -  Compatibility Mode - Saved](https://user-images.githubusercontent.com/25179620/57480977-1aea2680-726f-11e9-95a8-874a0f6a044a.png)

This error is not expected to occur since the item 1) already has a null value and 2) is being set to a non-null value.

I retested this on Chrome on my Windows machine and found that if I selected exactly 50 for the first value (i.e., the default value) and I did not see this error. Whenever I selected a different value for the first value, the error above was observed.

**Comment by MartijnR** [comment]
Some infinite loop seems to occur.
I'm going to have to get the XForm. (Ideally a minimalistic version of it to greatly speed up my work.)

**Comment by pbowen-oc** [comment]
Here you go:

[Strict VAS form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3163788/Strict.VAS.form.xml.txt)

Note that this is the XForm I got from using the standard view with Required defined as Strict. The same is occurring for Participate view forms as well (which automatically convert the required items to Strict before we call Enketo).

**Comment by MartijnR** [comment]
Thanks. I will look at this now.

**Comment by pbowen-oc** [comment]
This is failing still with a horizontal VAS (which unfortunately, our customer is using).

**Comment by MartijnR** [comment]
horizontal: http://localhost:8005/single/fs/i/::L2YbuxX2?ecid=1

**Comment by MartijnR** [comment]
Oops, it's the absence of the box that shows the value... Turns out my previous fix was quite silly as it depended on that box to be present. I will fix this within a couple of hours (so today). Sorry about that!

**Comment by MartijnR** [comment]
fix deployed in master and develop!
