### ISSUE TITLE
IE11 and Safari Date calculations only works for specific days of the year

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#213]
In IE11, a date calculation using the date function date(string value) produce a null date value except when the input date is between November 10 and December 31 (inclusive) in any year (I tested inputs for 2016-2019). The calculated value is supposed be exactly 2 years before the input date. When it does calculate a value, it is correct (probably as result of fix #197)

This calculation works as expected in Chrome.

[Ie11 date calc test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3193441/Ie11.date.calc.test.xml.txt)
![2019-05-17 19_42_43-Window](https://user-images.githubusercontent.com/25179620/57961897-1f9e8280-78e0-11e9-8f37-9a986f206de1.png)
![2019-05-17 19_42_15-Window](https://user-images.githubusercontent.com/25179620/57961898-20371900-78e0-11e9-8d6d-613e4df80ce6.png)
![2019-05-17 19_45_05-Window](https://user-images.githubusercontent.com/25179620/57961899-20371900-78e0-11e9-8c90-b3fac6d18116.png)
![2019-05-17 19_44_27-Window](https://user-images.githubusercontent.com/25179620/57961900-20371900-78e0-11e9-9953-69394930860a.png)

Similarly, Safari dates only calculated successfully with dates at the end of the year.
[Diagnosis_4 (1).xlsx](https://github.com/OpenClinica/enketo-express-oc/files/3419399/Diagnosis_4.1.xlsx)
<img width="721" alt="Safari Date calculation" src="https://user-images.githubusercontent.com/25179620/61670294-2b783d80-acb1-11e9-9274-3cadcfa9105f.png">
[Safari Date calculation.mp4.zip](https://github.com/OpenClinica/enketo-express-oc/files/3419402/Safari.Date.calculation.mp4.zip)

**Comment by MartijnR** [comment]
* [ ] check if fixed in #233

**Comment by pbowen-oc** [comment]
Resolved by updating the form definition to pad date values as expected.
