### ISSUE TITLE
OC3: encrypt preview id

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#216]

**Comment by MartijnR** [comment]
tbc:

* does OC store URL
* version

**Comment by MartijnR** [comment]
To run this version, we need to downgrade npm from version 6 to version 3: `npm install -g npm@3`.

**Comment by MartijnR** [comment]
@pbowen-oc , just to be absolutely sure, you don't need this feature in the modern Enketo right? (You mentioned you are encrypting the URLs on your side, but maybe you want to remove that or have extra security).

**Comment by pbowen-oc** [comment]
I don't think this will offer any benefit to what we already have in place for the current version. I will let @svadla-oc confirm.

**Comment by MartijnR** [comment]
Thanks. The fix for OC3 is in the `1.35.1.dirty-fixes` branch.

**Comment by svadla-oc** [comment]
> I don't think this will offer any benefit to what we already have in place for the current version. I will let @svadla-oc confirm.


Yes, I agree. We don't need this for OC4.
