### ISSUE TITLE
iOS - Read-only date item appears with interactive selector

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#219]
I have a form that has a read-only date item populated by a calculation using the format-date function. I think the syntax of the calculation is invalid, but Enketo loads the form without error.

[dateformat_xform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3283538/dateformat_xform.xml.txt)

When I open the form in Chrome on my PC, the date item stays blank (I assume because of the syntax of the calculation).
![2019-06-12 19_48_50-OpenClinica Participate](https://user-images.githubusercontent.com/25179620/59393924-a150c700-8d4b-11e9-977f-727a1ba4d332.png)

However, when I open the same form in Chrome on my iPhone (in the same view), the date item appears with a selector that is interactive and a date I choose from it is saved back to the server.

![Participate formatdate screenshot](https://user-images.githubusercontent.com/25179620/59393988-f42a7e80-8d4b-11e9-85c9-8c24e62a6af7.png)

My expectation is that the item will not be interactive since it is defined as read-only even if there is a syntax problem with the calculation.

**Comment by MartijnR** [comment]
Showing the datepicker for a readonly field is a bug in the Safari webview that Chrome on iOS uses: https://codepen.io/MartijnR/pen/OeoOoV

* [ ] Is model changed?

**Comment by MartijnR** [comment]
@pbowen-oc, the not-so-nice but functional workaround can be activated by adding a new widget.

If the OC config.json does not include a `widgets` property (i.e. an override of the default config), nothing has to be done.

If the OC config.json does include a `widgets` property the item "date-native-ios" should be added to the value (array).

**Comment by pbowen-oc** [comment]
This code appears to cause our forms to load with a lot of errors in the console and prevents printing forms (the popup appears when clicking the print icon, but the Prepare button does not trigger anything - tested in Chrome and Firefox on PC/Mac).

We do not use the widgets property, so we did not make any config changes.

My standard test form loads with the console full of errors like this since the build this morning:
![2019-07-11 20_33_42-OpenClinica](https://user-images.githubusercontent.com/25179620/61094179-f4399f00-a41b-11e9-9d7d-4968c3865786.png)

**Comment by MartijnR** [comment]
Thanks. I suspect these are two different issue and moved one to #227.

For the loading exceptions in the console, could you share the webform URL please? I think it doesn't happen to all of them.

**Comment by pbowen-oc** [comment]
Here is a sample XForm. If you need more info I can share it on our call.

[form load errors.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3387636/form.load.errors.xml.txt)

**Comment by MartijnR** [comment]
/single/fs/c/::

**Comment by MartijnR** [comment]
@pbowen-oc I'm not able to reproduce locally. I'm hoping the issue disappeared from your latest build...

**Comment by MartijnR** [comment]
* [ ] try running uglified build locally
* [ ] try different form

**Comment by MartijnR** [comment]
I can reproduce this now. It was a setting! I should have thought about that.
