### ISSUE TITLE
Add autoqueries to non-null relevant error items on form close (unless it has an open query already)

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#220]
Following up on issue #170, we want to make items with relevant errors (whether on the item directly or on the group the non-null item is in) behave like items with strict constraint errors when a form is closed in edit mode (whether the form is already complete or not complete).

AC1: When an item on a form evaluates as not relevant or is in a group that evaluates as not relevant but the item has a non-null value, it will be considered to have a relevant error and will show the following message: Message TBD. May be left as is.

AC2: If the form is opened in edit mode, review-only mode, read-only mode, or Study Designer Form Preview, when a relevant error is active on the current page, the user will NOT be prevented from navigating anywhere within the form. (Note: Other hard errors will prevent navigation)

AC3: Relevant errors will not prevent the user from using the Close button on the form.

AC4: If the form is opened in edit mode, when a relevant error is active on the form, the item with the error does not currently have a Query in New or Updated status, the form is already marked complete, and the user clicks the Close button, the user will be prompted to add an autoquery to the item with the relevant error before the form can be closed. (i.e., New or Updated query on this item is required in order to Close the form)

AC5 If the form is opened in edit mode, when a relevant error is active on the form, the item with the error does not currently have a Query in New or Updated status, the form is not yet marked complete, and the user clicks the Close button, the user will be prompted to add an autoquery to the item with the relevant error before the form can be closed. (i.e., New or Updated query on this item is required in order to Close the form)

AC6: Relevant errors will prevent the user from using the Complete button.

AC7: If the form is opened in review-only mode or read-only mode, relevant errors will not prevent the user from using the close button and will not trigger the creation of autoqueries.

**Comment by MartijnR** [comment]
I believe only AC4 and AC5 need work. 

AC7 tbc

**Comment by MartijnR** [comment]
* [ ] if relevant error on group add autoqueries to all question with value inside that group
* [ ] check AC7

**Comment by pbowen-oc** [comment]
I'm seeing one case where this is not working as expected:
1. A group has a relevant expression and is currently irrelevant.
2. Two items in the group have non-null values. 
3. One of those items has a New/Updated query status. The other item has no queries.
4. Close the form.

Expected:
The item that already has the New/Updated query will not be autoqueried. The item with no queries will get an autoquery (after the user is prompted).

Actual:
The user is not prompted and no autoquery is added.

Note: If neither item has a New/Update query, then the user will be prompted and both items with get the expected autoquery.

We may be able to live with this behavior for our current release if the fix is likely to be risky.

**Comment by MartijnR** [comment]
1. http://localhost:8005/::YYpM
2. Temp measured => Yes
3. Temp: 100
4. Temp units: F
5. Temp measure => No

**Comment by MartijnR** [comment]
Same issue occurs with a record that was marked as complete. The fix is straightforward. I'll commit
