### ISSUE TITLE
New Query Widget Feedback

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#221]
Here are our initials findings and feedback after integration with the new Query Widget (#145). The overall impression of this was fantastic.
 
- [x] When a Query is added within the session, leave the Query name for that thread in the left pane. More generally, leave the Query name blank if it isn't present (we should always be passing it in with each record). It already does this in the right pane.
- [x] Remove the "#" that precedes the Query name in both the left and right panes.
- [x] Within session, responses to existing queries do not display the query thread name in the right pane. We only expect new query threads to not display the name within session.
- [x] Value change entries are misaligned in the right pane. They are all the way at the bottom edge of the row (lower than the username/timestamp) rather than aligned vertically with the username/timestamp.
- [x] Styling of right pane is totally different in non-grid forms than grid forms. Beyond just the width being smaller, the query/response input box is completely different. Grid forms are showing it as expected. (related - can we make non-grid forms wider by default?)
- [x] Within session, I'm seeing some (not all) history entries attributed to "Me (null)" and the initials are displaying as "??". If we don't have a user's name to display with history in the session, can we display "Me" as the initials and have the hover text just show "Me"?
- [x] Within session and after closing and reopening the form, autoqueries are attributed to user "root (root)". The History display doesn't seem to be able to parse initials from this and shows them as "??". If the user's name only has one name for some reason, we should just display the single initial (in this case, "R").
- [x] When an item has one or more closed queries and the item's value is changed, the autoquery added as part of updating the query threads to Closed-Modified is not working correctly if the item has a constraint. In that case, the existing threads are each receiving the autoquery as expected, but the autoquery is also being created as a new thread that is immediately set to Closed-Modified. That new query thread is not created when the item doesn't have a constraint.  - REPRODUCIBLE WITH 1 QUERY THREAD THAT IS CLOSED AND NO OTHER THREADS.
- [x] When an item with an active strict error message has one or more closed queries and no open queries and the user closes the form and chooses to add autoqueries, the autoquery added to that item is starting in Updated status rather than New status.
- [x] When an error message is active, opening the Query Widget for the item and clicking Add New Query is not autopopulating the error text like it used to. We'd like it to populate there for a New Query entry (but not in the Response box for an existing Query or for a new Annotation).
- [x] Can we change the /instance/note endpoint to always open to View All History when a query thread is not passed in? We want to b able to open to a specific thread by passing the ID OR go to View All History by not passing in an ID. Currently, this is working the same way as activity within the form - If the item has only one open query, the widget is opening to that thread even when we don't pass a thread ID in. Note: To be clear, we only want to change the endpoint behavior, not the on-form query bubble behavior.

**Comment by MartijnR** [comment]
* [ ] merge

**Comment by MartijnR** [comment]
merged in master!

**Comment by MartijnR** [comment]
last bullet point also needs to be done for rfc views

**Comment by pbowen-oc** [comment]
- [ ] When a Query thread already has a user-facing ID, can you have a "#" precede it in both the left pane and right pane (example 123 will be displayed as #123)? If there is no Query ID to display yet (since it is the same session the query was thread was created in), do not display the # by itself (just leave it blank). (I know that we originally had this there and then removed it. Now that we have decided to not use a prefix and padding on our end, the # preceding the numeric ID is needed for clarity in the Query Widget again. Sorry for the indecision).
