### ISSUE TITLE
Print view style updates

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#223]
We have some requests to update the style used when we print a form:

1. Group labels are being displayed in bold, but with small text that doesn't stand out. Can these be made to use a larger font?
2. When a blank form is printed and irrelevant items are included in the printed view, the text colors is a little too faint for our users to read easily after being printed on paper. Can we make it a little darker while keeping the style different between relevant and irrelevant items?
3. When a question label is long enough to wrap to the second line in the print view, there is not enough vertical space between the lines of text and so they are hard to read.

Current example form (Printed to PDF from the icon on the form):
[Printed Form Example.pdf](https://github.com/OpenClinica/enketo-express-oc/files/3319120/Printed.Form.Example.pdf)

**Comment by MartijnR** [comment]
* [ ] group label size
* [ ] irrrelevant
* [ ] line-height

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/commit/d8dc02be61c7e74fc1236a9e7c2d230c8fba93fd
