### ISSUE TITLE
Can we widen form in non-Grid themes?

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#225]
look into consequences

**Comment by MartijnR** [comment]
I cannot find negative consequences. Unless I'm overlooking something it's just a matter of preference. I think 1100 px (as in Grid Theme) doesn't look as good as the current value (720px).

So I'm just changing to 900px now, and then let's adjust as desired (or find negative consequences).

**Comment by MartijnR** [comment]
I have only changed the "oc" theme. Let me know if you'd also like to make the same change to the "kobo", "formhub" and "plain" themes.

**Comment by MartijnR** [comment]
c844775f0acef076b46d93435f38ceacc7e5b7e6

**Comment by pbowen-oc** [comment]
It seems to be working fine at the new width.

As we noticed on our call yesterday, text fields are not taking the new full width and seem to be limited to the old width. When the form is viewed on a smaller device, the field continues to take only a fraction of the space available. Can we make the field take advantage of the new form width?

**Comment by pbowen-oc** [comment]
Let's hold off on my last comment. I think it may have looked a little off just due to the specific form I had tested it on. Since the extra space is currently used to ensure that reset/download/etc buttons have space, we should reconsider this.
