### ISSUE TITLE
Print View History updates

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#226]
We'd like to make the following tweaks when the Print View of a form contains History (i.e., Query) items:

- [x] If a History item has no history to display, show "None" in the box so the lack of history is explicit.
- [ ] Display the History item label (e.g., "History for - ItemLabel") at the top of the history for the item instead of at the bottom.
- [x] Update the History label to append the item name at the end in parentheses (e.g., "History for - Date of Birth (dob)"; where "Date of Birth" is the item label and "dob" is the item name).

**Comment by MartijnR** [comment]
* I used the existing (translateable) string 'No History'. Let me know if that should be changed to 'None'.
* I could not reproduce the misplaced History label (at bottom)

**Comment by pbowen-oc** [comment]
It looks like the label placement issue is related to nested groups:
![2019-07-05 16_57_05-OpenClinica](https://user-images.githubusercontent.com/25179620/60744923-217edc80-9f46-11e9-9379-62f4ced90cb3.png)

I'll send this XForm to you.

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=http://localhost:3000/form/History-label-issue/form.xml

Thanks!
