### ISSUE TITLE
Label text overlap with query icon in Grid forms

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#228]
It seems that the size of the query icon is a little bigger than Enketo calculates it to be. There is some overlap with label text in some cases. As this screenshot shows, though, if the overlap would be significant enough, the label text is forced to break to go to the next line.

![2019-07-12 20_48_54-OpenClinica](https://user-images.githubusercontent.com/25179620/61164848-2f54d480-a4e7-11e9-8018-6497304535f2.png)

**Comment by MartijnR** [comment]
```css
.question .btn-comment {
    margin: 0 8px;
}
```

* [ ] also fix special case: analog scale widget vertical
