### ISSUE TITLE
Regex evaluation exception 

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#230]
see email on 7/17 from Paul

**Comment by MartijnR** [comment]
caused by `'` in expression which seems like it is indeed an error in the expression

* [ ] figure out how to rewrite

**Comment by MartijnR** [comment]
@pbowen, the `'` in the expression should be replaced with `&quot;`

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. I was just starting to experimenting with that myself.
