### ISSUE TITLE
Query Widget Email checkbox is missing for image select item 

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#237]
The Query widget is not showing an Email checkbox for either a new query or a response to a query, but it seems to be limited to a select item that doesn't show radio buttons/checkboxes and just has the user select an image directly.
![2019-08-02 01_14_07-OpenClinica](https://user-images.githubusercontent.com/25179620/62346270-871da480-b4c3-11e9-92fb-091ae7f31534.png)
![2019-08-02 01_16_26-OpenClinica](https://user-images.githubusercontent.com/25179620/62346272-871da480-b4c3-11e9-9271-f2f590333a41.png)

**Comment by MartijnR** [comment]
fixed in `master` from tag `1.77.1.oc-4` onwards
