### ISSUE TITLE
Item with no label (Cannot read property 'after' of undefined error when opening a form)

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#238]
One of our users reported the following error that had seemingly been working as expected before our release last night:
![2019-08-02 13_17_41-OpenClinica](https://user-images.githubusercontent.com/25179620/62387268-1d83b180-b528-11e9-8e59-42173d72b177.png)

This error is causing the form to load in a non-functional state based on the latest changes to block data submissions from invalid forms.

I will send the XForm via email.

**Comment by pbowen-oc** [comment]
@MartijnR - I sent an email with the form details.

**Comment by pbowen-oc** [comment]
I'm working on debugging it myself as well. I noticed the form has several note items which are marked as readonly (which is redundant at best). I removed readonly from these but still get the error.

**Comment by pbowen-oc** [comment]
I saw that 2 of the smoking duration questions did not have labels. I added labels to them but still get the same error.

**Comment by pbowen-oc** [comment]
Is there already validation in place we can call to check these issues on upload (items lacking labels and note items marked as readonly)?

**Comment by MartijnR** [comment]
Items lacking labels is not allowed by pyxform, I think, but I'll check (might be ODK Validate). Will also check if Enketo Validate catches this.

**Comment by MartijnR** [comment]
* [ ] fix to tolerate absence of labels in sent form
* [ ] check if latest version of Enketo Validate discovers an empty label issue

**Comment by MartijnR** [comment]
@pbowen-oc version 1.77.1.oc-3 has the fix. The goal was to get the forms to work, but questions without labels may have styling issues.

**Comment by MartijnR** [comment]
*  [ ] add check to enketo-validate

**Comment by pbowen-oc** [comment]
Thanks, Martijn. We're deploying and testing now.

**Comment by MartijnR** [comment]
This may be useful for future. It validates in OC mode: https://validate.enketo.org/oc/

**Comment by pbowen-oc** [comment]
Thanks. We'll need to update to use that in the next major release.

**Comment by pbowen-oc** [comment]
The fix is working as expected.
