### ISSUE TITLE
IE11 - Query Widget not displayed (not query icon to click)

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#239]
IE11 doesn't seem to be displaying the query icon for any items in any form view:
![2019-08-07 00_17_31-OpenClinica - Internet Explorer](https://user-images.githubusercontent.com/25179620/62594544-0850af00-b8a9-11e9-9e4a-4cfdae90565e.png)

**Comment by MartijnR** [comment]
might be caused by lack of SVG support

**Comment by MartijnR** [comment]
fixed in `master` (no tag generated yet)
