### ISSUE TITLE
Autoqueries submitted silently in review-only mode when leaving form via browser controls

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#240]
Steps:
1. Open an existing form in review-only (note-only) mode such that a constraint error is visible on form load (i.e., create the form with some data and then change the form definition to make the existing data cause a constraint violation)
2. Use the browser Back button to leave the form (NOT the Close button on the form)

Expected:
No autoquery was added to item that had a constraint error message displayed. No submissions should be permitted for review-only mode except for user-initiated Query entries.

Actual:
An autoquery was added to the item with the constraint error. The submission can be seen in the Chrome Network tab and the Submission queue operation can be viewed in the Console.

It appears that the logic attached to the Close button is not being respected when the form is being left via other means. If the form is opened in edit mode and closed in this manner, autoqueries should be added without user prompt. However, this should never happen for review-only or read-only modes. The Close button appears to be performing correctly based on which mode the form was opened in.

**Comment by pbowen-oc** [comment]
@MartijnR - Please put the fix for this in Master.

**Comment by MartijnR** [comment]
```
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><wh_y>1</wh_y><temp_group><temp>37</temp></temp_group></page1></demo-vitals-grid-v9>&instance_id=b&load_warning=Hey you&ecid=a" http://localhost:8005/oc/api/v1/instance/note
```

**Comment by MartijnR** [comment]
The only thing I've done is disabled the 'beforeunload' handler for note-only (and readonly) views. If more complex changes are required, we should do this on top of the new headless mode logic (which is in `develop`).

**Comment by MartijnR** [comment]
* [ ] re-enable queue-check for note-only views
