### ISSUE TITLE
Strict constraint on date items not functioning properly

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#241]
A date item with a strict constraint based on today() is not functioning as expected. When I enter a future date (which violates the constraint), the strict error popup appears as expected. However, the value of the item is not reset to the old value and the new (invalid value) persists in the display. I confirmed that the invalid value is not submitted back to us. That is the behavior in Chrome.

In Edge, the same occurs, but the invalid date also triggers a long running script that freezes the form for a minute or so.

Example form:
[strict error not working for date item.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3527533/strict.error.not.working.for.date.item.xml.txt)

**Comment by pbowen-oc** [comment]
@MartijnR - Please fix this in Master.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::U078RHak?ecid=1

**Comment by MartijnR** [comment]
question has both strict required and strict constraint. Strict constraint empties invalid item, which is not allowed by the strict required logic, creating an infinite loop.

**Comment by pbowen-oc** [comment]
@MartijnR - My expectation is that what when the new value is rejected, it reverts to the old value regardless of whether the old value is considered valid or not. One case where this behavior is important is when data is entered in one version of a form and then modified in a different version of the form with updated logic. In this case, the value may be invalid when the form is opened and it should handle the user entering a different invalid value by reverting back to the most recent value since that is what we have actually saved.

BTW - On my test form, the temperature item (a decimal) has strict required and strict constraint and this scenario seems to work fine for it. I have definitely tested this case before (in Chrome) and always found the item to be reverted as expected. It looks like date items are being handled differently.

**Comment by pbowen-oc** [comment]
It seems to work as expected on my iPhone (i.e., touchscreen display mode).

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/commit/38315b659b68aba64ce2148a2a8aa1ac31aa9366#diff-3defe2d89350e736e8990b8cb92330b3

**Comment by MartijnR** [comment]
* [ ] test for date widget regressions, in particular for pasting, and entering values by keyboard with or without pressing Enter
* [ ] see if automated test can be developed, in particular for infinite loops
* [ ] merge to master in enketo-core
* [ ] propagate all the way to enketo-express-oc

**Comment by MartijnR** [comment]
`1.78.0.oc-1` is ready for testing. I'm confident this issue is resolved. However, the fix required updating enketo-core and merging with latest enketo-express, so it has some other changes.

**Comment by pbowen-oc** [comment]
Thanks!

**Comment by pbowen-oc** [comment]
Looks good!
