### ISSUE TITLE
IE11 - VAS item not displayed correctly on Grid form

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#242]
Using my usual test form, the layout is not as expected for a VAS item.

In Chrome, the VAS item correctly appears on it's own row. 
![2019-08-28 14_43_21-OpenClinica](https://user-images.githubusercontent.com/25179620/63883816-fa231980-c9a2-11e9-9e39-2d37bb9adbbe.png)

In IE11, the VAS item appears on the same row as the prior item and does not fit.
![2019-08-28 14_43_01-OpenClinica - Internet Explorer](https://user-images.githubusercontent.com/25179620/63883850-11620700-c9a3-11e9-94ae-5b5171e6cc1a.png)

(note: I had to zoom out in the browser to capture the full height of the item, but that did not alter the layout)

[IE11 VAS layout issue.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3552405/IE11.VAS.layout.issue.xml.txt)

It looks like in this case the group the items are in are defined as w5 and the image selection item and VAS item are each defined as w4.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::7tXKdyKY?ecid=1

**Comment by MartijnR** [comment]
fixed in `1.78.0.oc-2`

**Comment by pbowen-oc** [comment]
Looks good
