### ISSUE TITLE
Calling /pdf for a record in quick succession shows 405 error

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#246]
The protection for 'Record is already being edited' kicks in. I think this protection is not appropriate for the PDF end point (since it shouldn't edit anything unless I misremember).

**Comment by MartijnR** [comment]
probably same for /instance/view

**Comment by pbowen-oc** [comment]
Note to self: Expiry for record cache is the configuration

**Comment by MartijnR** [comment]
Not the case with /instance/view and /instance/view/pdf in /api/v2. Looks like this is specific to OC's API only.

**Comment by MartijnR** [comment]
* [ ] fix broken tests
