### ISSUE TITLE
Dropdown items are not showing any value in print view

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#256]
Dropdown items are rendered radio buttons in print view so that all options can be seen. However, the print view is not showing the current value of the item and is always displaying it as null.

<img width="1920" alt="render" src="https://user-images.githubusercontent.com/25179620/68176913-93971a80-ff54-11e9-93ea-2f5d6ed4c322.png">

**Comment by pbowen-oc** [comment]
Possibly the same issue - We noticed that printing from Edge that no radio buttons are showing values.

**Comment by MartijnR** [comment]
* [ ] check select_one non-grid
* [ ] check select multiple non-grid
* [ ] check select_one grid
* [ ] check select_multiple grid

**Comment by MartijnR** [comment]
@pbowen-oc, is it possible you are seeing this on an old version? 

<img width="417" alt="Screen Shot 2019-11-05 at 3 32 07 PM" src="https://user-images.githubusercontent.com/627350/68253585-7eb69780-ffe5-11e9-85cc-ad6fb08ff1b6.png">

**Comment by pbowen-oc** [comment]
@MartijnR - I just rechecked this on our dev environment with the latest Enketo deployed and it seems to working fine (at least in Chrome). I'll reopen this issue if there is something specific that is still causing it to fail on the current build.

**Comment by pbowen-oc** [comment]
I opened #257 for a seemingly related issue in Edge where all radio buttons and checkboxes are printing as null. This one is still occurring on the latest build.

**Comment by pbowen-oc** [comment]
@MartijnR - We noticed that while this was working as expected when we print from within a form, using the Print API did not show the values here.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><wh_y>1</wh_y><wh_unit>1</wh_unit><temp_group><temp>37</temp></temp_group></page1></demo-vitals-grid-v9>&instance_id=b&ecid=a" http://localhost:8005/oc/api/v1/instance/view/pdf

```

**Comment by MartijnR** [comment]
I wonder if the @media screen vs @media print is not working in puppeteer.

**Comment by MartijnR** [comment]
Using the built-in non-headless Chrome Print -> Save as PDF, the same issue occurs.

**Comment by MartijnR** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1027319&can=2&q=radial-gradient%20with%20opacity

**Comment by MartijnR** [comment]
I don't think the Chrome bug will be fixed any time soon. It seems best to not use custom styling for radiobuttons (and checkboxes for consistency and to also solve the Edge bug #257) in print views. This means the printout will look different than the screen but at least it should robustly show what is checked.

**Comment by MartijnR** [comment]
A Chromium dev (very responsive!) discovered it is PDF viewer related (see link above for bug tracker). When opening the PDF file in Chrome it does show radio buttons with an opacity.

This probably doesn't really change the issue, because I know you are not using Mac OS (Preview) but some other PDF viewer. So it seems that it may be a pretty common PDF viewer issue. Therefore, I think we should proceed with the workaround in the previous comment.

**Comment by pbowen-oc** [comment]
The style for dropdown items seems to look too much like disabled items rather than like the normal radio buttons:
[✅ クリコアの秘密の部屋-026_Casebook_2019-12-04-024602913+0000.pdf](https://github.com/OpenClinica/enketo-express-oc/files/3923859/-026_Casebook_2019-12-04-024602913%2B0000.pdf)

**Comment by pbowen-oc** [comment]
@theywa - Please see the Weight and Height Units item in the PDF attached in my last comment.

**Comment by MartijnR** [comment]
* cannot reproduce with older version of vitals form in enketo-core nor in enketo-express-oc, so I think it is fixed. 

[Vital Signs.pdf](https://github.com/OpenClinica/enketo-express-oc/files/4037563/Vital.Signs.pdf)

@bowen-oc, if you can still reproduce, please post XForm.

**Comment by pbowen-oc** [comment]
It is working for me now, too.
