### ISSUE TITLE
Printing from MS Edge does not show values for radio button/checkbox items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#257]
All radio button an checkbox items appear to be rendering as null when printed from MS Edge:
![2019-11-05 18_39_05-OpenClinica - Print](https://user-images.githubusercontent.com/25179620/68255742-217a1080-fffc-11e9-80df-8d883ac3a616.png)

I noticed that autocomplete, image-map, and compact select_one items are showing values as expected.

**Comment by MartijnR** [comment]
https://answers.microsoft.com/en-us/edge/forum/all/microsft-edge-does-not-allow-users-to-print/f1631753-cfe6-44c0-be34-b1dd10ae9b46

**Comment by MartijnR** [comment]
This issue, though serious, would resolve itself soon after January 2020. However, the solution for the Chrome bug #256, could fix this too.
