### ISSUE TITLE
Validator reporting nested repeat warning without any nested repeats

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#260]
I uploaded the following XForm to the OC Validator URL and it reported a warning for:
"Warnings:

Repeat "bp_rg" contains a nested repeat. This not recommended."

[xform_sample.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3817296/xform_sample.xml.txt)

This form does not have nested repeats so this was unexpected.

**Comment by MartijnR** [comment]
Ah thanks!

**Comment by MartijnR** [comment]
Still need to release new version

**Comment by MartijnR** [comment]
done -> https://validate.enketo.org/oc/
