### ISSUE TITLE
Date arithmetic failure in IE

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#261]
We have a calculation that computes age by subtracting DOB entered on the form from an event date passed into the form. The event date is either a pure date (for example, "2019-08-21") or a date and time (for example, "2019-08-21 11:11:00.0"). In Chrome, the age calculation works with either event date format.

![2019-11-07 17_05_24-OpenClinica](https://user-images.githubusercontent.com/25179620/68433056-acd1de00-0183-11ea-8e0a-2c392bd8fefe.png)

![2019-11-07 17_05_55-OpenClinica](https://user-images.githubusercontent.com/25179620/68433072-b3605580-0183-11ea-8019-dd1731c436ac.png)

However, in IE11, the age calculation works if the event date is a pure date but fails if it is the date and time.

![2019-11-07 17_13_30-IE Date Calc Test xlsx - Saved](https://user-images.githubusercontent.com/25179620/68433075-b5c2af80-0183-11ea-8452-b8d3c5dc99e9.png)

![2019-11-07 17_15_11-IE Date Calc Test xlsx - Saved](https://user-images.githubusercontent.com/25179620/68433086-bc512700-0183-11ea-8822-96ae72b3ea09.png)

Here is the XForm form these examples:
[date test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3821996/date.test.xml.txt)

**Comment by MartijnR** [comment]
* [ ] check Safari
* [ ] check Firefox

**Comment by pbowen-oc** [comment]
Depending on the issue here, we might have other workarounds to use such as advising users to use the substring function to only get the first 10 characters of the date if they are pulling in a value that may have a time as well.

**Comment by MartijnR** [comment]
in EE: http://localhost:8005/preview?form=https://github.com/OpenClinica/enketo-express-oc/files/3821996/date.test.xml.txt

**Comment by MartijnR** [comment]
without external data: 
[date.test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3848904/date.test.xml.txt)

**Comment by MartijnR** [comment]
It looks like the issue may be something very subtle with the datetime format. If you're using the actual dateTime format that Enketo supports, it works in IE11 as well.

E.g. valid are:
* 2019-08-21T11:11:00.000Z
* 2019-08-21T11:11:00.000+06:00
and I think also:
* 2019-08-21T11:11:00+06:00 (without decimal seconds)

**Comment by pbowen-oc** [comment]
We will handle this on our end for now.
