### ISSUE TITLE
Fix zip file (in master)

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#263]
Looks like I messed up the zip file:

- [x] ~~exclude bundle files (as they have to be rebuilt with custom config)~~
- [x] exclude public/js/build entirely
- [x] include public/src/js entirely

_Originally posted by @MartijnR in https://github.com/OpenClinica/enketo-express-oc/issues/262#issuecomment-553101289_

**Comment by MartijnR** [comment]
With the modern build system, the `npx` commands do not work if npm wasn't used to install.

* [ ] fix if possible

**Comment by MartijnR** [comment]
* [ ] add version to zip file name

**Comment by MartijnR** [comment]
Vagrantfile.js
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install -y curl
     curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
     apt-get install -y nodejs
  SHELL
end
```

**Comment by MartijnR** [comment]
`npm rebuild` fixes the `npx` commands but considering the time that takes, it is not so clear installing from zip still has any speed benefits.

**Comment by MartijnR** [comment]
This is working now. Instructions are here: https://github.com/OpenClinica/enketo-express-oc/blob/master/tutorials/03-deploy-from-zip.md

**Comment by pbowen-oc** [comment]
Deployment process seems to be working fine for us.
