### ISSUE TITLE
Queries not being displayed when existing form is opened

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#264]
Queries can be added on a form and are displayed in the query widget. If the form is closed and reopened, the query widget is not displaying any queries and the query bubble does indicate a query status. The query widget is displaying value change history.

![2019-11-13 18_32_34-OpenClinica](https://user-images.githubusercontent.com/25179620/68813584-439b1080-0644-11ea-92f8-d601fc2b0019.png)

I checked the instance being passed in and it include both the query and the value change.
[xform issue 264.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3843917/xform.issue.264.xml.txt)
[instance for issue 264.txt](https://github.com/OpenClinica/enketo-express-oc/files/3843918/instance.for.issue.264.txt)

**Comment by pbowen-oc** [comment]
@MartijnR  - This started occurring last week once we deployed the latest version for the first time in a long time.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::kCfDXGF4?ecid=1

**Comment by MartijnR** [comment]
@powen-oc what is the URL you are seeing this on? It doesn't look like this issue occurs for a simple edit view like http://localhost:8005/edit/fs/i/::kCfDXGF4?ecid=1&instance_id=a

**Comment by MartijnR** [comment]
Oh never mind @pbowen-oc I think I see the issue.

**Comment by MartijnR** [comment]
The stringified JSON in the instance doesn't have the right format. Instead of: `{"queries":[]}`, it contains `{"core/queries": []}`. So I think something changed on the OC side.

**Comment by pbowen-oc** [comment]
You were correct. The data was being passed in incorrectly.
