### ISSUE TITLE
Autocomplete in Chrome doesn't show more than 512 items

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#265]
when scrolling down only (no problem when searching)

might be a browser bug. FF has no problem. Safari doesn't either.

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/19c_8n1SzuyEUY66BktTJHdmlGGPy7LhoOuIFhuh2piM/edit#gid=0

**Comment by MartijnR** [comment]
https://codepen.io/MartijnR/pen/abbXjxW?editors=1000

**Comment by MartijnR** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1026739&can=2&q=datalist

**Comment by MartijnR** [comment]
Chromium dev responded that this is deliberate and they marked it as "won't fix". See link in previous message. They might be open to arguments though.

**Comment by pbowen-oc** [comment]
I agree with Won't Fix for this.
