### ISSUE TITLE
make sure page break is at end of DN history (and not in middle)

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#266]

**Comment by MartijnR** [comment]
The style is already applied to DN history. I actually cannot immediately reproduce a situation that cuts off a query history for a question (Chrome on Mac OC).

**Comment by MartijnR** [comment]
It must be an issue with pdf endpoint.

**Comment by pbowen-oc** [comment]
The sample I had was generated by printing from within the form, not the PDF endpoint.

**Comment by MartijnR** [comment]
Thanks. Could you perhaps share the PDF created by using printing from within the form. Maybe it shows a specific cause that will allow me to reproduce. Alternatively, if you have steps, and an XForm, to reproduce this with, that would be great too.

**Comment by pbowen-oc** [comment]
Example:

[bad pdf formatting.pdf](https://github.com/OpenClinica/enketo-express-oc/files/3893943/bad.pdf.formatting.pdf)

This might be related to the group the items on this page are in.

**Comment by MartijnR** [comment]
(I can reproduce)

`Page-break-inside: avoid` is not working for the history component. This is probably because of `display:flex` (of the history component). It may be easiest to set an explicit height on the history (it's actual height).

* [ ] try setting explicit height on history (its actual height)

**Comment by pbowen-oc** [comment]
The current implementation has history content spilling out of its box as well as the page break issue. See examples below showing history for items in a group - one example where the group is hidden and only the history is shown and one example where the group is not hidden and the items and history are shown.

[OpenClinica - test PDF with hidden item history.pdf](https://github.com/OpenClinica/enketo-express-oc/files/4020798/OpenClinica.-.test.PDF.with.hidden.item.history.pdf)
[OpenClinica - test PDF with no hidden item history.pdf](https://github.com/OpenClinica/enketo-express-oc/files/4020799/OpenClinica.-.test.PDF.with.no.hidden.item.history.pdf)

**Comment by pbowen-oc** [comment]
Long query text is also causing the formatting to break:
![OC11560 - User Input Displayed in History and overlapping the next value](https://user-images.githubusercontent.com/25179620/72014394-c4821d00-322d-11ea-9cb8-317f59bf8a3a.png)

**Comment by pbowen-oc** [comment]
The query text looks better, but the name and date are overlapping:
![Annotation 2020-01-21 221250](https://user-images.githubusercontent.com/25179620/72862679-04201e80-3c9c-11ea-8fe0-d054120f0be4.png)

Note that #282 is also still broken. This PDF was captured from a new form when no record was passed in.

**Comment by pbowen-oc** [comment]
The update looks good:
![Annotation 2020-01-22 155710](https://user-images.githubusercontent.com/25179620/72933547-eef4cf80-3d2f-11ea-8a97-6aee388675d8.png)
