### ISSUE TITLE
PDF endpoint is not printing images that had been entered on the form

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#267]
Printing from within the form is including uploaded images and drawings. Printing the same form with the PDF endpoint is not:

(Left is the PDf endpoint, right is print from within the form)

<img width="1920" alt="image2" src="https://user-images.githubusercontent.com/25179620/69385841-afa5f600-0c8e-11ea-8760-7cf9ce4a1f0b.png">
<img width="1920" alt="Image1" src="https://user-images.githubusercontent.com/25179620/69385842-b03e8c80-0c8e-11ea-9979-5b00192bf334.png">

**Comment by MartijnR** [comment]
* [ ] check if PDF endpoint properly supports loading files with a record
* [ ] test PDF output (may have been fixed with earlier fix)

**Comment by MartijnR** [comment]
@pbowen-oc, my conclusion is that the `instance_attachments` parameter is not passed when OC calls the PDF endpoint. This parameter should be called the same way as in calls to other /instance/* endpoints.

**Comment by pbowen-oc** [comment]
Looks like we found the issue on our end.
