### ISSUE TITLE
PDF endpoint not rendering analog scale correctly

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#268]
Printing from within the form renders the analog scale widget as expected. Using the PDF endpoint does not:

<img width="1920" alt="VAS" src="https://user-images.githubusercontent.com/25179620/69386003-36f36980-0c8f-11ea-9de7-f57c11016caf.png">

**Comment by MartijnR** [comment]
Likely same issue as https://github.com/OpenClinica/enketo-express-oc/issues/256. Will leave separate until confirmed.

**Comment by MartijnR** [comment]
No, it's different, and there is an easy fix for this one.

**Comment by MartijnR** [comment]
* [ ] fix background printing
* [ ] fix location of range
