### ISSUE TITLE
OC3: preview URL returned by API not encrypted?

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#269]

**Comment by MartijnR** [comment]
v2:
```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals" http://localhost:8006/api/v2/survey/preview
```

v1:
```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals" http://localhost:8006/api/v1/survey/preview
```

**Comment by MartijnR** [comment]
Got it @pbowen-oc! The feature was added to /api/v2 since I assumed that's what OC was using. That assumption was wrong as using /api/v1 explains the behavior we are seeing. 

I have no idea what the potential side effects are of switching to api/v2 (all your API requests), so I think the best course of action is to also add the feature to api/v1. Will complete that today.

**Comment by pbowen-oc** [comment]
Thanks, @MartijnR. Yes, the older version we're working with in this case is probably still using api/v1.

**Comment by MartijnR** [comment]
It is done. The new version is `1.35.1.oc-8`.

**Comment by pbowen-oc** [comment]
@MartijnR - Did you make any changes related to this to the form submission view? We are getting 500 errors when we try to submit forms on this branch now and we're wondering if the edit view might be mistakenly using the encrypted version ID.

**Comment by MartijnR** [comment]
There should be no submission-related changes. You can check that the edit view is using unencrypted URLs by the length of the ::ID part (if 4 or 8 characters, it is not encrypted). 

* [ ] I'll check to confirm submission is not broken in an edit view.

**Comment by MartijnR** [comment]
I don't see any difference in submission behavior between the 2 URLs. I also confirmed that /api/v1/instance returns a regular URL (4 character ID).
