### ISSUE TITLE
Printed form not displaying '/' character in history label

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#271]
Printed forms (print to PDF via API or printed from within the form) are not rendering all characters in item labels correctly when they are displayed as History item labels. For example: "History for - A/B (item1)" is being rendered as "History for - A&#2F;B (item1)".

[Printed history not displaying item label characters correctly.pdf](https://github.com/OpenClinica/enketo-express-oc/files/3929818/Printed.history.not.displaying.item.label.characters.correctly.pdf)

[Printed history not displaying item label characters correctly.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3929819/Printed.history.not.displaying.item.label.characters.correctly.xml.txt)

**Comment by MartijnR** [comment]
The code for this is in `/widget/discrepancy-note` in this repo. This app needs to be run to reproduce and fix this issue.

There is some magic happening when the print button is clicked which is done by the `_printify` function.

A few milliseconds later, all this is undone with the `_deprintify` function.

**Comment by theywa** [comment]
[PR](https://github.com/OpenClinica/enketo-express-oc/pull/278) ready for review
