### ISSUE TITLE
participantID supported in PDF views?

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#274]
Should be.

Check `pid` - yep!

* [x] /instance/view/pdf - already supported
* [x] /survey/view/pdf - already supported
* [x] update documentation if necessary - already documented

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><temp_yn>1</temp_yn><wh_y>1</wh_y><wh_units>1</wh_units><temp_group><temp>37</temp></temp_group></page1><page2><vas_question>45</vas_question></page2></demo-vitals-grid-v9>&instance_id=b&ecid=a&pid=TEST" http://localhost:8005/oc/api/v1/instance/view/pdf > ~/Downloads/pid1.pdf
```

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&ecid=1&pid=ANOTHER TEST" http://localhost:8005/oc/api/v1/survey/view/pdf > ~/Downloads/pid2.pdf
```

**Comment by MartijnR** [comment]
I have confirmed this is supported in the PDF views already in the same manner as in other views, using the `pid` parameter in the API call. So I think that parameter is missing when OC makes the PDF api call.

**Comment by pbowen-oc** [comment]
Thanks! I'll let you know if we have any issues using it.
