### ISSUE TITLE
DN history, remove borders + padding

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#275]
to reduce space (around 'Me' and each comment below)

<img width="927" alt="Screen Shot 2019-12-26 at 9 25 33 AM" src="https://user-images.githubusercontent.com/627350/71482791-b1009c00-27c1-11ea-9628-a8cc4185877d.png">

**Comment by theywa** [comment]
Hi Martijn, 
I need help with this ticket, how can I enable/show the dn widget on enketo-express-oc form? I tried to create a survey and instance form from my local enketo-express-oc using `/oc/api/v1` endpoint with the form that comes from server_url(kc.kobotoolbox.org) but I don't see any bubble query(dn_widget) like on runtime.

**Comment by MartijnR** [comment]
Hi dewa, Sorry, I was supposed to describe this issue better, but haven't done it yet. I'll do it today. The DN questions are actually coded into the XForm by OC (doing some XForm manipulation). Here is a form from OC: https://enketo-aggregate.appspot.com/xformsList (formID: "vitals"), that you could launch with:

server_url: https://enketo-aggregate.appspot.com
form_id: vitals

**Comment by MartijnR** [comment]
One trick I use to edit print css, is to comment out 2 lines in public/js/src/module/gui.js

* around line 492:  `//$dn.trigger( 'deprintify.enketo' );`
* around line 524: `//printHelper.styleReset();`

I added screenshot above.

**Comment by theywa** [comment]
No worries and thank you for the guide also here is the [PR](https://github.com/OpenClinica/enketo-express-oc/pull/277) that I created ready for review
