### ISSUE TITLE
Investigate PDF timeout

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#276]
>We are sometimes getting the following error when calling the PDF endpoint:

> 2019-12-09 17:12:42,998 ERROR [Thread-68] c.o.a.o.s.c.x.EnketoAPI [EnketoAPI.java:814] core.org.akaza.openclin ica.exception.OpenClinicaSystemException: ServerError:500 Internal Server Error:{
"message": "PDF generation failed: Navigation Timeout Exceeded: 30000ms exceeded"  

> Do you know which timeout is being exceeded and how we can adjust the timing of it?

> We are currently running this on our normal form server in our Dev environment. I remember that you previously made a hard-coded 30 second timeout configurable and we lengthened it to several minutes. I'm not sure if this could be related.

**Comment by MartijnR** [comment]
It would make a lot of sense to have a different timeout because this endpoint actually renders the whole form, so that would always take a lot longer than a simple URL response.

**Comment by MartijnR** [comment]
Enketo hasn't specified a timeout, so it defaults to 30 seconds.

The OC fork already has `{"headless": { "timeout": 5000 } } setting that we are using for the custom 'headless' views. I think we could re-use this. I don't know why it is set to such a low 5 second default.

* [ ] in enketo/enketo-express copy the "headless.timeout" setting from the OC fork and document it
* [ ] in the pdf controller use this timeout
* [ ] merge into enketo-express-oc

**Comment by MartijnR** [comment]
The existing configuration item:

```json
"headless": {
        "timeout": 10000 
},
```

is now also used for pdf generation. The default value has changed from 5000 milliseconds to 60000 milliseconds.

**Comment by pbowen-oc** [comment]
@MartijnR - This is generally working for us, but some large, forms with resources are taking a little longer. Can we increase this to 2 minutes?

Separately, we should look into a future feature that will not load audio and video files in the Print API. We'll define what to show instead.

**Comment by pbowen-oc** [comment]
We will update the config on our end.
