### ISSUE TITLE
Annotation Widget no longer allows image upload

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#280]
Our existing forms that use the Annotation widget in the classic way (having the data entry user upload an image when they enter data on the form) is no longer working. When I select a file to upload from my computer, I see the following console error and the file is not uploaded:
![Annotation 2020-01-06 152813](https://user-images.githubusercontent.com/25179620/71846866-910e8980-3099-11ea-94d5-998d6e3d5e23.png)

**Comment by MartijnR** [comment]
* [x] check enketo/enketo-express - no problem
* [ ] check enketo-express-oc

**Comment by MartijnR** [comment]
fixed by 931d01f9ad246334fa0f1d131f16548acc35a9d3

**Comment by pbowen-oc** [comment]
Passed testing.
