### ISSUE TITLE
annotation image becomes smaller when switching from fullscreen (edit drawing) on mobile to whole form

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#281]
Reproduce on Android/Chrome.

Probably same issue with other 2 drawing widgets.

**Comment by MartijnR** [comment]
* [ ] Also the keyboard shows up (focus on input?) when clicking colorpicker
* [ ]

**Comment by pbowen-oc** [comment]
Just a note that we observed this with both the annotation widget and the regular drawing widget. The size change seems to be less severe with the drawing widget than the annotation widget.

**Comment by MartijnR** [comment]
The resizing issue and double border can be reproduced on desktop Chrome in mobile mode.

**Comment by MartijnR** [comment]
* [ ] update enketo-express and enketo-express-oc before 11th

**Comment by pbowen-oc** [comment]
Passed testing on original case. Some other issues remain and will be logged later.
