### ISSUE TITLE
Headless print for Grid forms has different layout than the on-screen form or print from within form

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#285]
I see two issues with the layout/formatting of items in Grid forms using headless print (PDF API).

1. If an item is specified to be "w1" and is in a group that is "w5" but the item is the only one in its row, it is not expanding to fill the entire line (as it does on the screen and when printing from in the form). Instead, it is taking up only 1/5 of the row and the rest is blank.

2. Row height is inconsistent with the same row. If a select item with several vertical radio button choices and a decimal item are next to each in the same row. the shorter decimal item will have empty space underneath its cell rather than stretching to the same height as its taller neighbor.

This screenshot illustrates both issues:
![Annotation 2020-01-10 204102](https://user-images.githubusercontent.com/25179620/72196906-baa51900-33e9-11ea-8f9d-eb248836ee6b.png)

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1PG3HTWh0UjA-P5RityOZ766URpTiDPCGhy9P5C0AUhw/edit#gid=0

**Comment by MartijnR** [comment]
width issue:
* [ ] also check if row follows the cell-to-be-stretched
* [ ] check grid tutorial form
* [ ] refactor

**Comment by MartijnR** [comment]
http://localhost:8005/preview?form=https://xlsform.opendatakit.org/downloads/tv8hih0t/grid-print-issue.xml

**Comment by MartijnR** [comment]
* [ ] check pdf as well

**Comment by pbowen-oc** [comment]
This is working as expected almost everywhere. The on exception is that last row of the form, which seems to still have both the vertical and horizontal scaling issues:

![Annotation 2020-02-02 133619](https://user-images.githubusercontent.com/25179620/73613203-55e07700-45c1-11ea-86e0-6f9093add34c.png)
![Annotation 2020-02-02 133658](https://user-images.githubusercontent.com/25179620/73613204-55e07700-45c1-11ea-98e5-357f4b089ed0.png)

**Comment by MartijnR** [comment]
* [ ] check with form that has discrepancy notes at end

**Comment by pbowen-oc** [comment]
@MartijnR - If the last item in the PDF display is a History item, it renders as expected. This behavior is specifically occurring when the last items on the PDF are regular data entry items, not History items.

**Comment by MartijnR** [comment]
Can be reproduced with a group containing 2 questions, 1 multiline with w3 and 1 regular text with w1.

**Comment by MartijnR** [comment]
* [ ] update enketo-core in ee-oc

**Comment by pbowen-oc** [comment]
We're still seeing the last row issue in the PDF view:
[PDF last line test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4252780/PDF.last.line.test.xml.txt)

To reproduce this, we enter a value on the fist page and leave the second page blank:
![Annotation 2020-02-25 190607](https://user-images.githubusercontent.com/25179620/75299654-9c617400-5803-11ea-8bd2-e730f8de5201.png)

**Comment by MartijnR** [comment]
https://github.com/OpenClinica/enketo-express-oc/files/4252780/PDF.last.line.test.xml.txt

**Comment by MartijnR** [comment]
* [ ] try tweaking timeout

Does Chrome actually support multiline flexbox in print? If so we remove the hackery in the PDF api.

**Comment by MartijnR** [comment]
* [ ] propagate fix in enketo-core to enketo-express-oc (best done after merging 2.0.0)

**Comment by MartijnR** [comment]
* [ ] merged but still need to do final check to verify fix

**Comment by pbowen-oc** [comment]
Passed testing.
