### ISSUE TITLE
Select_one item showing multiple selections

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#286]
We're seeing single select radio button items that are not correctly changing between code choices when you click different items. 

Steps:
1. Select code 1
2. Select code 2

Expected:
Code 1 is deselected and code 2 is selected. The item submits back code 2's value.

Actual:
Code 1 remains selected and code 2 is also selected. The item submits back code 2's value.

![Annotation 2020-01-15 135810](https://user-images.githubusercontent.com/25179620/72469577-b1cb9300-37ad-11ea-917f-644d5d68bff8.png)

After this, the behavior is unpredictable. Clicking one of the radio buttons might deselect it and leave the field showing a different value than what was last submitted.

Here is the sample form:

[single select not working correctly xform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4067455/single.select.not.working.correctly.xform.xml.txt)

Note that this is not occurring in all cases. It may be related to the item being in a repeating group and/or the form style.

**Comment by MartijnR** [comment]
* [ ] strip all dn questions, and try in enketo-core

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=https://gist.githubusercontent.com/MartijnR/54293f7cc40269c6be7bffbcf944cbcf/raw/0fb986274f1ba3b56e6092c9c5d2ba8c1f7b3d2c/single.select.not.working.correctly.xml

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=https://raw.githubusercontent.com/enketo/enketo-core/master/test/forms/repeat-radio.xml

**Comment by pbowen-oc** [comment]
Looks good.
