### ISSUE TITLE
Extra blank pages shown when field-list not used

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#288]
When we have a form using pages theme and the items are not in a field-list group, there is one additional blank (no items) page at the end of the form for each item on the form. I think this is due to the comment items we add to the form to handle queries and history. Note that the query widget is working as expected for the items on the form.
![Annotation 2020-01-17 201240](https://user-images.githubusercontent.com/25179620/72655972-2a754f80-3966-11ea-9171-53276d4959f6.png)

[extra blank pages.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4079816/extra.blank.pages.xml.txt)

**Comment by MartijnR** [comment]
* [ ] also check out repeat handler in fork, as this one is no longer correct (though not related to this issue, just to page flipping when a repeat is created.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::zNhwBoYs?ecid=1

**Comment by pbowen-oc** [comment]
Working with yesterday's build.
