### ISSUE TITLE
Repeat Pages navigation issues

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#290]
I used the following XForm:
[repeat pages xform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4088855/repeat.pages.xform.xml.txt)

Issue 1 (new issue related to recent updates):
When I added 2 additional repeats to a new form and then deleted the second one, it caused an error and I was no longer able to change pages to last repeat (instead I saw blank pages):
![Annotation 2020-01-20 204941](https://user-images.githubusercontent.com/25179620/72769177-d073c480-3bc7-11ea-8c84-1fc456b77eba.png)

Issue 2 (existing issue present in our Production build):
When I reloaded this record later after having added and deleted repeats, the first page didn't indicate that there were other pages of repeats to view:
![Annotation 2020-01-20 205109](https://user-images.githubusercontent.com/25179620/72769260-116bd900-3bc8-11ea-99da-828062b18cfc.png)

If I used the Go to End button, it did take me to another page:
![Annotation 2020-01-20 205134](https://user-images.githubusercontent.com/25179620/72769302-35c7b580-3bc8-11ea-8770-e39d157c4411.png)

When I navigated Back, the first page now showed the expected Next button that was not present initially:
![Annotation 2020-01-20 205153](https://user-images.githubusercontent.com/25179620/72769343-5db71900-3bc8-11ea-9d70-ca72c4236ac1.png)

Here is the instance that was loaded for the that series of screenshots (copied out of the Network panel):
[repeat pages instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/4088865/repeat.pages.instance.txt)

**Comment by pbowen-oc** [comment]
Found during testing of #286

**Comment by MartijnR** [comment]
I haven't actually worked on this yet (but it might be resolved).

**Comment by MartijnR** [comment]
for first issue:
* [ ] fix in enketo-core
* [ ] update ee
* [ ] update ee-oc
* [ ] if fix included changes in modules that OC has customized (likely page.js or repeat.js), make sure to duplicate the changes!
* [ ] final test in ee-oc

**Comment by pbowen-oc** [comment]
Working correctly now for both issues.
