### ISSUE TITLE
Forms not opening on first page

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#291]
Our pages theme forms are opening directly to the second page when we open them as new records, as existing records, or as previews. Note that this does not refer to opening to a specific item. This began occurring after the most recent deployment with yesterday's updates.

This XForm is an example of one showing this issue:
[Form_XML_Vitals.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4093376/Form_XML_Vitals.xml.txt)

The following simpler form is also not opening correctly. It is opening to a blank page and navigation is only possible through the End and Beginning buttons.

[simple form opens to blank page.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4093500/simple.form.opens.to.blank.page.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=https://enketo-aggregate.appspot.com/formXml?formId=vitals

**Comment by MartijnR** [comment]
This is a different issue:

https://github.com/OpenClinica/enketo-express-oc/issues/291

**Comment by MartijnR** [comment]
EE:
http://localhost:8005/:YYpM

EE-oc:
http://localhost:8005/single/fs/i/::YYpM

**Comment by pbowen-oc** [comment]
Looks this is working now for both cases.
