### ISSUE TITLE
First occurrence of repeating group has non-functional items and is not running all logic

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#293]
The form below does not work properly for the first occurrence of the repeating group. I can enter the two integer values, but the calculation does not execute and the select_one item is does not allow anything to be selected.

[repeating group first entry items don't work.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4109867/repeating.group.first.entry.items.don.t.work.xml.txt)

![Annotation 2020-01-24 125506](https://user-images.githubusercontent.com/25179620/73091617-c6441580-3ea8-11ea-9522-6bbcac03903c.png)

**Comment by pbowen-oc** [comment]
@MartijnR - This is urgent.

**Comment by MartijnR** [comment]
Got it. Thanks. 

* [x] reproducible in enketo-core : no
* [ ] reproducible in enketo-express-oc:

**Comment by MartijnR** [comment]
@pbowen-oc I cannot reproduce like this:

1. open empty form /singe/fs/i/::something view
2. Blood pressure: yes
3. Systolic: 23
4 Diastolic: 23

I see:

<img width="1161" alt="Screen Shot 2020-01-24 at 2 04 22 PM" src="https://user-images.githubusercontent.com/627350/73103930-710d0180-3eb2-11ea-811a-71dbc5bf8e5c.png">

If you do experience the issue with the same actions, I think the deployed version may not the last one.

**Comment by pbowen-oc** [comment]
@MartijnR - We rechecked our deployments and I confirmed the server is reporting that we are running version: 1.83.5.oc-1. I confirmed I am still seeing the issue reported (using Chrome on Windows 10, but issue was first report on Mac).

The screenshot you included above is not showing the correct behavior since the Systolic Pressure item has a strict constraint that should be firing for the data you entered (see my screenshots below showing t working as expected for the second row).

Here is what I observed.
1. Open Form. No errors.
2. Select Yes for radio button - RG appears, but console shows error:
![Annotation 2020-01-24 214809](https://user-images.githubusercontent.com/25179620/73115495-830f9400-3ef4-11ea-9774-4b87fc775b7e.png)
3. Enter Systolic pressure - Value is entered and submitted, but console error appears:
![Annotation 2020-01-24 214835](https://user-images.githubusercontent.com/25179620/73115498-97539100-3ef4-11ea-8349-a5288eaf9d24.png)
4. Enter Diastolic pressure - Value is entered and submitted, but console error appears. Constraint message is shown on Diastolic item (as expected). Strict constraint message does not appear on Systolic item (NOT as expected). Ratio is calculated and submitted back to our database (confirmed in our audit log), but the value remains as 0 for the Ratio item on the form UI (NOT as expected).
![Annotation 2020-01-24 214908](https://user-images.githubusercontent.com/25179620/73115528-18ab2380-3ef5-11ea-8c7f-a100b9b5a808.png)
5. Date select item does not allow selection:
![Annotation 2020-01-24 215033](https://user-images.githubusercontent.com/25179620/73115535-2e204d80-3ef5-11ea-9c5e-af7e4d28ce2c.png)
6. Add second row. All values can be entered in the second row with no further console errors. The calculated value appears as expected and the selection item works as expected. The Systolic pressure item shows a Strict constraint error message as expected. The first row remains unchanged:
![Annotation 2020-01-24 215104](https://user-images.githubusercontent.com/25179620/73115552-822b3200-3ef5-11ea-9448-2ece4c3ffe3f.png)
7. Go back to first row, Update Diastolic item. No errors are displayed. The ratio is displayed, the selection item works, and the Strict constraint message is shown as expected.
![Annotation 2020-01-24 215232](https://user-images.githubusercontent.com/25179620/73115565-b9014800-3ef5-11ea-9d5a-f4d475e780b2.png)
8. Delete second row. The first row still allows edit without error:
![Annotation 2020-01-24 220735](https://user-images.githubusercontent.com/25179620/73115628-bb17d680-3ef6-11ea-820e-779a3d5b97f8.png)
9. Close the form. Autoqueries are added as expected. Reopen the form. No console errors are shown initially:
![Annotation 2020-01-24 220917](https://user-images.githubusercontent.com/25179620/73115638-db479580-3ef6-11ea-89aa-19a5ccb284a8.png)
10. Change Diastolic item value. Console error is shown. Ration is not updated in the UI:
![Annotation 2020-01-24 221001](https://user-images.githubusercontent.com/25179620/73115655-05995300-3ef7-11ea-859b-3ca718212e5d.png)

**Comment by MartijnR** [comment]
What URL are you loading? (not the one I provided in step ,  I think)

**Comment by MartijnR** [comment]
* [ ] fiddle with config.json to try to reproduce

**Comment by MartijnR** [comment]
Got it! I was using a config.json that OC was using during some server deployment issues in the past, and noticed it didn't set these (which I think you are using):

```json
    "repeat ordinals": true,
    "validate continuously": true,
    "validate page": false,
```

**Comment by MartijnR** [comment]
* [ ] try reproducing in enketo-core 
* [ ] fix
* [ ] move to ee
* [ ] move to ee-oc (make sure to update any customized modules!)

**Comment by pbowen-oc** [comment]
I don't know if it helps at this point, but I was loading this view: /single/fs/c/i/::something

**Comment by MartijnR** [comment]
@bowen-oc, I fixed the exception. I haven't gone through all the screenshot in your last post yet, as I don't have more time today and wanted to get this out.

* [ ] verify if all reported issues in last post by Paul, have been fixed

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. We'll deploy and start testing. Will you be able to follow up on it tomorrow?

**Comment by MartijnR** [comment]
I checked all except 9 and 10 as it seems easier for you to do.

**Comment by pbowen-oc** [comment]
It looks good on our end. Thanks for your help!
