### ISSUE TITLE
Form UI freezes after clicking print button

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#296]
We've been seeing unexpected behavior that is not fully reproducible. When the Print button is clicked on a form and the user clicks Prepare and proceeds to the browser print UI, once the user returns to the form after printing, the form is sometimes non-responsive. 

Steps:
1. Open this simple form - 
[form UI freezes after print.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4125222/form.UI.freezes.after.print.xml.txt)

2. Select a radio button for the first question
3. Click the Print button
4. Click Prepare in Enketo's print setup window
5. Print or Cancel from the browser's print window

Expected:
The user is returned to the form and can resume data entry, use the Close button, etc.

Actual:
The user is returned to the form and the form is non-responsive. The browser is still responsive and the page can be reloaded.

Note that this has only been observed in Chrome on Windows and seems to be occurring with simple forms like the one attached rather than multi-page Grid forms.

It has not been occurring every time but it has occurred for several users. It occurred for me several times in a row and then when I closed the form and opened another new copy of it, it didn't occur.

**Comment by MartijnR** [comment]
* [ ] try to reproduce in enketo-express-oc on Chrome on Windows
