### ISSUE TITLE
PDF API should not request non-printable files

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#298]
The PDF API should not request non-printable file attachments. This is currently causing some forms print much more slowly than necessary or timeout. 

I think only image media files and image uploads should be requested when creating a PDF (not audio, video, or misc files). ~~We should replace the image with a clear note that a file was present but not included. Perhaps something like, "File intentionally omitted."~~

If the filename is still displayed on the form, then we should be fine with just not displaying anything for the file itself.

**Comment by MartijnR** [comment]
Hmm. That's tricky. Options:

1. Serve a nearly empty, but valid audio/video file (on the OC side).
2. tbc

**Comment by MartijnR** [comment]
Perhaps EE can capture requests with a video/audio mime type and serve empty file? Not sure.

**Comment by MartijnR** [comment]
regular instance view with image, video and audio files in the record:

```bash
curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=widgets&instance=\
    <widgets><text_widgets><text>mart</text></text_widgets><media_widgets><image>test.jpg</image><audio></audio><video></video></media_widgets></widgets>\
    &instance_id=someUUID&return_url=https://enketo.org&\
    instance_attachments[test-image.jpg]=https://d33wubrfki0l68.cloudfront.net/2fed87e72cab7ed9e2d5ec916eb6e4c03e2ba2d0/da072/media/images/offline.png\
    instance_attachments[test-audio.mp3]=https://sample-videos.com/audio/mp3/crowd-cheering.mp3\
    instance_attachments[test-video.mp4]=https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4\
    " http://localhost:8005/api/v2/instance/view

```

**Comment by MartijnR** [comment]
* [ ] broke record caching somehow?

**Comment by pbowen-oc** [comment]
@MartijnR  - Does this also account for general files uploaded to an item of type file? For example, the user uploads a PDF or ZIP file to a file item (which Enketo will never try to render on the form anyway).

**Comment by MartijnR** [comment]
Ah, good question. No it doesn't. I think it would be safest to explicitly exclude those (pdf and zip) mime types, so some other types may fall through the net.

I also should mention that this feature relies on the mime type sent by the OC server when serving those files.

**Comment by MartijnR** [comment]
Actually, they won't load at all probably. 

* [ ] check if non-previewable files served as part of record to be edited, are retrieved from server at all (when offered via API).

**Comment by MartijnR** [comment]
```
https://sample-videos.com/pdf/Sample-pdf-5mb.pdf

curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=widgets&instance=\
    <widgets><text_widgets><text>mart</text></text_widgets><media_widgets><image>test-image.jpg</image><audio>test-audio.mp3</audio><video>test-video.mp4</video><file>test-pdf.pdf</file></media_widgets></widgets>\
    &instance_id=someUUID&return_url=https://enketo.org\
    &instance_attachments[test-image.jpg]=https://d33wubrfki0l68.cloudfront.net/2fed87e72cab7ed9e2d5ec916eb6e4c03e2ba2d0/da072/media/images/offline.png\
    &instance_attachments[test-audio.mp3]=https://sample-videos.com/audio/mp3/crowd-cheering.mp3\
    &instance_attachments[test-pdf.pdf]=https://sample-videos.com/pdf/Sample-pdf-5mb.pdf\
    &instance_attachments[test-video.mp4]=https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4" \
    http://localhost:8005/api/v2/instance/view
```

**Comment by MartijnR** [comment]
All good! It turns out that targeting preview-able media is all we need to do, so only video and audio. Non-preview-able media already doesn't get loaded.

**Comment by pbowen-oc** [comment]
Thanks!

**Comment by pbowen-oc** [comment]
Looks good!
