### ISSUE TITLE
setvalue upon xforms-value-changed

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#300]
Just a placeholder to facilitate tracking. Actual issue is here: https://github.com/enketo/enketo-core/issues/577

**Comment by MartijnR** [comment]
* [ ] may have to change the "valuechange" event in dn widget to `new events.XFormsValueChanged()`

**Comment by MartijnR** [comment]
*  [ ] make or contribute to xlsform proposal, so this feature can actually be used

**Comment by MartijnR** [comment]
https://forum.opendatakit.org/t/xlsform-proposal-to-calculate-a-value-when-another-value-changes/24978

**Comment by MartijnR** [comment]
* [ ] agree on xlsform spec
* [ ] wait for implementation in pyxform (or pro-actively implement)

**Comment by MartijnR** [comment]
tbc: no labels is currently not allowed by either Pyxform or ODK Validate 

https://docs.google.com/spreadsheets/d/1jPtfLjYKbk3VhnVfyvnO-8nS5CwqCFk4HyZN-TIJN4I/edit#gid=0

http://opendatakit.org/xlsform/

**Comment by MartijnR** [comment]
@pbowen-oc , I actually find that pyxform does not allow empty labels. Do you have a form that slips through the cracks on http://opendatakit.org/xlsform/?

**Comment by MartijnR** [comment]
* [ ] update enketo with latest spec (multiple setvalues under single `<input>`)

**Comment by MartijnR** [comment]
* [ ] publish in enketo-core 5.15.0 and propagate to enketo-express-oc (not urgent since the pyxform work is required to actually test this)

**Comment by MartijnR** [comment]
* [ ] update enketo-validate (setvalue-5.xml complains about no label for "e")

**Comment by pbowen-oc** [comment]
Closing since this is generally working and separate issues have been logged for specific issues.
