### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#301]

**Comment by MartijnR** [comment]
This might be related: https://github.com/enketo/enketo-core/issues/692

**Comment by MartijnR** [comment]
@pbowen-oc, I am ready to work on this. Just a reminder to send a performance-challenging form.

**Comment by pbowen-oc** [comment]
@MartijnR - I just sent two via email that use many repeats and large external code lists. Good luck!

**Comment by MartijnR** [comment]
enketo-core:

largeform1.xml
- remove users.xml
- remove dn/comment questions

enketo-express-oc:
- original form

**Comment by MartijnR** [comment]
45 repeats (with jr:count) still takes 11 seconds to load, but it was: ... seconds

**Comment by MartijnR** [comment]
TL/DR: still 10x improvement when loading 45 empty repeats, but when repeats have values, performance goes down (possibly due to other logic).

**Comment by MartijnR** [comment]
## Largeform2.xml




### enketo-express-oc:

(using an clinicaldata.xml file I had myself)
http://localhost:8005/single/fs/i/TO1o4ZMh?ecid=a

**Comment by MartijnR** [comment]
@pbowen-oc, @theywa, @wvandeventer, @gushil  from the current version `2.1.0.oc-1` onwards, Node.js version 12 is required (and any Enketo version before only works with Node.js 8). See https://blog.enketo.org/Enketo-Express-mar-2020-update/#a-nodejs-change-in-version-210 for guidance, if needed.

**Comment by MartijnR** [comment]
There is a serious regression with autocomplete, where the value becomes 'undefined' of all options

**Comment by MartijnR** [comment]
* [ ] Work on form sent by email "Slow form for #301" on 4/29/2020.

**Comment by MartijnR** [comment]
### Participant Dosing

**Comment by MartijnR** [comment]
### Clinical Laboratory Values

**Comment by MartijnR** [comment]
If we end up passing a contextNode to model.evaluate, it may be VERY worthwhile to see where in the code we can pass an already retrieved contextNode instead of a path+index. https://github.com/enketo/enketo-validate/issues/69

**Comment by MartijnR** [comment]
For further in the future, this may become the lowest-hanging fruit: https://github.com/medic/openrosa-xpath-evaluator/issues/59

**Comment by MartijnR** [comment]
New evaluator todo:

* [ ] fix issue with now()
* [ ] fix issue with `../my_age+100` without spaces around +
* [ ] possibly, implement lazy and/or evaluation
* [ ] possibly, adjust how custom functions are added

The ParticipantDosing form has been tested with Alex' latest branch and is not even faster (0.35 seconds), so that looks very promising (definitely, not across the board that much faster though).

**Comment by MartijnR** [comment]
Current speed: 0.29 seconds. More performance optimizations to be added, so I wanted to record this

**Comment by MartijnR** [comment]
* [ ] send Alex massive XML doc with slow XPath expressions

**Comment by MartijnR** [comment]
new measurements (7th of August):

### LargeForm1.xml (with 45 repeats added via `jr:count="45"`)
http://localhost:8005/single/fs/i/::mzpHKUGx?ecid=a
old: 25,527/25,237/24,677 ms
new:

### LargeForm2.xml
http://localhost:8005/single/fs/i/TO1o4ZMh?ecid=a
old: 6,800/7,188/6,560 ms
new:

**Comment by MartijnR** [comment]
* [ ] fix for #423 https://github.com/enketo/enketo-core/commit/8f8f23be05be527ba707c106081e17e445c66842 seems to have a fairly significant performance impact. Refactor.

**Comment by pbowen-oc** [comment]
Looks good in testing.
