### ISSUE TITLE
Cascading List Select items trigger RFC with no change

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#302]
[cascading list form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4132131/cascading.list.form.xml.txt)

1. Open this form as an existing record with a non-null value entered for each of three select items
2. View the Query Widget for the 2nd or 3rd items

Expected:
There is no change entry from opening the form since the value was not changed since the record was loaded.

Actual:
The Query Widget shows change entries from null to the existing value for these two items on form load.

If the form is opened as a Complete form (i.e., RFC mode - /edit/fs/rfc/c/i/::), this is treated as a data change that required RFC to be entered for each of these items.
![Annotation 2020-01-29 225839](https://user-images.githubusercontent.com/25179620/73419283-8c31a400-42ec-11ea-928a-ccb11462aed6.png)

**Comment by pbowen-oc** [comment]
@MartijnR - This seems to be the same issue that was affecting all items with values when an existing record was loaded as noted in this comment:
https://github.com/OpenClinica/enketo-express-oc/issues/272#issuecomment-566849574

**Comment by MartijnR** [comment]
* [ ] check itemset.js `setVal` call in enketo-core

**Comment by MartijnR** [comment]
Fixed in `1.84.0.oc-2`!

P.S. see changelog for` 1.84.0` for need to now run a separate build command to create an IE11 build (1st step towards completely removing the IE11 code/build system in March). It is no longer done as part of `npm install`.

**Comment by pbowen-oc** [comment]
Seems to be working as expected for us.
