### ISSUE TITLE
Hide URL input from print view

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#303]
to done in enketo-core

**Comment by pbowen-oc** [comment]
Current behavior:
![Annotation 2020-01-31 153358](https://user-images.githubusercontent.com/25179620/73581580-a63bc580-4457-11ea-820f-0e15ddbb6d22.png)

**Comment by theywa** [comment]
I create a PR to fix the issue preview :
![Screenshot from 2020-02-04 21-33-01](https://user-images.githubusercontent.com/13865076/73749861-21beaf00-4797-11ea-9289-d30b6cb4e5d0.png)

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/commit/7719744917b9488c2c4cf00838b410ab9c083f05

(I will move to enketo-express-oc later today when updating enketo-core)

**Comment by pbowen-oc** [comment]
Looks good!
