### ISSUE TITLE
Read-only partial dates are displayed as full dates

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#304]
When a form is opened in edit mode, data values for date fields with appearance year or month-year are displayed as just the year or month and year as expected (for example 2019 or 2020-02).  However, when the same form is opened in View mode and the date values are read-only, they are displayed as full dates (for example, 2019-01-01 or 2020-02-01). I'd expect the date fields to respect their appearance even when displayed as read-only.
[Edit vs Readonly mode.docx](https://github.com/OpenClinica/enketo-express-oc/files/4173792/Edit.vs.Readonly.mode.docx)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=widgets.xml (with edited form making those datefields readonly)

**Comment by MartijnR** [comment]
* [ ] update enketo-core in enketo-express-oc

**Comment by pbowen-oc** [comment]
@MartijnR - We're seeing an issue that I think is related to this.
[date calculation not displayed or saved.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4252659/date.calculation.not.displayed.or.saved.xml.txt)


If I enter a date value in this form, the corresponding calculated date item does not get populated.

If I reopen this form with a value already in the first date field, it immediately calculates the second field, displays the value, and submits it back to us. If I changed the first date field value, the calculated value resets to null.

**Comment by MartijnR** [comment]
* enketo-core: http://localhost:8005/?xform=date.calculation.not.displayed.or.saved.xml

**Comment by MartijnR** [comment]
* [x] fix in enketo-core
* [ ] updated enketo-core in enketo-express
* [ ] update enketo-express-oc

**Comment by MartijnR** [comment]
in commit tagged with `1.85.1.oc-1`

**Comment by pbowen-oc** [comment]
Looks good!
