### ISSUE TITLE
Query Widget text issue if parent item has columns-n appearance

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#307]
If a select item has columns-n appearance, the Query widget is not displaying the "Email?" checkbox as expected:

![screenshot-1 (2)](https://user-images.githubusercontent.com/25179620/75122003-8fa81900-5667-11ea-8282-469faa5a8188.png)
[Query Widget emaillabelstacked.txt](https://github.com/OpenClinica/enketo-express-oc/files/4242648/Query.Widget.emaillabelstacked.txt)

**Comment by pbowen-oc** [comment]
We also observed that if an item has image-map appearance and the SVG image map file is not loaded, then the "Email?" checkbox is not displayed at all.

**Comment by MartijnR** [comment]
http://localhost:8005/preview/?form=https://github.com/OpenClinica/enketo-express-oc/files/4242648/Query.Widget.emaillabelstacked.txt

**Comment by pbowen-oc** [comment]
Looks good.
