### ISSUE TITLE
See Form Behavior issues email on 2/25

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#308]

**Comment by MartijnR** [comment]
second issue in that email is a priority

**Comment by MartijnR** [comment]
enketo-core:  http://localhost:8005/?xform=select.Yes.and.relevant.repeat.issues.xml

**Comment by MartijnR** [comment]
The issue is probably in enketo-express-oc:

**Comment by MartijnR** [comment]
@pbowen-oc  I have not been able to figure out the cause of this yet, so that will be next week (Monday or Tuesday I expect).

**Comment by MartijnR** [comment]
to investigate:

- repeat count is inside group with relevant condition
- when group becomes irrelevant
- calculations inside group are updated, and this is where the repeat count is reset

**Comment by MartijnR** [comment]
* [ ] figure out why first repeat is not deleted (and see if that offers a solution)

**Comment by MartijnR** [comment]
IE11/Edge issue in email (first issue): cannot reproduce. IE11 is slow as expected. Tested on old Edge (44.17763.831.0), not the new one based on Chromium.

**Comment by pbowen-oc** [comment]
I observed this in Edge 44.18362.449.0. I'm not sure what version(s) our users saw it in.

**Comment by MartijnR** [comment]
One thing to consider would be to never clear calculations (that don't have a form control) based on them becoming non-relevant. This may actually be correct thing to do according to the XForms spec (not quite sure). Would be difficult to predict the implications of users.

**Comment by MartijnR** [comment]
* [ ] Martijn to discuss with peers about clearing calculated values that don't have form control
* [ ]

**Comment by MartijnR** [comment]
Never mind @pbowen-oc, those calculations without form controls should be "relevant pruned" upon submission according to the XForms spec. 

Unfortunately, this is where we run into an issue with not having a final submission step in this fork.

We can solve this on the pyxform side only for the first and third repeat count case. Not for the second case because a [valid concern] arose during discussions for the second case (where repeat_count is a calculation).

Will have to think about another approach that covers all cases.

**Comment by MartijnR** [comment]
* [ ] remove clearIrrelevantImmediately setting from Enketo Core? It doesn't really make sense, and is non-XForms-spec-compliant. It only makes sense for OC, because of using fieldsubmissions.
* [ ] remove clearIrrelevantImmediately setting from Enketo Express
* [ ] implement logic in EE-oc's relevant module extension that perhaps never clears calculations that do not have a form control 

So @pbowen-oc, it would be good to think about never clearing calculations that do not have a form control after all.

**Comment by MartijnR** [comment]
Non-relevancy-clearing behavior, requires some extra attention during testing.

**Comment by pbowen-oc** [comment]
I thought this worked as expected in IE11 after the fix. However, the behavior in IE11/Edge Legacy is now that the first click of Yes on this form results in an effective double-click - the form processes for a bit but then leaves the value un-selected. The user can then select Yes again and it makes the relevant repeating group appear and behave as expected. It is only that first attempt at selecting Yes that fails.

The other issue with the repeating group not having the expected non-relevant behavior in any browser is working as expected.

We may need to come back to this later to address the IE11/Edge Legacy behavior on first click, but I think this is good enough for now.

**Comment by pbowen-oc** [comment]
The issue with IE11 and Edge Legacy is still there where the first click fails to make a selection but the second click works.

The scenario at issue is the following form configuration:
1. Parent group with nested repeating group
2. Parent group has relevant expression
3. Repeating group uses repeat_count parameter

Here is the issue in those browsers:
Issue 1 - IE/Edge only:
Steps:
1. Open the form.
2. Select the Yes radio button (which should make the repeating group relevant)

Expected:
The Yes button becomes selected and the latter parts of the form that are relevant based on it are displayed.

Actual:
The Yes button does not becomes selected and nothing becomes relevant. The form seems to pause while processing. It looks like the model is being updated to Yes at first and then being changed to null. This can be seen by the field submission generated by this click.

Note that if Yes is already selected in the instance when the form is opened, it seems to work fine until Yes is selected again. Also, selecting No works as expected.

**Comment by pbowen-oc** [comment]
@MartijnR - The original form for this has a different issue in Chrome.

Steps:
1. Open the form
2. Select Yes for the first question
3. After the 8 repeat rows appear, enter data into some of them
4. Close the form
5. Reopen the form

Expected:
The form opens with the data in the same state as when the form was closed.

Actual:
The form opens with only 1 repeat row displayed (despite repeat count set to 8 in the form definition). The calculate item in the repeating group is submitting data back and the calls are failing. (Note that the data was saved correctly on the first pass through the form.)

I'll re-send the form via email.

**Comment by MartijnR** [comment]
* [ ] try to reproduce in enketo-core

**Comment by pbowen-oc** [comment]
Looks good in testing.
