### ISSUE TITLE
PDF endpoint text item issues

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#312]
In a multiline text item, the cell is not expanding as expected to show all of the text. In other cases it is just cutting the text off with no scrollbar.
![Annotation 2020-03-16 214119](https://user-images.githubusercontent.com/25179620/76814280-ba9e0c80-67d0-11ea-939f-826cdeeb0060.png)

Also, it's showing a scrollbar when printed from with the form. 
![Annotation 2020-03-16 215927](https://user-images.githubusercontent.com/25179620/76814586-837c2b00-67d1-11ea-9653-76f332021808.png)

In a single line text item with very long text, the cell is not expanding enough and the text is complete overflowing into the next items.
![Annotation 2020-03-16 214229](https://user-images.githubusercontent.com/25179620/76814610-8e36c000-67d1-11ea-8962-7e3826a993dd.png)

In that form, the full data for that first cell was:
![Annotation 2020-03-16 214304](https://user-images.githubusercontent.com/25179620/76814615-92fb7400-67d1-11ea-88a5-e151cd8e1b4a.png)

PDF Endpoint:
[Participant_FixedPrefix912936_Casebook_2020-03-17-013945794+0000.pdf](https://github.com/OpenClinica/enketo-express-oc/files/4341103/Participant_FixedPrefix912936_Casebook_2020-03-17-013945794%2B0000.pdf)

Print to PDF from with the form:
[mulitline text with scrollbar.pdf](https://github.com/OpenClinica/enketo-express-oc/files/4341101/mulitline.text.with.scrollbar.pdf)

**Comment by MartijnR** [comment]
* [ ] check if multiline-not-expanding issue on printout is occurring with OC theme (or any other non-grid theme) as well
* [ ] check if single-line issue on printouts is occurring with OC theme (or any other non-grid theme)  as well

**Comment by pbowen-oc** [comment]
@MartijnR - The single line issue seems to have been resolved when we redeployed using both `grunt css` and `grunt build-ie11` in succession. Is that what we should be doing?

The multiline issue is still occurring for us.

**Comment by theywa** [comment]
@MartijnR - This issue happens when the user reopens form with a text area that already has a value that quite long(at least exceed default text area default height) and do print without updating the text area. Basically the _resize method is not working on the initial value, I'm not sure how to modify the _resize method to working on the initial value so the easiest way that I think is to apply the text-print widget to include text area.

**Comment by MartijnR** [comment]
Will respond in PR. Thx!

**Comment by MartijnR** [comment]
* [ ] to be updated in enketo-express and then merged

**Comment by MartijnR** [comment]
* [ ] merged, but still need to final check to verify

**Comment by theywa** [comment]
@MartijnR - sorry, it looks like the printing issue not fixed when the text-area not loaded yet. So is it okay to update the last row.forEach on _resizeRowElements method in print.js to something like this
````
   row.forEach( el => {
        const textarea = el.querySelector( 'textarea' );
        el.classList.add( 'print-height-adjusted' );
        el.style.height = `${maxHeight}px`;
        if (textarea) {
            if ( textarea.scrollHeight > textarea.clientHeight && textarea.scrollHeight > maxHeight ) {
                el.style.height = `${textarea.scrollHeight + Math.round( textarea.scrollHeight / 5 )}px`;
            }
        }
    } );
````
The text area scroll height on print preview is not the same as on the form so need to add around a fifth of the current text area scroll height value to make the make sure the label height can show all the text.

**Comment by MartijnR** [comment]
Apologies for the late response.

I think there may be a few issues with the proposed approach:

1. The script only runs for Grid theme and is really just meant to mimic the screen behavior of CSS multiline flexboxes in printouts (oddly enough browsers do not support that in print). I'm guessing the same issue exists for non-grid themes (formhub/kobo/oc - they're all pretty much the same).
2. It looks like a row with a textarea and number field would get different heights for each cell (the solution would be to add your logic to set maxHeight to a higher value instead (for all questions in a row).

I am not sure about the best approach. I guess we have these options:

a. go back to your (and @gushil's) first plan to use the new text-print widget also for textareas (but keep the logic you've added for the screen issue)
b. use a modified version of your approach above that also runs for other themes 
c. do this at widget level by handling some 'print' event (we do something like that in the DN widget ) - see 'printify.enketo' in gui.js in enketo-express-oc

What is your preference @theywa?

**Comment by MartijnR** [comment]
I'm inclined to go back to a. I don't much like doubling all text in the form though. Maybe we can  tweak this by using a printify and deprintify event, that that widget handles. If so that would mean:

1. changing the text-print widget in enketo-core to instantiate for textareas as well
2. changing the text-print widget to not populate the `<div class="print-input-text">` until a printify event is detected
3.changing the text-print widget to empty when a deprintify event is received
4. making sure that if those events are not fired (e.g. when the user gives the print command with Ctrl-P), the original `<textarea>` and `<input type="text">` are printed (with hidden overflowing text)
4. update enketo-core in enketo/enketo-express and add logic  to fire those events (and delay `window.print()`) when the print button is clicked. - I think OpenClinica is overriding that code and won't use it.
5. merge in enketo-express-oc and make changes to use this (we can use the new Custom event added to enketo-core instead of the 'printify.enketo' via jQuery.trigger()).

What do you think?

**Comment by theywa** [comment]
@MartijnR - sorry for the late response. I also think it's much easier(less code used) to use option a. 
In progress to following the suggestion.

**Comment by theywa** [comment]
@MartijnR - I'm not sure about the point 5 and 6 so it's not included in current PR

**Comment by MartijnR** [comment]
Thanks. I can do point 5 and 6. I actually (urgently due to a COVID-19 project need) fixed 3 Grid print issues that were regressions because of the text-print widget yesterday: https://github.com/enketo/enketo-core/issues/705. Hopefully those don't bring back some old issues in this thread.

**Comment by MartijnR** [comment]
* [ ] fix regression with overflowing text (flowing over question below)
* [ ] change event name
* [ ] trigger events in EE
* [ ] update PR in EE-oc

**Comment by pbowen-oc** [comment]
@MartijnR - It looks like past work has caused a regression here for the PDF call:
![Annotation 2020-07-15 184224](https://user-images.githubusercontent.com/25179620/87607462-6433d280-c6cb-11ea-954f-815acb7bd744.png)

The long text is not expanding as expected. 

Also, the image map item above it doesn't have the expected height relative to the area allotted and is pushing out of its grid boundaries.

[PDF API layout issues.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4928353/PDF.API.layout.issues.xml.txt)

**Comment by MartijnR** [comment]
* [ ] image-map size in pdf, and perhaps also print view
* [ ] textarea resizing issue

**Comment by MartijnR** [comment]
in enketo-express:

```
curl --user enketorules: -d 'server_url=https://enketo-aggregate.appspot.com&form_id=vitals&ecid=a&instance=<demo-vitals-grid-v9 xmlns:OpenClinica="http://openclinica.com/odm" xmlns:enk="http://enketo.org/xforms" xmlns:jr="http://openrosa.org/javarosa" xmlns:oc="http://openclinica.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="vitals" version="9">  <page1><ins_note/><rndm>4</rndm><cohort>D</cohort><cohort_note/><temp_yn/><temp_group>  <temp/>  <temp_units/>  <temp_unit_des/>  <temp_entry/>  <temp_entry_hidden/>  <temp_comment oc:queryParent="temp"/>  <temp_units_comment oc:queryParent="temp_units"/>  <temp_entry_comment oc:queryParent="temp_entry"/>  <temp_entry_hidden_comment oc:queryParent="temp_entry_hidden"/></temp_group><wh_y/><wh_units/><weight/><weight_unit_des>weight not entered</weight_unit_des><height/><height_unit_des>height not entered</height_unit_des><calc_note/><bmi/><bmi_hidden/><bmi_calc>0</bmi_calc><bmi_ro/><bmi_rad/><resp_rate/><pulse/><format1/><format2/><format3/><format4/><temp_yn_comment oc:queryParent="temp_yn"/><wh_y_comment oc:queryParent="wh_y"/><wh_units_comment oc:queryParent="wh_units"/><weight_comment oc:queryParent="weight"/><height_comment oc:queryParent="height"/><bmi_comment oc:queryParent="bmi"/><bmi_hidden_comment oc:queryParent="bmi_hidden"/><bmi_rad_comment oc:queryParent="bmi_rad"/><resp_rate_comment oc:queryParent="resp_rate"/><pulse_comment oc:queryParent="pulse"/><format1_comment oc:queryParent="format1"/><format2_comment oc:queryParent="format2"/><format3_comment oc:queryParent="format3"/><format4_comment oc:queryParent="format4"/>  </page1>  <page2><bp_yn/><bp_note/><bp_rg enk:last-used-ordinal="1" enk:ordinal="1">  <bp_rg_num_init/>  <bp_rg_num/>  <bp_row/>  <bp_pos/>  <bp_sys/>  <bp_sys_val/>  <bp_sys_count/>  <bp_dia/>  <bp_dia_val/>  <bp_dia_count/>  <bp_ratio/>  <bp_ratio_hidden/>  <bp_dt_prec/>  <bp_dt_ymd/>  <bp_dt_ym/>  <bp_dt_y/>  <date_note/>  <bp_row_comment oc:queryParent="bp_row"/>  <bp_pos_comment oc:queryParent="bp_pos"/>  <bp_sys_comment oc:queryParent="bp_sys"/>  <bp_dia_comment oc:queryParent="bp_dia"/>  <bp_ratio_comment oc:queryParent="bp_ratio"/>  <bp_ratio_hidden_comment oc:queryParent="bp_ratio_hidden"/>  <bp_dt_prec_comment oc:queryParent="bp_dt_prec"/>  <bp_dt_ymd_comment oc:queryParent="bp_dt_ymd"/>  <bp_dt_ym_comment oc:queryParent="bp_dt_ym"/>  <bp_dt_y_comment oc:queryParent="bp_dt_y"/></bp_rg><bp_sys_mean/><bp_dia_mean/><bp_number/><bp_ratio_lookup/><likert_group>  <likert_note/>  <systolic_agreement/>  <diastolic_agreement/>  <systolic_agreement_comment oc:queryParent="systolic_agreement"/>  <diastolic_agreement_comment oc:queryParent="diastolic_agreement"/></likert_group><newselectitem/><newdecimal/><pain_level/><vas_question/><media_yn/><pic/><sound/><vid/><afile/><pic_ann/><pic_draw/><pic_sig/><ecg_picture/><cascade1/><cascade2/><cascade3/><us_map>MT</us_map><image_map_note/><add_notes> Lots of additional notes. Lots of additional notes. Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.  end</add_notes><bp_yn_comment oc:queryParent="bp_yn"/><bp_sys_mean_comment oc:queryParent="bp_sys_mean"/><bp_dia_mean_comment oc:queryParent="bp_dia_mean"/><bp_number_comment oc:queryParent="bp_number"/><bp_ratio_lookup_comment oc:queryParent="bp_ratio_lookup"/><newselectitem_comment oc:queryParent="newselectitem"/><newdecimal_comment oc:queryParent="newdecimal"/><pain_level_comment oc:queryParent="pain_level"/><vas_question_comment oc:queryParent="vas_question"/><media_yn_comment oc:queryParent="media_yn"/><pic_comment oc:queryParent="pic"/><sound_comment oc:queryParent="sound"/><vid_comment oc:queryParent="vid"/><afile_comment oc:queryParent="afile"/><pic_ann_comment oc:queryParent="pic_ann"/><pic_draw_comment oc:queryParent="pic_draw"/><pic_sig_comment oc:queryParent="pic_sig"/><ecg_picture_comment oc:queryParent="ecg_picture"/><cascade1_comment oc:queryParent="cascade1"/><cascade2_comment oc:queryParent="cascade2"/><cascade3_comment oc:queryParent="cascade3"/><us_map_comment oc:queryParent="us_map"/><add_notes_comment oc:queryParent="add_notes"/>  </page2>  <meta><instanceID>uuid:7f1e3c36-b617-42bc-a03d-2c202314f24f</instanceID><instanceID_comment oc:queryParent="instanceID"/>  </meta></demo-vitals-grid-v9>&instance_id=a' http://localhost:8005/api/v2/instance/view

```

then go to: http://localhost:8005/view/acefc9353e1386051bec92da9669bda3?instance_id=a&print=true

**Comment by MartijnR** [comment]
in enketo-express for the image-map issue:

```bash
curl --user enketorules: -d 'server_url=https://api.ona.io/enketo&form_id=widgets&instance_id=a&instance=<widgets xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" xmlns:orx="http://openrosa.org/xforms" id="widgets" version="201912030016">  <formhub><uuid>01a710c316b44364986eb020e7fc7457</uuid>  </formhub>  <intro/>  <text_widgets><text/><phone/><long_text>  Lots of additional notes. Lots of additional notes. Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.   Lots of additional notes.  end</long_text></text_widgets> <meta><instanceID>uuid:36f6b413-2026-4854-a4d1-e3c9fbc254ba</instanceID></meta></widgets>' http://localhost:8005/api/v2/instance/view/pdf > ~/Downloads/two.pdf
```

set theme to Grid

**Comment by MartijnR** [comment]
enketo-core:

* http://localhost:8005/?xform=imagemap_form.xml (cannot reproduce in that form, but check after fix)

**Comment by MartijnR** [comment]
Create different issue for image-map

**Comment by pbowen-oc** [comment]
Looks good after testing.
