### ISSUE TITLE
Extra "Back" link appears on forms

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#316]
Multi-page forms have an extra back link (version 1.86.3):
![Annotation 2020-03-30 103929](https://user-images.githubusercontent.com/25179620/77925587-06da5980-7273-11ea-90c0-b0b086b1cb46.png)

**Comment by MartijnR** [comment]
* [ ] Check if extra or just not styled correctly.

**Comment by pbowen-oc** [comment]
Looks good
