### ISSUE TITLE
Button issues with latest build

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#319]
There are a couple button issues with the 2.0.1 build.

For non-pages forms, there is a large Next button at the bottom of the form:
![Annotation 2020-04-07 210212](https://user-images.githubusercontent.com/25179620/78733404-57a51e80-7913-11ea-8312-f24ac6b079dd.png)

For Preview forms, there is a Submit button instead of the expected Validate button:
![Annotation 2020-04-07 210302](https://user-images.githubusercontent.com/25179620/78733412-5d026900-7913-11ea-9b45-df5141d1aafc.png)

**Comment by MartijnR** [comment]
Sorry, that doesn't look pretty at all.

**Comment by MartijnR** [comment]
* Next button issue, I cannot reproduce. Might be a CSS build issue. Try `rm -R public/css && grunt css` to rebuild just css.

* [ ] fix Submit button in previews with `?form=....` parameter in enketo/enketo-express
* [ ] update enketo-express-oc
* [ ] test http://localhost:8005/preview/?form=https://gist.githubusercontent.com/MartijnR/54293f7cc40269c6be7bffbcf944cbcf/raw/0fb986274f1ba3b56e6092c9c5d2ba8c1f7b3d2c/single.select.not.working.correctly.xml

**Comment by MartijnR** [comment]
Only happens on single page form (grid theme?)

**Comment by pbowen-oc** [comment]
Looks good
