### ISSUE TITLE
Allow user to open next form when closing current form

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#320]
Based on form configuration, allow user to choose between going back to OC and going to the next form when Closing/Completing a new form.

Add ability to specify that there should be a toggle on the form to indicate where to redirect to when the form is Closed/Completed.
Support communication with the form's iframe to indicate how to proceed.

**Comment by pbowen-oc** [comment]
@MartijnR - Can you set out a design approach for this to be implemented in the next couple months by @gushil?

**Comment by MartijnR** [comment]
design (work in progress):

* [ ] Enketo's API adds supports for a `next_prompt` parameter and includes in the response URL something like `next_prompt=true` if the API request parameter is provided
* [ ] In Enketo Express add a tickbox for `go to next form` above close button (design tbd) if query parameter is present
* [ ] when sending message to parentWindow (`postEventAsMessageToParentWindow`) add `nextForm: true` to message
* [ ] on OC side in parentWindow look for `nextForm: true` and redirect to another form if present

**Comment by theywa** [comment]
Hi @MartijnR, 
I create a draft PR for all points above and ready for review.
Also, check Chinese characters and it looks normal 
![Chinese character](https://user-images.githubusercontent.com/13865076/98384697-acaf3b80-2080-11eb-8cd4-c3a446bdffdf.png)

Thanks

**Comment by MartijnR** [comment]
Great!

@pbowen-oc which webform views should this work in (or which should it not work in)?

Should it work in previews?
Should it work when editing an already started record, or only for new records?
Should it work in Participant views?

**Comment by theywa** [comment]
From the description then it should be only working for not participant new form(CMIIW) 
AC7: The checkbox will not be present when a form that has already been started is opened in edit, review only, or read-only mode.
AC8: The checkbox will not be present when a form that does not have this configuration is opened.
AC9: This checkbox will not be present when a form is opened in Participate.

**Comment by pbowen-oc** [comment]
@theywa @MartijnR - This should work in the standard new record edit mode. It should not work for editing existing records or in read-only, review-only modes, or Participant modes.

I think it would be good to show this in Preview mode as well to give the closest impression to how the form will really behave (although we won't process the checkbox status in Preview mode).

**Comment by theywa** [comment]
PR updated to include preview mode

**Comment by pbowen-oc** [comment]
Looks good in testing.
