### ISSUE TITLE
Add ability to update Item Hidden/Removed message when opening directly to an item

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#321]
When a form is opened directly to a specific item and that item is not visible on the form, we currently see one of the following messages:

``The item you are trying to access has been removed from this form. Please use the View Query Only icon instead of the View Query Within Record icon to see it.``

``The item you are trying to access is currently hidden. Please use the View Query Only icon instead of the View Query Within Record icon to see it.``

We are adding the ability to open directly to a specific item in other parts of the system and need to adjust this text based on the where we are calling the form from.

**Comment by MartijnR** [comment]
@pbowen-oc, is the alternative text fixed? Is it just removing the second sentence from each message?

**Comment by pbowen-oc** [comment]
@MartijnR - For our Queries use case, the only possibilities for this are items that are hidden or are not on the form (aka removed). That is why we have the text above.

For our SDV use case, there is a third possibility - calculate items. The current functionality (before any new implementation for this), puts calculate items in the the removed bucket. This is not appropriate since the item is still on the form, just not displayable. I'd like the text to be "The item you are trying to access is not visible on the form." for the SDV use case when the item being referenced is a calculate item on the form (and still keep the other cases for hidden/irrelevant items and items that are completely gone from the form.)

**Comment by MartijnR** [comment]
I just noticed there is also the go_to_error_url functionality. 

In the queries interface, will you continue to have 2 scenarios, i.e. 1) to provide this link  and 2) not to provide this link? If you could always provide a link in the queries interface, we could simplify things by having fewer scenarios.

**Comment by pbowen-oc** [comment]
@MartijnR - We have not yet started passing a link in using that method. My best recollection was that we'd want it to hide the actual link from the user and have something like "Click _here_ to open" the other view.

**Comment by MartijnR** [comment]
Right, the implementation is to show the sentence "Please visit __miniform__ to see it." where miniform is replaced with the link, when go_to_error_url is provided. So I'll just proceed needing to maintain those 2 scenarios in the queries interface then.

**Comment by MartijnR** [comment]
default:
queries:
queries+go_to_error_url:
sdv:

**Comment by MartijnR** [comment]
* [ ] bug in controller-webform in enketo/enketo-express go_to is not url encoded (nor decoded) - used by OC for view-only

**Comment by MartijnR** [comment]
Master contains the new feature, with the exception of the 'sdv' interface (which is the same as default for now).

OC API docs updated with `interface` parameter: https://github.com/OpenClinica/enketo-express-oc/blob/master/tutorials/oc-api.md

**Comment by MartijnR** [comment]
* [ ]  in enketo-core add another error, and detect this error in the OC-fork, to deal with it.

Weirdly, I don't see any error when going to a calculated field without a form control in Enketo Core.

**Comment by MartijnR** [comment]
@pbowen-oc, When going to a calculation without a form control, I see no error. This makes me think I may be misunderstanding your sdv requirement above, or that you'd like to go from no error to this new message (in the sdv interface).

**Comment by pbowen-oc** [comment]
@MartijnR - You are probably correct. I took a closer at the call we were making when I saw the message and we were calling to open to the calculate item's comment field (which doesn't exist). So I think that is why I saw the item removed message.

If we called to go directly to the calculate item (not a non-existent comment item), how hard would it be to have that show the error message I described?

**Comment by MartijnR** [comment]
I think I may have found a way that would be easy to implement, but it would rely on using an absolute goto path, so /path/to/node instead of //node. This makes it a bit of a hack. It would be a quick check that would run if Enketo Core returns no errors (to see if Let me check quickly.

To do it properly (in Enketo Core) would be to add this particular error. That would be a bit more work. I'm not quite sure how much yet.

**Comment by MartijnR** [comment]
* [ ] in OC fork (and perhaps enketo/enketo-express) rename GoToHidden to GoToIrrelevant
* [ ] detect GoToInvisible event

**Comment by MartijnR** [comment]
completed by https://github.com/OpenClinica/enketo-express-oc/commit/8e1e6756a833bdafd32ecaf72f383245c889227f

**Comment by pbowen-oc** [comment]
Passed testing.
