### ISSUE TITLE
Enketo is not respecting SVG image map viewBox attributes

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#330]
When we use an SVG image map in our forms, there is no way to control the size of the image. SVG includes a viewBox attribute that is supposed to set the scale for the image. However, this setting is disregarded and SVG images are consistently shown in a larger size than desired (often getting cropped on the edge of the form).

The following images are the same except for the viewBox:

[circle_small.svg.txt](https://github.com/OpenClinica/enketo-express-oc/files/4625203/circle_small.svg.txt)
[circle_large.svg.txt](https://github.com/OpenClinica/enketo-express-oc/files/4625204/circle_large.svg.txt)

Viewing these directly in Chrome (after changing the extensions back .svg) shows the intended effect of the viewBox configuration. However, when these are used as an image map in a form, they look the same (and get clipped by the edge of the form).

Inspecting the form when I open it with one of these, I see that the viewBox setting is overridden with this:
![Annotation 2020-05-13 193334](https://user-images.githubusercontent.com/25179620/81876481-d0ba1600-9550-11ea-8277-06591d59561b.png)

If I manually change this attribute in Chrome's Developer Tools, I see it works as I expect.

The image map is being clipped in the same manner whether I am viewing the form on my laptop or on my iPhone, so the current behavior of overiding viewBox does not seem to be beneficial in any environment.

![Annotation 2020-05-13 194203](https://user-images.githubusercontent.com/25179620/81877021-09a6ba80-9552-11ea-9fd7-7bc30c86a99f.png)
![Image from iOS](https://user-images.githubusercontent.com/25179620/81877036-14f9e600-9552-11ea-946f-cf53f71116a9.png)

Example Form:
[imagemap_form.zip](https://github.com/OpenClinica/enketo-express-oc/files/4625386/imagemap_form.zip)

**Comment by pbowen-oc** [comment]
@MartijnR - In addition to the sizing issue noted here, I am also unable to get Enketo to recognize the central region defined by the circle (id="Layer_37"). I am assuming this is a separate bug, but I am not certain.

**Comment by pbowen-oc** [comment]
The one working example I have that does not get cut off is the US map SVG. That file only specifies width and height and the form appears to use those values to set the viewBox. However, I tried the same approach for the files I attached above and the from still consistently set the viewBox to the same value and cropped the image regardless of how I defined the SVG.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=imagemap_form.xml

**Comment by MartijnR** [comment]
* [ ] fix bounding box calc
* [ ] check into selecting middle circle

**Comment by pbowen-oc** [comment]
Sorry, forgot to create a separate issue for the circle selection. Do you want me to do that?

**Comment by MartijnR** [comment]
No problem, no need. I am implementing both solutions (putting id on g parent of circle, and putting id on circle). The difference in use is how the 'selected' state is shown - either border, or full circle).

**Comment by MartijnR** [comment]
* [ ] propagate to this repo via enketo-express

**Comment by pbowen-oc** [comment]
Passed testing
