### ISSUE TITLE
Trigger fieldsubmissions for static default values

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#331]
* [x] create test form with static defaults including for a repeat https://docs.google.com/spreadsheets/d/1FAdE69ZM7L-9YoTby7krk9CCkFlEdBRX4BE64t5pat8/edit#gid=0

**Comment by MartijnR** [comment]
This routine would not exclude:

* readonly fields with a static default
* fields that are non-relevant upon load with a static default

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/c4wK8Nm3?ecid=1

**Comment by MartijnR** [comment]
* [ ] since the added code is very slow for some forms, do not run it in edit mode (if data.instanceStr)

**Comment by pbowen-oc** [comment]
@MartijnR - If a static default (e.g., 1, "hello", etc.) is used within a repeating group, the default value is not getting submitted except for in the first repeat. Static defaults are also submitted  as expected outside of repeating groups.

For all static defaults, even those that are submitted, the History widget is not showing an entry for the initial default value during the form session. Calculated defaults are showing an entry for the default value as expected.

"Hello" is a static default and does not appear in the History widget within the initial form session. "Hello World" for the other item is a calculated default (concatenation of the other values) is is showing an entry for the default value as expected.

![Screenshot 2020-11-25 130925](https://user-images.githubusercontent.com/25179620/100266530-f8d2fa80-2f1f-11eb-8414-4ac3ad225055.png)

**Comment by pbowen-oc** [comment]
@MartijnR - I see I already logged issue #396 for the non-submission in repeating groups. Do you want a separate issue for the History widget?

**Comment by pbowen-oc** [comment]
I'll open a separate issue for this:
"For all static defaults, even those that are submitted, the History widget is not showing an entry for the initial default value during the form session. Calculated defaults are showing an entry for the default value as expected."

And we can address it later.

**Comment by pbowen-oc** [comment]
Looks good in testing.
