### ISSUE TITLE
fieldsubmission of completed record using POST instead of PUT

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#332]
possibly related to new pyxform

**Comment by MartijnR** [comment]
From the code it looks this would happen if the ../meta/deprecatedID is not generated, which in its turn is dependent on whether the record-to-edited contains an instanceID.

**Comment by MartijnR** [comment]
It doesn't look like the oc:complete="true" attribute makes any difference in deciding when to use POST or PUT.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=new&ecid=1&instance=\
<data xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"   xmlns:enk=\"http://enketo.org/xforms\" ><med_rg enk:last-used-ordinal=\"1\"  enk:ordinal=\"1\" ><dosedate>2020-05-04</dosedate><dose1></dose1><dose2></dose2><dose1_mins>NaN</dose1_mins><dose2_mins>NaN</dose2_mins><dose2_mins_adj>NaN</dose2_mins_adj><dose2_mins_comment></dose2_mins_comment><dose2_mins_adj_comment></dose2_mins_adj_comment><dose1_mins_comment></dose1_mins_comment><dosedate_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"2020-05-04\\\"\",\"user\":\"pbowenadm\",\"date_time\":\"2020-05-18 19:15:59.215 Z\"}]}</dosedate_comment><dose1_comment></dose1_comment><dose2_comment></dose2_comment></med_rg></data>\
&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit/rfc
```

**Comment by MartijnR** [comment]
confirmed that PUT is chosen if the record contains an instanceID (which it doesn't in the above case).

So, this makes me suspicious that Enketo is not sending an instanceID during the first session when a "new" record is created, when OC is expecting to get this. Will look into recent code changes wrt instanceID.

**Comment by MartijnR** [comment]
@pbowen-oc, for fieldsubmissions that take place if a value changes, I don't see any recent pyxform or Enketo change that would explain a switch from PUT to POST.

PUT or POST is determined by the meta/instanceID node in the record that is passed to Enketo for editing. As far as I can see, Enketo never submits that XML node, so I'm just wondering if OC used to add it to the record manually.

Nevertheless, I could just change the logic and use record completeness instead to determine whether to use PUT or POST. That's trivial to do (according to the API documentation, Enketo should have always done that: https://app.swaggerhub.com/apis/martijnr/openclinica-fieldsubmission/1.0.0#/fieldsubmission/put_fieldsubmission_complete)

**Comment by MartijnR** [comment]
Actually, when using PUT, enketo adds a deprecatedID field, so the logic is really meant to rely on instanceID to be present in the XML record. 

currently:
```
if deprecatedID
   use PUT method and add deprecatedId parameter to submission
```

should be:
```
if deprecatedID and recordMarkedAsComplete
   use PUT method and add deprecatedId parameter to submission
```

**Comment by pbowen-oc** [comment]
It looks like this was on our end.
