### ISSUE TITLE
Error opening forms in view mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#333]
We are getting an error opening any form in view mode. This is for new forms and existing records, but edit mode seems to be fine.

An error like this come sup when the form is attempting to load (but it fails):
![Annotation 2020-05-20 184900](https://user-images.githubusercontent.com/25179620/82505617-2a2fc100-9acc-11ea-8128-3cb0c9bc1fe4.png)

The console shows messages like these:
![Annotation 2020-05-20 185326](https://user-images.githubusercontent.com/25179620/82505832-47fd2600-9acc-11ea-9a56-2ecac0948884.png)

![Annotation 2020-05-20 185821](https://user-images.githubusercontent.com/25179620/82505841-4af81680-9acc-11ea-9bd0-5ab1a5bafe8e.png)

We updated from v2.2.1 (I think) to the latest master today and that seems to be when we started observing this.

**Comment by MartijnR** [comment]
Oops. Sorry. I expect this will be a quick fix.

* [ ] try to reproduce in enketo/enketo-express

**Comment by MartijnR** [comment]
* [ ] test addSignedStatus functionality

**Comment by pbowen-oc** [comment]
We are still seeing an error for any form opened in note-only mode as an existing record:
![Annotation 2020-05-21 204711](https://user-images.githubusercontent.com/25179620/82619851-0a200080-9ba5-11ea-9b6d-b1382e673ab9.png)

URLs observed in: /edit/fs/dn/i/ and /edit/fs/dn/c/i/

**Comment by MartijnR** [comment]
```
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=cascading&ecid=1&instance=\
<cascading xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\">\
<page1><cascade1>1</cascade1><cascade2>1</cascade2><cascade3>1</cascade3></page1>\
<meta><instanceID>uuid:1234</instanceID><oc:signature>A Signature</oc:signature></meta></cascading>\
&instance_id=a" http://localhost:8005/oc/api/v1/instance/note/c
```

**Comment by MartijnR** [comment]
Got it. I didn't test that view.

**Comment by pbowen-oc** [comment]
Passed testing.
