### ISSUE TITLE
Enketo Validate issues

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#334]
* [x] https://github.com/enketo/enketo-validate/issues/66
* [x] https://github.com/enketo/enketo-validate/issues/67
* [ ] https://github.com/enketo/enketo-validate/issues/68
* [x] https://github.com/enketo/enketo-validate/issues/69
* [x] bug: https://github.com/enketo/enketo-validate/issues/73
* [x] https://github.com/enketo/enketo-validate/issues/70
* [x] release new version and launch on validate.enketo.org

**Comment by MartijnR** [comment]
@pbowen-oc , the non-performance/timeout improvements can be tested on https://validate.enketo.org/oc/ now.

**Comment by MartijnR** [comment]
It's live with the performance improvement now. I haven't been able to figure out how to increase the timeout yet. Note, this server is very slow (inexpensive) too.

**Comment by pbowen-oc** [comment]
Looks good in testing
