### ISSUE TITLE
Unexpected field submissions when form is not loaded fully

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#335]
I have a form that is passing the clinicaldata instance over with an invalid character (due to an emoji).

[clinicaldata with emoji.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4685309/clinicaldata.with.emoji.xml.txt)

The form loads with this error:
![Annotation 2020-05-26 182641](https://user-images.githubusercontent.com/25179620/82956564-0b737380-9f7f-11ea-8d93-9f702966e05b.png)

Note that the primary instance is loaded as expected:
[instance with emoji.txt](https://github.com/OpenClinica/enketo-express-oc/files/4685314/instance.with.emoji.txt)

Due to the form load error, the form is missing the Close and Complete buttons (as expected). However, the form is still submitting data back even in this state. My expectation is that due to the form not loading fully, field submissions will be disabled.

Here is the test form I used for this:
[testform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4685331/testform.xml.txt)

**Comment by MartijnR** [comment]
XML invalid so from Enketo's side:

* [ ] make sure no fieldsubmissions occur when an error like this occurs

**Comment by pbowen-oc** [comment]
@MartijnR - I am now seeing unexpected behavior when I open a new form that has calculations that should trigger submission right away.
![Annotation 2020-06-01 151357](https://user-images.githubusercontent.com/25179620/83464606-5db10a80-a43f-11ea-80d8-e9cf1e2607a1.png)

In this case, the initial submission calls for the calculations are not made until the form is closed or I manually enter another value. The submission are all made successfully at that time. At that point, the message changes to the normal text, but in the lighter color.
![Annotation 2020-06-01 193906](https://user-images.githubusercontent.com/25179620/83464768-d1531780-a43f-11ea-8df1-c7fb42fb9aed.png)


Note that when I load a form with an invalid external instance as in the original report, it is correctly blocking submission as expected and the text shown in my screenshot appears when I enter data.

**Comment by MartijnR** [comment]
The issue is with message only.

**Comment by MartijnR** [comment]
can be reproduced with http://localhost:8005/single/fs/i/YYpM

**Comment by MartijnR** [comment]
@pbowen-oc, though I now fixed this (submissions will take place right away), I wanted to let you know we could also revert this fix to keep the submission behavior as it was, but change the initial feedback message (to nothing) instead. This would also be very easy to do.

The advantage of not submitting until the first user interaction might be that no record is created if a user simply opens a form without doing anything else.

**Comment by pbowen-oc** [comment]
Thanks, @MartijnR! 

We had thought about not having submissions in case like that before. With the current behavior (before this fix is deployed), I am finding that the calculation submissions are being triggered when I click the Close button even if I had not interacted with the form in any other way. Would it be possible to change that behavior so that the calculation submissions don't occur at all?

**Comment by pbowen-oc** [comment]
Looks good after testing when a form loading error appears. However, I logged #376 for some cases where missing external instances do not generate loading errors.
