### ISSUE TITLE
Firefox allows non-numeric entry in repeating numeric items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#338]
This issue seems to be specific to Firefox. It was reported in our production build and is still an issue in the most recent build. I confirmed it on Firefox version 76 in my test form.

When an integer item (and also decimal, I think) is in a repeating group, the first occurrence correctly restricts the input of the item as expected. However, when a second repeat is added, the integer item now allows any characters to be directly input (decimal points, letters, spaces, etc) and no errors are reported in the UI. It seems to work as expected for any repeat occurrences that are present when the form is opened but not newly added occurrences.

![Annotation 2020-05-31 224411](https://user-images.githubusercontent.com/25179620/83372064-3ea86f00-a392-11ea-8646-f78a7cf526ad.png)

**Comment by MartijnR** [comment]
Also occurs in Chrome.

http://localhost:8005/?xform=repeat-default.xml

**Comment by pbowen-oc** [comment]
Passed testing.
