### ISSUE TITLE
Previews not loading XPath extensions

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#339]
see e.g. http://localhost:8005/preview/YYpM

("comment-status does not exist" error)

**Comment by MartijnR** [comment]
* [ ] add a test to prevent this from happening again (during a merge)

It might also make sense to make a sense to make an OC-only preview view, that would prevent such merge errors better.

**Comment by pbowen-oc** [comment]
Looks good.
