### ISSUE TITLE
RFC requested when form is open due to calculated item with false change

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#340]
This is related to or a partial regression of #272. It may have been caused by #302. The issues below are currently in our production release of 1.85.x. I believe this was working as expected in our previous release of 1.83.x (at least for #1 below since that was part of the comment thread in #272).

1. When a form with a calculation is re-opened, there is an extra entry in the field history for the item changing from null to current value. There is no submission associated with this and it is not generally triggering a RFC request.

For example, see my demo form:
![Annotation 2020-06-04 004300](https://user-images.githubusercontent.com/25179620/83716257-5d5e6e00-a5fd-11ea-85e3-7131c677407c.png)

2. In some cases, the calculated item is triggering a RFC request along with the extraneous value change in the field history:
![Annotation 2020-06-04 002330](https://user-images.githubusercontent.com/25179620/83716392-c34af580-a5fd-11ea-88e9-2d18fdcfbf50.png)

Xform:
[unexpected RFC on calculated item.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4727610/unexpected.RFC.on.calculated.item.xml.txt)

In that screenshot, the form was opened with the instance in that state and RFC were requested immediately.

Calculated items should never prompt the user for a RFC (since they did not change that item directly).

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=RFC&ecid=1&instance=\
<Labs_v3c-mini xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"   xmlns:enk=\"http://enketo.org/xforms\" ></Labs_v3c-mini>\
&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit/rfc
```

**Comment by MartijnR** [comment]
The actual issue for 2 may be that the Test Name questions are not readonly (they are editable).

**Comment by MartijnR** [comment]
issue 1 can also be reproduced with the above curl command (check Test Name question)

**Comment by MartijnR** [comment]
* [ ] create a 1-question form to reproduce the first issue
* [ ] figure out why inputupdate is fired

**Comment by pbowen-oc** [comment]
@MartijnR - The Test Name items do not show up as editable to me. They are just populated by the row position. Here is the XLS that the XForm came from:

[Labs v3c-mini.zip](https://github.com/OpenClinica/enketo-express-oc/files/4733676/Labs.v3c-mini.zip)

**Comment by MartijnR** [comment]
Yes, the readonly issues (and related RFC) are fixed now. Was totally broken for minimal-selects. Working on first issue now.

**Comment by pbowen-oc** [comment]
Looks good after testing.
