### ISSUE TITLE
Some forms are not displaying image maps

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#343]
In the attached small form, the US map SVG is displayed as expected.

In the attached larger form the US map SVG (which is near the end of the form) is not displayed. It is interactive as I can make selections from the apparently empty cell it is in, but the entire image map itself is invisible.

[us map small form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4756216/us.map.small.form.xml.txt)
![Annotation 2020-06-10 003804](https://user-images.githubusercontent.com/25179620/84227937-b1f96180-aab3-11ea-8b86-3b6007ecb126.png)

[us map full form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4756217/us.map.full.form.xml.txt)
![Annotation 2020-06-10 004032](https://user-images.githubusercontent.com/25179620/84227947-b58ce880-aab3-11ea-9d01-b8eebfcb1c1d.png)

Image map for both forms:
[US_MAP.svg.txt](https://github.com/OpenClinica/enketo-express-oc/files/4756227/US_MAP.svg.txt)

**Comment by pbowen-oc** [comment]
I think this first occurred when #330 was updated. I didn't realize it at the time since my test forms for that issue were small like the form that works correctly in this ticket.

**Comment by MartijnR** [comment]
* Click No at "Was temperature measured"
* Go to second page and see question "Which state..."

Also occurs with non-grid themes

**Comment by MartijnR** [comment]
This is fixed, but merging is blocked by #346

**Comment by pbowen-oc** [comment]
Passed testing.
