### ISSUE TITLE
Babel configuration

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#346]
OC is using a babel tasks for an IE11 build.

enketo/enketo-express now has a babel build again for all non-IE11 browsers due to an issue in Edge Legacy.

This means that we have to fix something in OC after the next merge.

Either,:

a. if OC is really still able to load any form in Edge Legacy (which would really surprise me), we simply keep the babel task as it is, only for IE11

b. create a config with two different babel config and fix the merge conflicts with babel packages

**Comment by pbowen-oc** [comment]
@MartijnR - I no longer have Edge Legacy on this computer and therefore can't test this directly myself, but my colleague told me that the current build does not work in Edge for him. It appears to be trying to load indefinitely.

**Comment by MartijnR** [comment]
Right, that makes sense. Will use option b.

**Comment by MartijnR** [comment]
done with 19ed071f322708e8a5f9e33ff82ec1fe1ccebd19
