### ISSUE TITLE
Select item not cleared after becoming irrelevant 

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#347]
Steps:
1. In the attached form, select a test
2. In the units item that appears, make a selection
3. De-select the test

Expected:
Since the units item is now irrelevant, and it is automatically emptied due to the choice filter, it should disappear.

Actual:
The units item remains displayed until the user de-selects the test item while the units item is already empty.

Note that I saw similar behavior with an item that did not use the choice filter. In that case, the steps would add step 4 which would be to de-select the units item.

Note that the same issue is present in 1.85.1.

![Annotation 2020-06-18 010157](https://user-images.githubusercontent.com/25179620/84981081-b3eda100-b101-11ea-80ec-e0a69d09e714.png)

[relevant repeat test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4796429/relevant.repeat.test.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/QnzD6yfd?ecid=1

**Comment by MartijnR** [comment]
* [ ] fix failing test

**Comment by pbowen-oc** [comment]
Looks good after testing.
