### ISSUE TITLE
question with setvalue/xforms-changed calc gets cleared when it becomes non-relevant

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#350]
Need to add logic to block that for form controls that users can edit.

**Comment by MartijnR** [comment]
Solution for OC fork only (set clearIrrelevantImmediately to true)

**Comment by MartijnR** [comment]
I think this may have magically fixed itself. I like it when that happens.

<img width="923" alt="Screen Shot 2020-08-04 at 3 05 07 PM" src="https://user-images.githubusercontent.com/627350/89344945-ecbae880-d663-11ea-8356-aca9aff95bf4.png">

**Comment by pbowen-oc** [comment]
Closing this since it was logged again as #404 and a fix applied for that.
