### ISSUE TITLE
File items and drawings failing to upload

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#354]
All file item types (file, image, audio, video) are failing to upload.

[file_item.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4849243/file_item.xml.txt)

The console shows this error:
![Annotation 2020-06-29 231011](https://user-images.githubusercontent.com/25179620/86079489-9e13a080-ba5e-11ea-874f-a97cfb74914d.png)

This doesn't seem related to the Pyxform updates.

**Comment by MartijnR** [comment]
Looks like drawing widget has similar issue

**Comment by pbowen-oc** [comment]
Looks good after testing.
