### ISSUE TITLE
Deprecated UUID submitted in every form call

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#362]
@MartijnR - I'm not sure if it is the same issue, but there is an unexpected submission when a form is opened in review-only mode (for example, /edit/fs/dn/c/i/).

[review-only submission on load.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4950347/review-only.submission.on.load.xml.txt)

Sample Form:
[review-only submission on load.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4950367/review-only.submission.on.load.xml.txt)

Sample Instance:
[review-only submission on load.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/4950372/review-only.submission.on.load.instance.txt)

Screenshot immediately upon load:
![Annotation 2020-07-20 184357](https://user-images.githubusercontent.com/25179620/87993874-a12c0a80-cab9-11ea-8616-a19f3dd08360.png)

It seems like this could be due to an extra Put call that is not present in our Prod branch that is submitting <deprecatedID>uuid:1234</deprecatedID>.

**Comment by MartijnR** [comment]
* [ ] never submit deprecatedID (probably started submitting this when we added logic for static default nodes)

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=oc-340&ecid=1&instance=\
<data xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"   xmlns:enk=\"http://enketo.org/xforms\" >\
    <a>aa</a>
    <b>aa</b>
    <meta>
        <instanceID>123</instanceID>
    </meta>
</data>\
&instance_id=123" http://localhost:8005/oc/api/v1/instance/note/c

```

**Comment by MartijnR** [comment]
This did not have to do with the recent static default value submission logic after all, I believe, Not sure what introduced it, unless the instanceID was not populated in the record-to-be-submitted until recently. 

In any case, it should now never be submitted.

**Comment by pbowen-oc** [comment]
Looks good after testing.
