### ISSUE TITLE
PID parameter no longer displaying the value with the form title

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#364]
Opening any form including the &PID=ABC parameter is no longer showing the PID value in the form title area.

It was previously working like this (with PID = "001"):
![Annotation 2020-07-23 191554](https://user-images.githubusercontent.com/25179620/88347883-e3ec1d80-cd19-11ea-8eab-0ba87aaf4579.png)

But is now omitting the PID entirely:
![Annotation 2020-07-23 191846](https://user-images.githubusercontent.com/25179620/88347871-d9318880-cd19-11ea-8b3c-5e3c05eb5b26.png)

This is reproducible in all views, including /edit/fs/c/i/.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/::YYpM?PID=abc

**Comment by MartijnR** [comment]
it's added to head>title but not to the form title

**Comment by MartijnR** [comment]
@pbowen-oc should this also work in Participate?

**Comment by pbowen-oc** [comment]
@Martijn - We don't pass that parameter in for Participant views, so it doesn't need to work for that.

**Comment by pbowen-oc** [comment]
Looks good after testing.
