### ISSUE TITLE
Relevant error when loading empty form with date questions

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#366]
Further testing shows that this is also happening on other forms for all date items that have relevant conditions (at least for ones based on select_one items).

_Originally posted by @pbowen-oc in https://github.com/OpenClinica/enketo-express-oc/issues/352#issuecomment-665694817_

**Comment by MartijnR** [comment]
* [x] reproduce in enketo-express-oc - yes
* [x] reproduce in enketo-core (with validateContinuously set to true) - no
https://docs.google.com/spreadsheets/d/1eTt82akYGk8d2IwmkVjpLsFQeVowLMRFDdl32AAdqHg/edit?usp=sharing
http://localhost:8005/?xform=date-relevant.xml

Issue is likely with an OC customization. I don't think it has something to do with the performance fix.

Yes, disabling the relevant module extension prevents it.

* [ ] fix using http://localhost:8005/single/fs/i/Z4DAugjj?ecid=
* [ ] do final check with http://localhost:8005/single/fs/i/SdiVErEP?ecid=1

**Comment by MartijnR** [comment]
Found this to be a recent regression after a Firefox fix for date (and datetime and time) pickers. There were numerous DN widget bugs when linked to date/datetime/time questions as well caused by this. These are now also fixed. To avoid having to investigate and describe those yet undiscovered-but-now-fixed bugs, probably best to update test server soon @pbowen-oc.

**Comment by pbowen-oc** [comment]
Looks good after testing.
