### ISSUE TITLE
Form Closing Performance

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#368]
See form in email from me on 8/18. 

In 2.3.8.oc-3, when clicking the Close button after entering values in the first two fields, it is taking about 18 seconds for the form to respond. No submissions are occurring in this time.

The same form in 1.85.1.oc-1 responds in 1 second under the same scenario.

**Comment by MartijnR** [comment]
DS1 on Centro: http://localhost:8005/single/fs/i/HLH9tsA4?ecid=

**Comment by MartijnR** [comment]
Looks like this commit is the culprit. In OC we had previously relied on immediate clearing of irrelevant values and skipped clearing during validation (unlike in the rest of Enketo).

* [ ] check if the above change was accidental
* [ ] if it was change `form.validate` in Form.js or `relevant.update` in relevant.js in OC fork

**Comment by MartijnR** [comment]
back to old quickness (700 ms instead of 15,000 ms) with version `2.3.8.oc-4` in master

**Comment by pbowen-oc** [comment]
Looks good after testing.
