### ISSUE TITLE
Bring Edge 18 support back after next merge

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#369]
This support will be removed in enketo/enketo-express. This issue is a reminder to bring it back to this fork, as presumably that is desired.

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, that is desired!

**Comment by MartijnR** [comment]
Likely requires no action this time. Though in the future, it may very well require this (if libraries use unsupported modern syntax).

**Comment by MartijnR** [comment]
no action required
