### ISSUE TITLE
Does slow max-size response result in showing default max file size?

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#371]
* [x] confirm - this can actually be reproduced on http://localhost:8005/widgets (Ona) where Ona responds with 100000000 and only 5MB is shown to user)
* [x] fix in enketo/enketo-express
* [x] after merging into enketo-express-oc, add same fix to fieldsubmission entry point

**Comment by MartijnR** [comment]
done by 1537a67e42f0dd4c7c20d8d31ec6ebfe7a83d9b9

**Comment by pbowen-oc** [comment]
Looks good in testing.
