### ISSUE TITLE
Do not use old-fashioned mebibytes for megabytes

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#372]
(file upload max sizes)
https://en.wikipedia.org/wiki/Megabyte

**Comment by MartijnR** [comment]
* [ ] wait for merge

**Comment by MartijnR** [comment]
Seeing NaN in ee-oc:

<img width="520" alt="Screen Shot 2020-09-28 at 11 15 05 AM" src="https://user-images.githubusercontent.com/627350/94464625-ef295280-017b-11eb-8382-a307649f904c.png">




* [ ] check enketo-express

**Comment by pbowen-oc** [comment]
Looks good in testing
