### ISSUE TITLE
root node name length issue

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#374]
see email from @pbowen-oc on Sep 3, 2020

**Comment by MartijnR** [comment]
* [ ] try loading form in enketo-core

**Comment by MartijnR** [comment]
Note: clinicaldata XML file seems to have a an error `ItemGroupOID="IG_SITEI_ELIGIBILE"` whereas query looks for `IG_SITEI_ELIGIBLE`. This might not be cause though.

After correcting the above in the clinicaldata.xml file:

* removing `[@ItemOID='I_SITEI_DATE_UCOLITIS']` makes it work

**Comment by pbowen-oc** [comment]
Closing since this has not been seen again (possibly since we changed Pyxform versions).
