### ISSUE TITLE
Pasting invalid value into field clears the value but does not trigger a submission

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#381]
Steps:
1. Enter a valid value into an integer item (for example 10)
2. Copy a decimal value (for example 1.23)
3. Select the integer value and choose paste

Expected:
The integer value will be cleared since it is being pasted over. However, since the decimal being pasted is not valid for this item, the value will be set to null. The new null value will be submitted back to reflect the updated state of the form. The Query Widget History will show this value you change from the integer to null.

Actual:
Pasting causes the integer item to change to null, but does not trigger a submission. The change to null is also not listed in the Query Widget History.

This was previously working in 1.85.1.oc-1.

**Comment by MartijnR** [comment]
possible culprit in here: https://github.com/enketo/enketo-core/commit/cbd4c3e427ee59a7d9c464f9ad690b50abd742b6#diff-26fcebb749b5231eb5a84b1c7253e49c

**Comment by MartijnR** [comment]
* [ ] merge from enketo/enketo-express

**Comment by pbowen-oc** [comment]
Looks good in testing.
