### ISSUE TITLE
Note items are being displayed with extra read-only text field

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#382]
Note items previously just showed the item label text. With the latest version, they are now being displayed with a read-only text field under the label text. This applies to both Grid and non-Grid forms.
![Screenshot 2020-09-14 144911](https://user-images.githubusercontent.com/25179620/93126434-53d3b000-f69a-11ea-90ab-e3a06cf25065.png)

[note test1.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5220394/note.test1.xml.txt)

**Comment by pbowen-oc** [comment]
@MartijnR - I think we may have discussed this before, but I don't recall what the result of that was. Unfortunately, we have had user complaints about this behavior immediately upon release.

**Comment by MartijnR** [comment]
http://localhost:8005/widgets

**Comment by MartijnR** [comment]
Issue does not exist in latest enketo/enketo-express. Merge may resolve it.

**Comment by MartijnR** [comment]
* [ ] find out if css or readonly module issue. 
* [ ] if CSS issue, make temporary fix on master, if possible

**Comment by MartijnR** [comment]
was fixed in 2.3.9 (and introduced in 2.3.8)

**Comment by MartijnR** [comment]
added (minimal) fix to `2.3.8.oc-6`

**Comment by MartijnR** [comment]
* [ ] revert fix after merging to 2.3.9 or higher

**Comment by pbowen-oc** [comment]
Looks good after testing.
