### ISSUE TITLE
Print timings: detect when rendering complete

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#383]
some inconsistent results. Sometimes, Grid print script hasn't run or completed.

**Comment by MartijnR** [comment]
* [ ] use mutation observer in enketo-core print.js to determine when to resolve printGrid promise
* [ ] customize OC script and test, in branch
* [ ] let OC test problematic forms, in branch
* [ ] when fix is confirmed merge into enketo-core
* [ ] change script in ee
* [ ] merge ee into ee-oc and make additional oc-specific changes

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/mzpHKUGx

**Comment by MartijnR** [comment]
@pbowen-oc the branch `fix/print-timing` may not have this problem any more if we're lucky. It's right on top of the latest master. Please deploy and test internally.

**Comment by MartijnR** [comment]
put in master

**Comment by MartijnR** [comment]
ready for testing in master

**Comment by pbowen-oc** [comment]
Looks good.
