### ISSUE TITLE
clinicaldata items being submitted

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#386]
Items on forms defined as clinicaldata are being submitted unexpectedly. Our server is not expecting these items so it is causing submission failure errors.

I don't know if this could be related to the new Pyxform, but the XForm definition looks ok to me.

[clinicaldatasubmission.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5388604/clinicaldatasubmission.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/HAEFLj9W?ecid=1

**Comment by MartijnR** [comment]
Looks like enketo-validate no longer adds attribute

* [ ] fix in enketo-validate

**Comment by pbowen-oc** [comment]
Looks good.
