### ISSUE TITLE
Relevant/constraint error issue

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#387]
see failing test"

>"Customized Branching Logic for individual questions with relevant error interacting with constraint error shows relevant error but not constraint error when form.validate() is called FAILED"

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/KjuBFpgW?ecid=1

**Comment by MartijnR** [comment]
if field has constraint error and then gets a relevant error, the constraint error is supposed to be clear. Currently both errors remain shown.

**Comment by pbowen-oc** [comment]
Looks good in testing
