### ISSUE TITLE
Strict constraints and required functioning as standard constraints/required

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#389]
Strict constraints and required are being treated as standard constraints and required. Iit appears that constraint-type strict and required-type are being completely ignored.

[Strict test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5426776/Strict.test.xml.txt)

**Comment by pbowen-oc** [comment]
@MartijnR - I just realized you fixed #387 since we last deployed, so I will check again tomorrow and let you know if this is still an issue after that.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/RW6drPHf?ecid=1

**Comment by pbowen-oc** [comment]
@MartijnR - Something is still not as expected for these. I am now observing that entering an invalid value in the strict item causes the strict required/constraint popup to appear and the value is rejected. So, that part is working.

However, if I put the item in a state that violates the strict required/constraint by changing another item's value, then the strict item shows its error message with the red background rather than the orange background we use for strict errors. Also, while in the strict error state, I am not prevented from moving to the next page of the form as I was before.

**Comment by MartijnR** [comment]
```
Could not evaluate: /model/instance[1]/data/temp_group/ /model/instance[1]/data/temp_group/temp_units, message: The expression is not a legal expression.
```

**Comment by pbowen-oc** [comment]
Looks good in testing.
