### ISSUE TITLE
Autoquery not being submitted correctly when user navigates away instead of adding a required RFC

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#390]
Steps:
1. Open a complete form
2. Change a data value
3. Do not enter a Reason for Change
4. Navigate away from the form

Expected:
Because no RFC was entered, an autoquery for this condition will submitted automatically.

Actual:
A note of type Reason for Change is being submitted with the text intended for the autoquery. In other words, the submission is as expected except the note type should be Query not RFC.

**Comment by MartijnR** [comment]
```
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9 xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"><page1><temp_yn>1</temp_yn></page1></demo-vitals-grid-v9>&instance_id=someUUID&ecid=a&instance_attachments[test.jpg]=http://www.kobotoolbox.org/sites/toolbox/themes/Rise_sub/logo.png" http://localhost:8005/oc/api/v1/instance/edit/rfc
```

**Comment by MartijnR** [comment]
As far as I can tell this behavior was by design (and has always been like this). 

Will change the mechanism to switch to query type.

**Comment by pbowen-oc** [comment]
Looks good in testing.
