### ISSUE TITLE
Autoquery not submitted when form is opened with item initially irrelevant and having open query

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#393]
Steps:
1. Open an existing form where an item already has an open query and is irrelevant when the form is first opened
2. Change the form data to make the item with the query become relevant
3. Open the query widget

As expected, the query widget shows an auto-query entry to close the open query. However, this autoquery is not being submitted back. 

If the form is opened with the item relevant and data is changed to make it irrelevant after the form is opened, then the auto-query is submitted as expected when the item is hidden.

Example XForm:
[irrelevant autoquery test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5519903/irrelevant.autoquery.test.xml.txt)

Open this with a record tat has Item 1 as null and Item 2 with a query in New status. The form model will show Item 2's query being auto-closed but it won't be submitted.

**Comment by MartijnR** [comment]
empty: http://localhost:8005/single/fs/i/HfoTsJEB?ecid=1

reproduce: 
```

```

**Comment by MartijnR** [comment]
The `"Query closed by system because this item was hidden"` autoquery does seem to be submitted immediately after it has been generated (in the first session for that record).

**Comment by pbowen-oc** [comment]
@MartijnR - I am not seeing that submission (or any other) when I open the form with it starting in this state.

Here is the response to the instance call that I am getting for my test form posted above:
[irrelevant autoquery test instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5520785/irrelevant.autoquery.test.instance.txt)

When I toggle Item 1 to option 2, Item 2 becomes visible and the query widget shows the autoquery as expected, but there was never a submission call for it.
![Screenshot 2020-11-10 183501](https://user-images.githubusercontent.com/25179620/98746612-d4094f80-2383-11eb-97dc-828fb23e08ed.png)

**Comment by MartijnR** [comment]
@pbowen-oc, the submission is made during the first session, at the moment the question was made non-relevant and the autoquery was added. It is not added when you open an existing record with question 2 as non-relevant, because it is already there (or should be).

**Comment by pbowen-oc** [comment]
@MartijnR - That works for our primary cases. However, the use case here is either that data was imported into our system from an external source and then the form was opened with Enketo for the first time or that the data was migrated to a new form definition such that the item was relevant when the form was last edited but it was irrelevant when the form was edited again.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=autoquery&ecid=1&instance=<data xmlns:OpenClinica=\"http://openclinica.com/odm\" xmlns:enk=\"http://enketo.org/xforms\" xmlns:jr=\"http://openrosa.org/javarosa\" xmlns:oc=\"http://openclinica.org/xforms\" xmlns:orx=\"http://openrosa.org/xforms\" id=\"autoquery\" version=\"1\"><item_1>option_1</item_1><item_2/><meta><instanceID>uuid:453f91be-98cd-4a06-a294-c8c7d839bf46</instanceID><instanceID_comment oc:queryParent=\"instanceID\"/></meta><item_1_comment oc:queryParent=\"item_1\"/><item_2_comment oc:queryParent=\"item_2\">{\"queries\":[{\"type\":\"comment\",\"id\":\"1\",\"date_time\":\"2020-11-10 15:57:02.847 -07:00\",\"comment\":\"a query\",\"status\":\"new\",\"assigned_to\":\"\",\"notify\":false,\"thread_id\":\"3d01833c-ad32-4ed3-974d-1ea8dd173c61\"}]}</item_2_comment></data>&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit

```

**Comment by MartijnR** [comment]
Though it's possible to simply trigger the same inputUpdate event when a query is updated, this would probably affect performance negatively as it will run the whole evaluation cascade for any possible dependencies on the dn question. 

May be better to invent a new queryUpdate event instead. Tbc.

**Comment by MartijnR** [comment]
The issue is that the current logic relies on the Widget superclass (originalInputValue setter) to fire a change event. However, this event is not listened for until after the widget has initialized, so the model doesn't actually update (and a dataupdate event is not fired).

**Comment by MartijnR** [comment]
* [ ] make change in enketo core to add helper function isFormInitialized
* [ ] update ee
* [ ] merge into ee-oc
* [ ] make ee-oc changes

**Comment by pbowen-oc** [comment]
@MartijnR - This is not working as expected. The desired behavior is that an autoquery is generated when the form is opened since a queried item is non-relevant and that autoquery is submitted. It looks like now there is no autoquery generated in this case (and of course, no query is submitted).

**Comment by MartijnR** [comment]
Looks like this broke in a subsequent commit.

**Comment by pbowen-oc** [comment]
Looks good in testing.
