### ISSUE TITLE
Cannot complete some forms with required items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#394]
Some forms with required items (not sure of the exact cause) can't be completed. When clicking Complete, Enketo displays a message that all errors need to be addressed even when all required items have been entered and there are no errors for any items.

[cannot complete.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5531982/cannot.complete.xml.txt)

I tried to refine this form down further but could not reproduce the issue with a similar two item form (with one item required and irrelevant).

Note that this appears to be related to #389 as it only appeared when we deployed the latest update.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/3Jagy7wT?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
