### ISSUE TITLE
Repeating group error when nested non-repeating group has relevant logic

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#395]
[repeating group second instance error.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5540134/repeating.group.second.instance.error.xml.txt)

Repeating group relevant logic seems to reference a values in different repeat number unexpectedly.

Steps:
1. In the attached form, enter a value in the first item and then a value in the second item when it becomes relevant
2. Add a new repeating group

Expected:
The second repeat shows the first item as null and doesn't show the second item since it shouldn't be relevant.

Actual:
The first item is null, but the second item is shown (also as null) and with an error message that the value should be cleared (this message is different than our Relevant Error text). If the second item is cleared in the first repeat, the expected behavior is seen.

![Screenshot 2020-11-13 222623](https://user-images.githubusercontent.com/25179620/99138798-58b4d180-2601-11eb-8f6f-4d77cb4664de.png)

Note that this issue does not occur if the relevant logic is applied directly to the item without using a nested group.

This was observed in version 2.3.8.oc-6 with forms made using the old Pyxform. It is still present in the latest Enketo with forms made using the new Pyxform.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/PcLdRXm9?ecid=1

enketo-core:

**Comment by MartijnR** [comment]
* [ ] check enketo-core:

**Comment by pbowen-oc** [comment]
Looks good in testing.
