### ISSUE TITLE
Static defaults not submitted after first repeat

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#396]
Static default are not being submitted from repeating groups after the first repeat.

[repeating group static default submission.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5540179/repeating.group.static.default.submission.xml.txt)

Steps:
1. Open the attached form.
2. Note the default values are populated and submitted.
3. Add second repeat.

Expected:
The defaults are populated and submitted.

Actual:
The defaults are populated on the form. The defaults that are derived using functions are submitted but the static defaults are not submitted.

**Comment by MartijnR** [comment]
approach to consider:

* add event to setAllVals that OC controller listens for
* replace code for non-repeat defaults upon load to use same event

**Comment by pbowen-oc** [comment]
Looks good in testing.
