### ISSUE TITLE
Figure out how to use previous value for A as dynamic default of A in a new repeat instance

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#398]
might be a pyxform bug with indexed-repeat first arg (relative path), but we also couldn't immediately get it to work with XPath syntax either (Why doesn't /data/repeat1[position(..)-1]/question work))?

Possibly the model gets updated correctly but not the view?

**Comment by MartijnR** [comment]
* [ ] create pyxform issue if needed
* [ ] figure out XPath syntax to do this

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1rEpdmkYuJ_UzJtcCoOxQrKw-VOqPaS3n1psVgQzoVO0/edit?usp=sharing

**Comment by MartijnR** [comment]
XPath approach: http://localhost:8005/?xform=default-previous-repeat.xml

**Comment by MartijnR** [comment]
remaining is pyxform issue for indexed-repeat: XLSForm/pyxform#484

**Comment by pbowen-oc** [comment]
@MartijnR - The indexed-repeat function is still not returning a value. I don't know if I'm doing something else wrong that I'm just missing.
[indexed repeat set value test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5693744/indexed.repeat.set.value.test.xml.txt)

**Comment by MartijnR** [comment]
As you probably suspected, it looks like this form has been created using the bugged version of pyxform ;).

I see `indexed-repeat( ../bp_sys ,  /data/page2/bp_rg , position(..) - 1)`. The first parameter is relative and should be absolute after @gushil's fix.

**Comment by pbowen-oc** [comment]
@MartijnR - I think we are successfully running version 1.3.1 now. I tried the online converter at https://getodk.org/xlsform/ (which is apparently on 1.3.2) and I seem to be getting the same result in my XForm.

[demo-vitals-grid-v32-repeat test.zip](https://github.com/OpenClinica/enketo-express-oc/files/5700810/demo-vitals-grid-v32-repeat.test.zip)

Does the Pyxform issue need to be reopened?

**Comment by MartijnR** [comment]
Yes, you're right. Sorry, I didn't check. I've re-opened it.

**Comment by pbowen-oc** [comment]
All set with this.
