### ISSUE TITLE
Update History Widget display for selection items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#401]
We'd like to update the way selection item (select_one, select_multiple, select_one_from_file) values are displayed in the Query Widget history. Instead of just displaying them by code name, we also want to include code value. 

Each value should be listed like "<label> (name)" (for example, field changed from "Yes (1)" to "No (2)") (assuming label "Yes" corresponds to name 1).

**Comment by MartijnR** [comment]
See if jr:choice-name() can be used internally.

**Comment by pbowen-oc** [comment]
Looks good in testing.
