### ISSUE TITLE
Preview not showing alert for errors

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#402]

**Comment by MartijnR** [comment]
enketo-express:http://localhost:8005/preview/widgets - works ok

enketo-express-oc:

**Comment by MartijnR** [comment]
@pbowen-oc, I confirmed that for previews, we deliberately ignore non-strict violations. 

Will change that to default behavior now (but still show a different error message for strict violations).

**Comment by pbowen-oc** [comment]
Looks good in testing.
