### ISSUE TITLE
Read-only form is opening without Close button

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#403]
When I open a form that another user has open, I automatically get the form in read-only mode and see a message that the form is locked:
![Screenshot 2020-12-11 005037](https://user-images.githubusercontent.com/25179620/101869165-d14d7600-3b4c-11eb-9f5b-d2207bf8ab13.png)

This is behaving as expected except that the form does not have a Close button. We don't want this to be treated as an error condition. We just want to show this message and open the form in read-only mode.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=autoquery&ecid=1&instance=<data xmlns:OpenClinica=\"http://openclinica.com/odm\" xmlns:enk=\"http://enketo.org/xforms\" xmlns:jr=\"http://openrosa.org/javarosa\" xmlns:oc=\"http://openclinica.org/xforms\" xmlns:orx=\"http://openrosa.org/xforms\" id=\"autoquery\" version=\"1\"><item_1>option_1</item_1><item_2/><meta><instanceID>uuid:453f91be-98cd-4a06-a294-c8c7d839bf46</instanceID><instanceID_comment oc:queryParent=\"instanceID\"/></meta><item_1_comment oc:queryParent=\"item_1\"/><item_2_comment oc:queryParent=\"item_2\">{\"queries\":[{\"type\":\"comment\",\"id\":\"1\",\"date_time\":\"2020-11-10 15:57:02.847 -07:00\",\"comment\":\"a query\",\"status\":\"new\",\"assigned_to\":\"\",\"notify\":false,\"thread_id\":\"3d01833c-ad32-4ed3-974d-1ea8dd173c61\"}]}</item_2_comment></data>&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit
```

http://localhost:8005/edit/fs/i/HfoTsJEB?ecid=1&instance_id=a&load_warning=HEY!

**Comment by MartijnR** [comment]
@pbowen-oc with `readonly mode` you mean that submissions are disabled and the user cannot enter queries, right?

**Comment by MartijnR** [comment]
Note to self: 
* line 196 in controller-webform-fieldsubmission is where all buttons are removed if there are loadErrors.
* there is no mechanism yet to switch UI from review-only to read-only mode

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, we apply this logic when one user is in the form in edit mode or review-only mode to prevent another user from opening the form in edit mode or review-only and cause conflicts with their data/query entry into the same record.

**Comment by MartijnR** [comment]
Only in read-only and review-only mode I believe. My question is what to do exactly in review-only mode. I've updated my question above.

**Comment by pbowen-oc** [comment]
@MartijnR - I think there is a typo in your last message.

The expectation (and current behavior in our Prod environment) is that this behavior applies when opening an existing record in either edit mode or review-only mode. In either mode if this condition occurs the message should be displayed and the user should get read-only mode access to the form instead of their intended mode. I think we are handling the mode switch to read-only on our end and opening the form in read-only mode and sending along the message to be displayed when the form is opened.

I'm seeing a URL like this being passed to get into this state:
/view/fs/i/...form_parameters...&loadWarning=This%20form%20is%20currently%20unavailable%20for%20data%20entry.%20User%20pbowenusim%20is%20currently%20entering%20data.%20Once%20they%20leave%20the%20form%2C%20you%20can%20reopen%20the%20form%20and%20enter%20data.

**Comment by MartijnR** [comment]
It seemed safe to just never remove the close button from readonly and note-only views regardless of what kind of loadErrors are occurring (including load_warnings passed by OC).

**Comment by MartijnR** [comment]
What do you think of the last comment @pbowen-oc. Particularly when opening discrepancy-note-only views. There would be no change in fieldsubmissions, as those will always be disabled when any load errors occur.

**Comment by pbowen-oc** [comment]
I think consistency with removing the close button for all modes would be most useful.

**Comment by MartijnR** [comment]
remove when loadError other than OC-provided load_warning occurs

**Comment by pbowen-oc** [comment]
Looks good in testing.
