### ISSUE TITLE
Item with editable change event triggered calculation is being cleared when made irrelevant

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#404]
An item is in a group with a relevant condition. The item has a change event triggered to set its value when the group becomes relevant. When the item has a non-null value and the group is made not relevant, the item is being cleared. This is what we do for our standard calculated values since they are always read-only and the user cannot clear them manually. However, for items that are not read-only, we don't want to clear the value in this case since the user has control over that. In the typical change event triggered calculation case, the item will have a default but will still be editable and the user would be expected to clear the value themselves if the item (or its group becomes irrelevant).

![Screenshot 2020-12-14 161100](https://user-images.githubusercontent.com/25179620/102136522-7d31e280-3e27-11eb-930e-04b3a93b6a1b.png)

In that example, item temp is being cleared when the group becomes irrelevant.

[trigger from set value.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5693837/trigger.from.set.value.xml.txt)

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1H_3gIB9Y9vMx0PEwT8PD50qmTJOxUShS7CHn27U537o/edit?usp=sharing

**Comment by MartijnR** [comment]
@pbowen-oc not directly related to this issue but this is not how it happens:

> The item has a dynamic default to set its value when the group becomes relevant. 

Since dynamic defaults are only set when certain events occur (new-repeat or first-load), this value is populated upon load. I'm also (correctly) seeing the form above loads in a relevant error state:


<img width="880" alt="Screen Shot 2020-12-14 at 1 41 26 PM" src="https://user-images.githubusercontent.com/627350/102133279-1950ef00-3e12-11eb-86b4-029ad068fb66.png">

**Comment by MartijnR** [comment]
And wrt to the actual issue, I cannot reproduce it with the above form. The `def` question is never cleared by Enketo (like `calc` which is also never cleared). Only `note` is cleared when `grp` becomes non-relevant.

**Comment by pbowen-oc** [comment]
@MartijnR - Apologies. I was multi-tasking when I wrote that and said it completely wrong. I was actually referring to change event triggered calculations being cleared when irrelevant. I will fix it.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/1OsTIQ1C?ecid=1

**Comment by MartijnR** [comment]
branch `fix/relevant-calc-clearing` may provide a path forward, but many failing tests to look into (whether they are acceptable change of behavior).

**Comment by pbowen-oc** [comment]
@MartijnR - For us, I think, the distinction is generally between read-only items and user-editable items. We don't want to clear data when an item becomes irrelevant, but we also don't want the user to be stuck with no way to clear the errors on their form. So, I think the tradeoff is to clear read-only values (since the user may not be able to do it themselves) but not clear user-editable values since the user can simply delete the values as needed. For read-only values that are calculated in some way, the user should generally be able to cause them to be calculated again if they make them relevant.

The only potential problem I see with an approach like that would be for items that are read-only, but not calculated (because they are populated by a data import process outside of the form itself). For those, neither clearing the value nor not clearing the value seem like great options for behavior that will always occur.

**Comment by MartijnR** [comment]
Thanks @powen-oc, there is deeper issue here to be resolved first, since the clearing in this case is done in the calculation module in some inconsistent way

**Comment by MartijnR** [comment]
* [ ] publish new enketo-core
* [ ] propagate via enketo-express to enketo-express-oc
* [ ] fix any issue in fork

**Comment by MartijnR** [comment]
Ready for testing. Note, we should really use a published version of enketo-core for your deadline frozen state. I'm holding off in case any of the other issue require a fix in enketo-core.

**Comment by pbowen-oc** [comment]
Looks like this was also previously logged as #350.

**Comment by pbowen-oc** [comment]
Looks good in testing.
