### ISSUE TITLE
Calculations and change event triggered calculations are not triggering other change events

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#405]
If item2 is triggered based on item1 and item1's value is changed due to a calculation or change event triggered calculation, it is not triggering the change event for item2 as expected.

![Screenshot 2020-12-14 161100](https://user-images.githubusercontent.com/25179620/102137085-49a38800-3e28-11eb-99b7-153ac7593c11.png)

In this form, when item temp is changed via the change event action, it does not trigger item temp_units. If item temp is changed manually, it does trigger temp_units as expected.

[trigger from set value.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5693835/trigger.from.set.value.xml.txt)

The same occurs if the value is changed by a standard calculation rather than a change event triggered calculation.

**Comment by MartijnR** [comment]
Out of curiosity, do you see any use for `once()` now that we have dynamic defaults? I wonder if it has become obsolete.

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/12riPGFSXPs3i_LNR2MKKijysQV2nuw_twWoxZn2cqwg/edit#gid=0

**Comment by pbowen-oc** [comment]
@MartijnR - I think we will still use once() in calculations. It is possible that dynamic defaults or set values could cover what we use once() for, but I'd need more time with the new features to see if that is the case.

**Comment by MartijnR** [comment]
should be fixed, but still have to do a final check (Friday)

**Comment by pbowen-oc** [comment]
Looks good in testing.
