### ISSUE TITLE
Position function not evaluating as expected in repeating group

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#406]
The attached form has a default that should populate text in the repeating group for entries 1, 2, and 3, and leave it blank for entries 4 and on. However, after populating the expected text for each of the first 3 entries, it populates "Standing" (the text for entry 1) for entries 4 and on.

[repeat set value test2.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5693768/repeat.set.value.test2.xml.txt)

**Comment by pbowen-oc** [comment]
Also, the default value is populating even though the repeating group it is in is not relevant at form load. I wanted it to populate for the first repeat entry once I made the repeat relevant (as calculations work). I was able to get it to avoid populating this irrelevant item at form load by adding an if statement to my default (to align it with the relevant logic), but then it never populated the default for the first repeat entry. I can't think of a workaround other than to perhaps try to use the default for repeat entries 2 and up and use a set value for to populate row 1 when it becomes relevant.

**Comment by pbowen-oc** [comment]
@pbowen-oc - Verify this again after deploying the latest. It looks like it is not occurring. Try testing with the repeating group not having the relevant expression.

Workaround for the default value not populating on the first occurrence in the relevance case could be to create a separate set vlue trigger just for the first repeat.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/COaurZzW?ecid=1

Looks like the first repeat still has a bug.

**Comment by pbowen-oc** [comment]
Looks good in testing.
