### ISSUE TITLE
Items with setvalue triggers are not appearing with query bubbles.

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#408]
In the attached form, the temp_units item seems to be defined correctly and the XForm contains the associated comment item as expected, but it is not displayed on the form.

[trigger from set value.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5706910/trigger.from.set.value.xml.txt)

**Comment by MartijnR** [comment]
getLinkedQuestion has a bug. It's finding hidden setvalue inputs.

**Comment by pbowen-oc** [comment]
@MartijnR - I think I logged that other behavior already as #409.

**Comment by pbowen-oc** [comment]
Looks good in testing.
