### ISSUE TITLE
Consider not serving stylesheets in headless mode to improve performance

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#411]

**Comment by MartijnR** [comment]
* [ ] run large form without stylesheets in borwser to measure impact.

**Comment by MartijnR** [comment]
test form:
(empty regular view http://localhost:8005/single/fs/i/TO1o4ZMh?ecid=a)

```bash

```

**Comment by pbowen-oc** [comment]
Looks good in testing
