### ISSUE TITLE
readonly views load with TypeError

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#412]
caused by readonly module. Can probably be fixed in ee by tweaking the selectors in the readonlify function.

**Comment by MartijnR** [comment]
http://localhost:8005/view/c89e9303f524188382c4252ff9461228

**Comment by MartijnR** [comment]
check:
* calculated items
* preload items
* setvalue items

**Comment by pbowen-oc** [comment]
Looks good in testing
