### ISSUE TITLE
ClassList error opening any form in review-only or read-only mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#414]
Every existing form record opened in review-only or read-only mode (/edit/fs/dn/c/i/ and /view/fs/i/ including read-only mode for new forms with no instance /view/fs/i/) is opening with the following TypeError error about ClassList being null. Opening the same form in regular edit mode does not have this issue.

![Screenshot 2020-12-21 121806](https://user-images.githubusercontent.com/25179620/102810674-22057000-4392-11eb-94ae-d5ada34a44c1.png)

![Screenshot 2020-12-21 121724](https://user-images.githubusercontent.com/25179620/102810687-26ca2400-4392-11eb-9232-0ab9ef988047.png)

[read-only.xform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5726009/read-only.xform.xml.txt)

[read-only.instance.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5726012/read-only.instance.xml.txt)

**Comment by MartijnR** [comment]
Duplicate of #412? (fixed last Friday). 

* [ ] check

**Comment by MartijnR** [comment]
I hadn't applied the same fix to fieldsubmission views.

**Comment by pbowen-oc** [comment]
The following form is giving the same error when reopened in review-only mode (but not edit mode):
[FormRepeats ReadOnly.pab.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5806474/FormRepeats.ReadOnly.pab.xml.txt)
[FormRepeats ReadOnly.pab.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5806475/FormRepeats.ReadOnly.pab.instance.txt)

I see that the instance seems to have two null nodes that aren't present in the XForm, but I don't know if cleaning that up on our end (they shouldn't be there in the instance) will resolve it. The instance is the same in edit mode but does not cause the error.

**Comment by MartijnR** [comment]
http://localhost:8005/view/fs/i/df5ccb0e09aadba132ae3965d13879af?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
