### ISSUE TITLE
Error uploading calculate item with default but no calculation

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#416]
This form - [demo-vitals-grid-v32-calculate test.zip](https://github.com/OpenClinica/enketo-express-oc/files/5740813/demo-vitals-grid-v32-calculate.test.zip) - fails with a lengthy error from Pyxform when uploaded:

`Traceback (most recent call last): File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 195, in main_cli() File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 177, in main_cli enketo=args.enketo_validate, File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 49, in xls2xform_convert enketo=enketo, File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 1055, in print_xform_to_file raise error File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 1051, in print_xform_to_file file_obj.write(self._to_ugly_xml()) File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 838, in _to_ugly_xml return '' + self.xml().toxml() File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 243, in xml node("h:head", node("h:title", self.title), self.xml_model()), File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 546, in xml_model model_children += self.xml_bindings() File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey_element.py", line 479, in xml_bindings dynamic_default = e.get_setvalue_node_for_dynamic_default() File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey_element.py", line 369, in get_setvalue_node_for_dynamic_default default_with_xpath_paths = self.get_root().insert_xpaths(self.default, self) File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 996, in insert_xpaths return re.sub(BRACKETED_TAG_REGEX, _var_repl_function, unicode(text)) File "/usr/lib64/python3.6/re.py", line 191, in sub return _compile(pattern, flags).sub(repl, string, count) File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 993, in _var_repl_function matchobj, context, use_current, reference_parent File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 976, in _var_repl_function if _is_return_relative_path(): File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 960, in _is_return_relative_path and "indexed-repeat" in context["bind"]["calculate"] KeyError: 'calculate'`

If I add a dummy calculation to the calculate item ${cohort} (such as once(.)), this error does not occur. Note that other scenarios with a default defined with no calculation do not cause this issue. The dummy calculation can be removed from calculate item ${rndm} without causing this error.

Given the message at the end, is this related to #398 / https://github.com/XLSForm/pyxform/issues/484 ?

**Comment by pbowen-oc** [comment]
Less important, but still one I'd like to get changed: if the calculate item's default is static (for example, 5) and it does not have a calculation, a "Missing calculation." error occurs. This still requires a dummy calculation to get around, but at least it identifies the error and row number it came from.

**Comment by MartijnR** [comment]
Hey Paul, The zip file seems to be empty.

**Comment by pbowen-oc** [comment]
@MartijnR - Sorry about that, I uploaded a new copy of the file that should work.

**Comment by MartijnR** [comment]
These use cases (and all uses for type=calculate) really call for type=hidden. I wonder if this should be promoted more (and perhaps also in pyxform warning output)

* [ ] check support for these uses with type=hidden
* [ ] file pyxform issue for type=calculate (and perhaps for type=hidden)
* [ ] consider deprecating type=calculate (in documentation only initially - note type=calculate does not exist in XForms, it's an xlsform invention).

**Comment by MartijnR** [comment]
https://github.com/XLSForm/pyxform/issues/507

**Comment by pbowen-oc** [comment]
Looks good in testing.
