### ISSUE TITLE
Select Multiple error when more than one choice is selected

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#417]
Steps:
1. Open the attached form
2. Select a value for the select_multiple item
3. Select another value for the select_multiple item
4. Open the Query Widget for the item

Expected:
There should be no console errors when the selections are made. The Query Widget should show the history of each selection being made.

Actual:
There is a console error each time a selection is made when there is already a choice selected. The Query Widget doesn't show changes made for the additional selections.  Note that it is submitting each value as expected.

[select multiple.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5768081/select.multiple.xml.txt)

![Screenshot 2021-01-04 231321](https://user-images.githubusercontent.com/25179620/103606090-a05e2800-4ee3-11eb-916b-4b0bc0b57e80.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/gvjYC78D?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
