### ISSUE TITLE
Dynamic Defaults handled differently in first repeat and subsequent repeats

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#419]
Steps:
1. Open the attached form in preview mode - [defaults in repeats.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5778463/defaults.in.repeats.xml.txt)
2. Note that the defaults are populated for all 3 items shown in the first repeat
3. Add another repeat

Expected: 
Defaults will be populated the same way in the first repeat and subsequent repeats.

Actual:
One of the items is not populated in the second repeat (unlike the first).

![Screenshot 2021-01-06 175718](https://user-images.githubusercontent.com/25179620/103831642-7d01bd00-504a-11eb-9b04-31c4ad013e43.png)

Based on discussion, it may be that the first repeat's defaults are being processed twice and that is what is leading to different results. It seems that the expected behavior would be that the item is not populated in any repeat based on the order of default processing (items with no form control first, then items with form controls).

Steps:
1. Open the same form in edit mode
2. Look at the first repeat

Expected:
Given the above discussion, it is expected that items 1 and 2 will have defaults.

Actual:
Only item 1 has a default.

I got the same behavior when I added a second repeat. However, when I added a third repeat, the default was populated for the first two items (like how it was when the form was opened in preview mode).

![Screenshot 2021-01-06 175658](https://user-images.githubusercontent.com/25179620/103831652-8428cb00-504a-11eb-8f4c-0c3341e80762.png)

**Comment by pbowen-oc** [comment]
@MartijnR - Also on this form, the dynamic default values (when they are populated) are being reflected in the item history in the Query Widget. My understanding was that static defaults would not show up there since they are treated as initial values but dynamic default values would be treated like any other value change.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=defaults.in.repeats.xml.txt

**Comment by MartijnR** [comment]
> @MartijnR - Also on this form, the dynamic default values (when they are populated) are being reflected in the item history in the Query Widget. My understanding was that static defaults would not show up there since they are treated as initial values but dynamic default values would be treated like any other value change.

@pbowen-oc I'm not sure if you're asking or reporting something. If there is an issue with Enketo's audit log (after this fix is verified), please create a new issue.

**Comment by pbowen-oc** [comment]
@MartijnR - I was reporting a bug but with a typo that made it lose the meaning. I'll log an issue if it persists after this.

**Comment by pbowen-oc** [comment]
Looks good in testing
