### ISSUE TITLE
External List item in repeating group empty except in last repeat

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#423]
Steps:
1. Open the attached form
2. Add two additional repeats (for 3 total)
3. Select values for the items in the repeats, including for the select_one_from_file item
4. Close the form
5. Reopen the form

Expected:
The previous item values are all displayed.

Actual:
The select_one_from_file item is empty in repeats 1 and 2 and only has its previous value in repeat 3.

XForm:
[repeat_external.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5806818/repeat_external.xml.txt)

External List:
[elist.csv.txt](https://github.com/OpenClinica/enketo-express-oc/files/5806825/elist.csv.txt)

Instance:
[repeat_external.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5806827/repeat_external.instance.txt)

**Comment by MartijnR** [comment]
enketo-express-oc:

**Comment by pbowen-oc** [comment]
Looks good in testing.
