### ISSUE TITLE
Signature widget - reset button, download button, clicking area outside of the canvas trigger change events

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#428]
Steps:
1. Open the attached form - [SignatureTimestamp.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5818658/SignatureTimestamp.xml.txt)

2. Draw something in the signature widget
3. Note the timestamp is triggered in the next item by the drawing
4. Click outside of the canvas area (such as the Reset button, Download button, or just an empty space not in the canvas)

Expected:
Change events are only triggered by drawing in the canvas, so clicking outside of it will not trigger a change event.

Actual:
A change event is triggered (and sets the timestamp) with this click.

If the user clicks the Reset button and confirms the action, the signature is cleared and that also triggers the change event (which would be expected).

If the user clicks the Download button, an additional change event is triggered again when the download completes. It is triggered yet again when I close the download bar in Chrome after the signature download has completed.

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=SignatureTimestamp.xml

This happens when the canvas loses focus. So it doesn't actually respond to clicks outside the canvas. This is the actual correct change event (and e.g. how a text field works). The other events are a bit of a hack to save intermittently.

Not sure if it should be considered a bug.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/cJ1LlfOo?ecid=1

**Comment by pbowen-oc** [comment]
@MartijnR - I'm unclear on what the expected behavior is as of this fix. Will it still have any additional change event on leaving the canvas? To your point, I could see this potentially being the one and only change event associated with drawing, but the immediate change associated with incremental changes seem more accurate since each of those dose actually change the drawing image. If I were to draw my signature and wait a few minutes before clicking outside of the canvas, I wouldn't expect that the final change event would be when I made my last stroke, not when I clicked elsewhere minutes later.

**Comment by MartijnR** [comment]
>  If I were to draw my signature and wait a few minutes before clicking outside of the canvas, I wouldn't expect that the final change event would be when I made my last stroke, not when I clicked elsewhere minutes later.

Why would the behavior be different than with a text field?

In any case, my fixes do what you want, but I'm not entirely convinced it is 'right' because it's inconsistent.

**Comment by pbowen-oc** [comment]
Thanks, Martijn.

I think the drawing widget is saving stroke by stroke. For a text item, you can type a key and hit backspace and the system doesn't save the intermediate value at any point. The change event behavioral difference flows naturally from that difference from my perspective.

**Comment by MartijnR** [comment]
Yes, I agree. That's a good comparison with select multiple.

**Comment by pbowen-oc** [comment]
Looks good in testing.
