### ISSUE TITLE
Multi-select item with set value trigger for another item is setting itself

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#432]
In the attached form, there is an editable multi-select item and read-only multi-select item. The read-only item should be triggered to calculate a value based on the selection in the editable item. However, making a selection in the editable item is triggering that same item instead of the other item.

Steps:
1. Open the attached form - [MultiSelect_v2.pab.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5859611/MultiSelect_v2.pab.xml.txt)
2. Make a selection in the first item

Expected:
The second item should be set based on the set value trigger.

Actual:
The first item is set based on the set value trigger (i.e., the item is setting itself).

**Comment by MartijnR** [comment]
* [ ] reproduce in enketo-core with simplified form:

**Comment by MartijnR** [comment]
done! ping @pbowen-oc

**Comment by pbowen-oc** [comment]
Looks good in testing.
