### ISSUE TITLE
clinicaldata items getting submitted back

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#438]
A oc:external="clinicaldata" item is being submitted back if it's value is populated by a default. These items should not be submitted whether populated by a calculation, default, or set value trigger.

Example form (with default):
[default clinicaldata.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5891214/default.clinicaldata.xml.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/IfIf6hFC?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
