### ISSUE TITLE
Close button not working on completed form in IE11 or Edge Legacy

### ISSUE THREAD

**Issue by theywa** [OpenClinica/enketo-express-oc#439]
On IE11 or Edge Legacy, the close button on the completed form did not redirect the user to the previous page.
![EdgeLegacyCloseBtnNotWorking](https://user-images.githubusercontent.com/13865076/106482786-6b43f600-64e0-11eb-9d05-9e0d6d5d9a3f.png)

After debugging, it looks like `node.firstElementChild` not working properly on IE11 and Edge Legacy.

**Comment by theywa** [comment]
Hi @MartijnR, I create the PR for this issue, if you have time can you take a look? thank you

**Comment by pbowen-oc** [comment]
Looks good in testing.
