### ISSUE TITLE
Opening a form to hidden item is treating as an error condition (no Close button, no submissions)

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#443]
When a form is opened directly to an item/query on an item (for example, with a url like /edit/fs/c/i/...%2F%2Ftemp_comment) and that item (in this case, temp) is not relevant, the form loads with a message to user as designed.  However, it is also currently loading without Close and Complete buttons. If the user tries to enter data, the "Saving is disabled." message appears on the form and no data is submitted.

This is not an error condition, so the expectation is the the Close/Complete buttons appear and data is submitted as usual in this case.

![Screenshot 2021-02-02 234616](https://user-images.githubusercontent.com/25179620/106699900-c09c0800-65b1-11eb-8c0c-448296635437.png)

This should also be the case for opening directly to an item that is not present on the form at all (such as when the form definition has changed).

**Comment by MartijnR** [comment]
fix related to #403 perhaps

**Comment by MartijnR** [comment]
@pbowen, if the "goto" question is regular question (not a query item), you'd also want to treat that as a not so error as above, right?

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, that is correct.

**Comment by pbowen-oc** [comment]
Looks good in testing.
