### ISSUE TITLE
Trigger for item outside of repeating group causes error when item in repeating group is changed manually

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#448]
If item outside of a repeating group uses an item in a repeating group as a change event trigger, when that item in the repeating group is manually changed it causes a console error and does not process any further (such as other items that should also be triggered by the item in the repeating group). Note: repeat ordinal 1 works fine, but subsequent repeats fail.

If the same item in the repeating group is changed via default (when a new repeat is added) or triggered change event, there is no error and the change event outside of the repeating group occurs as expected.

Steps:
1. In the attached form ( [RGSV version 2.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5955893/RGSV.version.2.xml.txt) ), add a new repeating group entry
2. Note that the first item on the form (outside the repeating group) is changed to a random number because of the default applied to the last item in the repeating group entry just added
3. In the second repeat, toggle the select item
4. Note that this changes the last item in the repeating group and also changes the first item on the form to a different random number
5. Manually change the last item in the repeating group (in the second repeat)

Expected:
The first item will be changed to a new random number.

Actual:
The first item does not change. There are errors in the browser console:
![Screenshot 2021-02-09 234042](https://user-images.githubusercontent.com/25179620/107465924-3dd6f800-6b31-11eb-80eb-f20daf5a523a.png)

**Comment by MartijnR** [comment]
* [ ] reproduce in enketo-core:

**Comment by pbowen-oc** [comment]
Looks good in testing
