### ISSUE TITLE
Goto hidden message 2nd sentence is missing.

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#45]
Please use the View Query Only icon instead of the View Query Within Record icon to see it.

(put in Develop)

**Comment by MartijnR** [comment]
The logic that is intended:

if `goto` field is not a dn item, don't show any error

if `goto` field is a dn item show the "The item is currently hidden". In addition, show either "Please use the View Query Only icon instead of the View Query Within Record icon to see it." if API request did not include a `go_to_error_url`, or show "Please visit [this form]() to see it."

**Comment by MartijnR** [comment]
* [ ] reproduce dn case with go_to_error_url
* [ ] reproduce dn case without go_to_error_url

**Comment by MartijnR** [comment]
Looks like the custom handler for gotohidden errors is overridden by the generic loadError handler (so both are shown in quick succession.

**Comment by MartijnR** [comment]
@powen-oc, the difference you're observing with the missing sentence is related to whether the question is a discrepancy note or a regular question. This was by design.

Maybe it's not what OC requires though.

**Comment by pbowen-oc** [comment]
@MartijnR - We're observing the issue when we try to open the form to the DN item. Let's debug on our next call if you are seeing something different.

**Comment by MartijnR** [comment]
That's actually what I'm seeing, and was deliberate (I updated some of my descriptions above after you go the email notification probably). Yes, we can discuss how to change.

**Comment by MartijnR** [comment]
Looks like I switched the logic. The complex message is for go_to's pointing to a dn item.

**Comment by MartijnR** [comment]
for dn items:

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><wh_y>1</wh_y></page1></demo-vitals-grid-v9>&instance_id=b&load_warning=Hey you&ecid=a&go_to=//temp_comment&go_to_error_url=https://enketo.org" http://localhost:8005/oc/api/v1/instance/edit
```


```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9><page1><wh_y>1</wh_y></page1></demo-vitals-grid-v9>&instance_id=b&load_warning=Hey you&ecid=a&go_to=//temp_comment" http://localhost:8005/oc/api/v1/instance/edit
```
