### ISSUE TITLE
Irrelevant items (via group logic) with values are not shown in review-only mode or read-only mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#450]
Open a form that has data for items that are not relevant due to the relevant logic for the group they are in. In edit mode, the items are displayed along with the expected relevant error message for the group. In review-only mode or read-only mode, the items are not displayed.

XForm: [Relevant Group.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5969498/Relevant.Group.xml.txt)

Instance: [Relevant Group.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5969499/Relevant.Group.instance.txt)

**Comment by MartijnR** [comment]
edit (without issue):

readonly:

**Comment by MartijnR** [comment]
Relevant deactivation is deliberately ignoring readonly items. This is probably desired except for those questions that were artificially made readonly in the note-only and readonly views.

**Comment by pbowen-oc** [comment]
Looks good in testing
