### ISSUE TITLE
Add Another Form feature is closing forms when data is entered

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#453]
Steps:
1. Open a new form in edit mode for a form that is configured to use the Add Another Form (See issue #320)
2. Enter data into an item
3. Check the Add Another Form checkbox at the bottom of the form
4. Enter or change data for an item

Expected:
The item data is changed and the form remains open in edit mode.

Actual:
The form is closed and the next instance of the form is opened.

The expectation is that only Close or Complete will close the form and initiate the Add Another Form action. Entering item data should not initiate the Add Another Form action regardless of whether the checkbox is currently checked or unchecked.

**Comment by theywa** [comment]
an issue on study runner's script
