### ISSUE TITLE
Select item in repeating group not cleared after becoming non-relevant

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#454]
This appears to be a regression of #347.

Steps:
1. In the attached form, enter a text value.  [SelectRelevantRG.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6033308/SelectRelevantRG.xml.txt)
2. When the select item becomes relevant, select a value for it
3. Clear the text item
4. Clear the select item

Expected:
Since the select item became non-relevant when the text item was cleared, the select item should be hidden once the user clears the value from it.

Actual:
The select item remains visible with a relevant error even though it is null.

Note: This was broken prior to the most recent patch.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/FIof6XRa?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing
