### ISSUE TITLE
Node positional calculation not working dynamically

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#455]
The attached form attempts to read in from the clinicaldata instance using three different methods:
1. Using node position: [1]
2. Using node position: [position()=${rownum}] where ${rownum} = 1 (from a calculate item = position(..))
3. Using node position: [number(${rownum})] where ${rownum} = 1 (from a calculate item = position(..))

Only the first method reads in the value successfully. The other options read in null. All three were expected to work.

Method #2 was in use on the original source form prior to deploying 2.5.6.oc-5 and working successfully then. Since that time, it reads no data.

XForm: [NodePositionCalc.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6033555/NodePositionCalc.xml.txt)

Clinicaldata instance: [NodePositionCalc.clinicaldata.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6033556/NodePositionCalc.clinicaldata.xml.txt)

![Screenshot 2021-02-24 001514](https://user-images.githubusercontent.com/25179620/108951784-a3011200-7636-11eb-8cbc-130c7fafbeb1.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=NodePositionCalc.xml

**Comment by MartijnR** [comment]
I believe the two none-working formulas are evaluating correctly because current() is missing in the predicate. That would be a pyxform issue then. Will confirm.

* [ ] run original form in enketo-express-oc with correction of predicate to `current()/../rownum` to confirm that the XForm is wrong
* [ ] test similar xlsform in latest pyxform
* [ ] file bug report in pyxform if necessary

**Comment by MartijnR** [comment]
Pyxform issue already posted: https://github.com/XLSForm/pyxform/issues/490

**Comment by MartijnR** [comment]
> Method #2 was in use on the original source form prior to deploying 2.5.6.oc-5 and working successfully then. Since that time, it reads no data.

Definitely no recent change in this very elementary XPath evaluation in Enketo. XPath expressions are clearly incorrect.

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. Am I correct in assuming that we will need to take this approach for now for any item references used in the instance expression? Is this syntax going to vary if the item being referenced is in a different group than the item that has this instance expression?

**Comment by pbowen-oc** [comment]
I have created a new Pyxform issue (https://github.com/XLSForm/pyxform/issues/531) since the previous fix was incomplete and did not handle expressions that contained spaces.

**Comment by pbowen-oc** [comment]
This is all set.
