### ISSUE TITLE
Error opening form using jr:choice-name function

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#457]
We have a form that has a calculation using the jr:choice-name function. The item it refers to uses choice filters and the labels for the choice include item references:

![Screenshot 2021-02-24 165557](https://user-images.githubusercontent.com/25179620/109071239-734b1c00-76c1-11eb-84f0-b2f384c5ecb8.png)

![Screenshot 2021-02-24 165507](https://user-images.githubusercontent.com/25179620/109071218-6f1efe80-76c1-11eb-81c1-e78560d3c710.png)

The form sometimes loads with this error: TypeError: Cannot read property 'previousElementSibling' of undefined
![Screenshot 2021-02-24 165657](https://user-images.githubusercontent.com/25179620/109071188-6a5a4a80-76c1-11eb-9811-dba04005af2c.png)

**Comment by MartijnR** [comment]
Actually, there is another possible cause that is almost fixed: https://github.com/enketo/enketo-core/issues/738.

It's nearly the same issue. Will fix today and add to oc master.

**Comment by pbowen-oc** [comment]
Looks good in testing
