### ISSUE TITLE
Entire repeating group is hidden if repeating group is non-relevant and first repeat occurrence is cleared

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#458]
If a repeating group has group-level relevant logic and multiple repeat entries are added to it, when the group becomes non-relevant and the first repeat is cleared of editable data, the entire repeat is being hidden from view even if there is data in repeats after the first one.

Steps:
1. Open the attached form in edit mode - [RGRel.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6040345/RGRel.xml.txt)

2. Enter a value in item2
3. Add another repeat
4. Enter a value in item 2 in the second repeat
5. Enter a value in item1 (this makes the repeating group non-relevant)
6. Clear the value in item2 in the first repeat

Expected:
The value is cleared but the repeating group remains visible since the second repeat still has data.

Actual:
The repeating group is hidden.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/vLi9ex7D?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing
