### ISSUE TITLE
Non-relevant items not disappearing in pages style

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#459]
Steps:
1. Open this form in edit mode -  [Relevant_pages.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6040670/Relevant_pages.xml.txt)
2. Enter 1 in the first item (this will make the second item relevant on the next page)
3. Enter a value in the second item
4. Go back to the first page and clear the value of the first item
5. Return to the second page. Note the second item has a relevant error as expected.
6. Clear the vale for the second item

Expected:
The second item disappears since it is now empty and not relevant.

Actual:
The second item remains visible but with a disabled lookin style.

Note that the Query Widget is still active for the second item and will pop under some of the form in a way that makes it hard or impossible to access.

![Screenshot 2021-02-25 002458](https://user-images.githubusercontent.com/25179620/109107854-7adde580-7700-11eb-927d-f0763ef0662d.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/l4dI7HUC?ecid=1

**Comment by MartijnR** [comment]
I'd recommend leaving as-is with DN widget disabled.

**Comment by pbowen-oc** [comment]
Looks good in testing
