### ISSUE TITLE
Some selection items not displaying name and label in history

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#460]
Issue with #401.

Selection items that use the "no-buttons" style are not displaying both name and label in the Query Widget history. They only display name like before #401 was added.

Additional, we have older forms that still use "horizontal-compact" and other older appearances rather than 'columns-pack" and the equivalent newer appearances. These older items look fine on the form but are also only displaying name in the query Widget History.

In the attached form, the first item displays history as expected, but the other items do not.
[appearance history.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6040886/appearance.history.xml.txt)

See also #435 and #436

**Comment by MartijnR** [comment]
Sounds like the question style is leaking into the dn widget style. If so, best to address in the DN widget style.

**Comment by theywa** [comment]
@MartijnR ~ found the reason, there is no condition for horizontal-compact and no-buttons appearance on dn widget. Which approach will be better, update the existing condition(like the current PR) or create a new condition(else if)?

**Comment by pbowen-oc** [comment]
@pbowen-oc - Make a list of all older appearances that this should cover (not just horizontal-compact). We should have a test form to cover them all.
@theywa

**Comment by MartijnR** [comment]
I see I had misdiagnosed the problem. Sorry about that @theywa. You solution is great.

There may indeed be other appearances out there that cause the same problem (but I've merged the solution for these 2).

**Comment by pbowen-oc** [comment]
Looks good in testing.
