### ISSUE TITLE
Form Printing adding page breaks in the middle of an item

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#463]
Form PDF generation is breaking pages in the middle of an item.

**Comment by MartijnR** [comment]
Using print button in preview, using Chrome.

**Comment by theywa** [comment]
Hi @MartijnR ~ I'm able to reproduce it using preview. it looks like related to "break-inside" not working correctly on flex. still investigating. also, I found [how-to-get-page-break-inside-avoid-to-work-nicely-with-flex-wrap-wrap](https://stackoverflow.com/questions/20408033/how-to-get-page-break-inside-avoid-to-work-nicely-with-flex-wrap-wrap), is the workaround script on print.js?

**Comment by MartijnR** [comment]
That's funny that you found that! I don't remember if that's the solution in print.js or not, but the script basically disabled flexbox and mimics it instead using fixed widths and heights.

**Comment by theywa** [comment]
@MartijnR  ~ I see, somehow that on the first list when I googling 😄 .
I update the CSS on _print-oc.scss to fix that, is that acceptable?

**Comment by MartijnR** [comment]
@pbowen-oc version 2.5.6.oc-11 can be tested with this fix now

**Comment by pbowen-oc** [comment]
Looks good in testing.
