### ISSUE TITLE
Pages theme form loaded with data in non-relevant items shows those items on every page

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#465]
Steps:
1. Open the attached form ( [Pages Relevant.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/6146247/Pages.Relevant.xform.txt) ) with the attached instance ( [Pages Relevant.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/6146249/Pages.Relevant.instance.txt) ) containing data in a non-relevant item

Expected:
The non-relevant item is visible since it has data, but only on the page it belongs to.

Actual:
The non-relevant item is displayed on every page.

![Screenshot 2021-03-16 010520](https://user-images.githubusercontent.com/25179620/111259257-f1318180-85f4-11eb-9416-6b79f8dc3cc5.png)
![Screenshot 2021-03-16 010533](https://user-images.githubusercontent.com/25179620/111259258-f1ca1800-85f4-11eb-871c-7ea06f37ea98.png)
![Screenshot 2021-03-16 010549](https://user-images.githubusercontent.com/25179620/111259259-f1ca1800-85f4-11eb-8fb3-96326a4cb65d.png)
![Screenshot 2021-03-16 010606](https://user-images.githubusercontent.com/25179620/111259256-f098eb00-85f4-11eb-8cbe-9319bd0d89e9.png)

The same also happened when the relevant logic was at the group level rather than the item level.

**Comment by MartijnR** [comment]
sounds like a CSS issue

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/lPHVgqKb?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
