### ISSUE TITLE
History not updated in the Query widget when selected choice becomes filtered out

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#467]
Steps:
1. Select a choice in a select or multi-select item
2. Update another value such that the choice becomes filtered out
3. View the Query Widget

Expected:
The Query Widget History should reflect that the choice was deselected when it was filtered.

Actual:
The Query Widget does not show any history after the choice was filtered.

The choice being filtered is accompanied by a console error:
![Screenshot 2021-03-17 012653](https://user-images.githubusercontent.com/25179620/111420745-27890280-86c2-11eb-92ac-f1b51a6ee432.png)

This behavior persists until the the choice is unfiltered. Presumably it is unable to look up the label of the filtered choice to populate the old value portion of the next history entry.

It does not appear that this affects item submission.

Here is a sample test form:
[Choice filter test1.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/6153983/Choice.filter.test1.xform.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/36l6zfJH?ecid=1

**Comment by MartijnR** [comment]
For this case it would be easiest to fall back to just the value (and generally for any other case where the label cannot be found).

**Comment by pbowen-oc** [comment]
This approach makes sense to me.

**Comment by pbowen-oc** [comment]
Looks good in testing.
