### ISSUE TITLE
Functions using node-set arguments do not work inside a repeating group when referring to an item in the group

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#468]
Related to #398

All node-set functions (except indexed-repeat) fail to work as expected when used inside a repeating group and referencing an item in the same repeating group. They act only on the item within the same repeat instance rather than the node-set of the item across all repeats.

The indexed-repeat function was previously updated in Pyxform to resolve this issue and work correctly within repeating groups. See issue https://github.com/XLSForm/pyxform/issues/484

The same behavior occurs in all other node-set functions tested:
count
count-non-empty
sum
max
min
concat
join
randomize

In Pyxform v2.4.1 these are still showing the behavior that indexed-repeat was showing before it was fixed. I'm not sure if I missed any other supported node-set functions.

Test XLS: [function_nodeset_test.zip](https://github.com/OpenClinica/enketo-express-oc/files/6161252/function_nodeset_test.zip)

Resulting XForm: [function_nodeset_test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6161249/function_nodeset_test.xml.txt)

**Comment by pbowen-oc** [comment]
@MartijnR - Can you log an appropriate Pyxform issue for this?

**Comment by MartijnR** [comment]
https://github.com/XLSForm/pyxform/issues/525

**Comment by pbowen-oc** [comment]
We decided not to move forward with this change.
