### ISSUE TITLE
Image file download fails on iPhone

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#469]
The download button doesn't do anything for image items when tapped on an iPhone in Safari. 

Tested on iPhone 12 Pro, iOS 14.4

The same test worked as expected and did download the image file to the Files app on an iPad in Safari (running the same software as the iPhone above).

Tested on iPad Pro 11" 2018, iPadOS 14.4

**Comment by pbowen-oc** [comment]
This appears to be related to an issue on my form as it doesn't occur on a test form I created for this. The form that it failed on seems to not be saving data correctly (Failed to save changes), and I think the issue causing that is related to the download button not working.

**Comment by MartijnR** [comment]
😅
