### ISSUE TITLE
Preview error: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#472]
With the new XPath evaluator deployed, previewing a form is failing with the following error:
Cannot read property 'dataset' of null

![Screenshot 2021-04-06 231852](https://user-images.githubusercontent.com/25179620/113805906-61807e00-972f-11eb-9378-c0296bbd537c.png)

XForm:
[Simple Form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6268781/Simple.Form.xml.txt)

**Comment by pbowen-oc** [comment]
We pass in an empty user list for the Query Widget in this case. I'm not sure if that could be what is triggering this error.

**Comment by MartijnR** [comment]
Cannot reproduce with same form on http://localhost:8005/view/fs/i/b836393fc3917ddd7488da3fcd437c53?ecid=1.

Using an empty xml file provides a different error for me. @pbowen-oc Could you please check if your URL looks similar and what the exact content of the empty users list is?

**Comment by MartijnR** [comment]
Ok, never mind, I can reproduce with http://localhost:8005/preview/?form=http://localhost:3000/form/Simple.Form/form.xml

**Comment by pbowen-oc** [comment]
Looks good in testing.
