### ISSUE TITLE
Instance error: Too many tokens

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#473]
With the new XPath evaluator deployed, reopening an existing form with instance data is failing with the following error:
Could not evaluate: /model/instance[1]/node()/@oc:complete = "true", message: Too many tokens.{"stack":[{"t":"root","tokens":[{"t":"arr","v":[{}]},{"t":"bool","v":false}]}],"cur":{"v":""}}

![Screenshot 2021-04-06 233428](https://user-images.githubusercontent.com/25179620/113806817-0780b800-9731-11eb-8ec9-849bf70961f3.png)

XForm:
[Simple Form.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6268802/Simple.Form.xml.txt)

Instance:
[Simple Form.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/6268809/Simple.Form.instance.txt)

**Comment by MartijnR** [comment]
Thanks. That's a weird one, as the expression itself seems incorrect.

**Comment by MartijnR** [comment]
* [ ] report bug with tests
* [ ] edit Enketo because using `*` is actually better than using `node()` here

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=dn-calculate&instance=\
    <dn-calculate xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"><a>1</a><meta><instanceID>a</instanceID></meta></dn-calculate>&instance_id=a&ecid=b" http://localhost:8005/oc/api/v1/instance/edit```

**Comment by MartijnR** [comment]
I marked this as ready for final review, as I changed the XPath syntax to a better syntax, and that works around this issue.

However, the XPath evaluator issue still exists and should be fixed, so we could leave this open to track that.

**Comment by pbowen-oc** [comment]
The solution worked to allow us to continue testing. I'm removing the tag since the remaining update is still needed to finish this.

**Comment by MartijnR** [comment]
the underlying problem with the evaluator is now fixed as well, so will close
