### ISSUE TITLE
Update IE11 build to avoid new XPath evaluator

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#474]
Forgot the most time-consuming part....

**Comment by MartijnR** [comment]
* [ ] add a separate rollup task for IE11 
* [ ] use that bundle as the IE11 source

**Comment by MartijnR** [comment]
I was able to test this on IE11 (not Edge Legacy), and it all looks good.

Same installation as before, and same XPath evaluator as before.

**Comment by pbowen-oc** [comment]
Looks good in testing.
