### ISSUE TITLE
Headless mode failing for complete forms with null required items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#476]
Steps:
1. Open a complete form in headless mode where one of the items is required and empty (use /headless/rfc/ since the form is complete)

Expected:
Headless mode api creates an auto-query for the null required item, "This field is required".

Actual:
The call returns the following error:
"{
    "message": "waiting for selector `#headless-result` failed: timeout 120000ms exceeded"
}"

Opening this same record in the UI is working properly. When the form is opened and close button is clicked, it shows the popup "Some field have errors which must be addressed before the form is closed". Clicking Proceed is adding autoqueries to items with errors.

XForm:
[RequiredItem.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/6300875/RequiredItem.xform.txt)

Instance:
[RequiredItem.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/6300876/RequiredItem.instance.txt)

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=RequiredItem&ecid=1&instance_id=a&instance=<data xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"   xmlns:enk=\"http://enketo.org/xforms\" ><MHX enk:last-used-ordinal=\"1\"  enk:ordinal=\"1\" ><diagnosis>Diag</diagnosis><rating></rating><diagnosis_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"Diag\\\"\",\"user\":\"root\",\"date_time\":\"2021-04-10 12:35:44.317 -04:00\"}]}</diagnosis_comment><rating_comment></rating_comment></MHX><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></data>" http://localhost:8005/oc/api/v1/instance/edit
```

**Comment by pbowen-oc** [comment]
Looks good in testing
