### ISSUE TITLE
Calculated item with relevant logic not working as expected

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#481]
The attached form has an item that is editable and another item that is calculated to be the value of the first item and only relevant when the first item is null. There are two issues that may or may not be related.

Steps:
1. Open the attached form in edit mode. [relevant calculation test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6395893/relevant.calculation.test.xml.txt)
2. Enter a value for the first item.

Expected:
The second item will become hidden due to its relevant logic.

Actual:
The second item becomes hidden, but there is a field submission for it that sets it to the value of the first item. This is unexpected since the item is not relevant. Additionally, if the value of the first item is changed from one radio button to the other, there is another field submission for the second item even though it is not relevant and the change in value keeps it non-relevant.

Steps (continued):
3. Deselect the radio button for the first item so that it becomes null

Expected:
The second item becomes visible again and has a null value.

Actual:
The second item becomes visible again but it shows the value of the radio button that was just deselected for the first item. This could be a display issue. When the first item was changed to null, there was a field submission of null for the second item (which really shouldn't have happened, but it is consistent with the behavior above). This is also observed in the History widget which shows the second item was changed to null. So, the display is not in sync with the value submitted or displayed in the item history.

![Screenshot 2021-04-28 220445](https://user-images.githubusercontent.com/25179620/116493955-d85ff100-a86d-11eb-9292-5fc97dfef099.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=relevant.calculation.test.xml

**Comment by MartijnR** [comment]
Note that with the form above it is not possible to set a value for `Visit_option_patient_con1`.

**Comment by pbowen-oc** [comment]
Looks good in testing
