### ISSUE TITLE
create high-level overview of OC customizations (across Enketo tools)

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#483]

**Comment by pbowen-oc** [comment]
@MartijnR - Do you have/can you create a list of the customizations? I can describe the purpose of them if there is a list. Otherwise, I can list a few of the big ones that I know are custom for us.

**Comment by MartijnR** [comment]
I actually started one. Let me create a branch for it.

**Comment by MartijnR** [comment]
Here it is: https://github.com/OpenClinica/enketo-express-oc/pull/489 Since it's just markdown, editing in the browser may work.

**Comment by MartijnR** [comment]
done with 2bf9946838b40c21dc139278667eb62d5c9dd6fd
