### ISSUE TITLE
Offline not working

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#485]
domain.com/x/offline-app-worker.js is returning a 500 error

<!DOCTYPE html><html lang="en" dir="ltr"><head><title>OpenClinica Participate</title><meta charset="utf-8"><meta name="author" content="Martijn van de Rijdt (Enketo LLC)"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="/images/favicon.ico"><link rel="icon" type="image/png" sizes="180x180" href="/images/icon_180x180.png"><link rel="apple-touch-icon" sizes="180x180" href="/images/icon_180x180.png"><link rel="stylesheet" href="/css/error.css"></head><body><h1 class="error">ENOENT: no such file or directory, open '/public/js/src/module/offline-app-worker-partial.js'<span class="status-code">Error Code: 500</span></h1></body></html>

**Comment by MartijnR** [comment]
I had to try fixing this blindly, since it's likely a particular deployment environment related issue.

Try branch `fix/service-worker-485`.

**Comment by MartijnR** [comment]
can be closed I believe

**Comment by pbowen-oc** [comment]
Confirmed that offline functionality is working for us on the latest builds.
