### ISSUE TITLE
Logic using if() and another clause evaluates incorrectly

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#491]
An if() function joined with another clause by "and" or "or" is always being treated as true.

Test form:
[if_calculation.1.xls](https://github.com/OpenClinica/enketo-express-oc/files/6641609/if_calculation.1.xls)
[calculation_if_test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6649095/calculation_if_test.xml.txt)

![Screenshot 2021-06-11 234351](https://user-images.githubusercontent.com/25179620/121764078-1740c200-cb0f-11eb-91d1-3aadd27d456c.png)

This form works as expected in 2.5.6.oc-11

**Comment by pbowen-oc** [comment]
The test form above uses calculations to demonstrate the bug. We initially found it in constraints since we always modify the user's specific constraint logic by adding comment-status() clauses to it.

**Comment by pbowen-oc** [comment]
It looks like the if() result is being treated as a string. The following expression correctly evaluates as false since the if() result is a null string:
if(false(), false(), '') or false()

**Comment by MartijnR** [comment]
* [ ] martijn to verify if this is really a bug

**Comment by MartijnR** [comment]
* [ ] try ODK Collect
* [ ] If ODK Collect does not convert params to strings, propose to change the ODK spec
* [ ] if ODK spec is changed, ask Alex to change implementation

**Comment by pbowen-oc** [comment]
Comment added to https://github.com/enketo/openrosa-xpath-evaluator/issues/124 about related issue with count-non-empty(if(true(), ${int2}, ${text3})) not passing Validate as expected in current version.

[if-function-operators-cne.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6706091/if-function-operators-cne.xml.txt)

**Comment by MartijnR** [comment]
merged!

**Comment by pbowen-oc** [comment]
@MartijnR - Has this been merged into the master branch? I don't see it.

**Comment by MartijnR** [comment]
Oops. Sorry, I forgot to push. Done now.

**Comment by pbowen-oc** [comment]
Thanks!

**Comment by pbowen-oc** [comment]
Looks good in testing.
