### ISSUE TITLE
Opening form to query not working correctly for last item on form that have image map

### ISSUE THREAD

**Issue by theywa** [OpenClinica/enketo-express-oc#495]
**Describe the bug**
When opening the query from the last item on the form that has an image map item the scroll into view query modal gets pushed to the bottom after the image map is fully loaded so the user can't see the query modal.

https://user-images.githubusercontent.com/13865076/128530634-9bbf3682-51df-472e-bc68-c7847266a375.mp4

**Comment by pbowen-oc** [comment]
Looks good in testing.
