### ISSUE TITLE
simultaneous fieldsubmissions for the same calculated field

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#501]
branch off of 2.5.6.oc-12

Add 20ms delay to  fieldsubmission.

Let Jon and Paul know when done.

**Comment by MartijnR** [comment]
I think 2.5.6.oc-12 doesn't exist in this fork. Is this deployed from @theywa 's fork?

**Comment by MartijnR** [comment]
I created a branch called `2.5.6.oc-12` (from theywa/enketo-express-oc's branch with the same name), and added the delay in an additional commit. This commit was tagged with 2.5.6.oc-13.

**Comment by pbowen-oc** [comment]
@MartijnR  - We can't find your commit. Do you have a link to it?

**Comment by pbowen-oc** [comment]
@MartijnR - Unfortunately, this does not appear to be adding a delay when we need and we are still experiencing the same issue. Our server still show the problematic requests only 3-4 ms apart and Jon's browser activity reflects the same.

When we see multiple submissions for different items on form load, they appear to be processed in a waterfall manner (independent of the new delay). Each call is shown in the browser as starting after the prior call completes. This is consistent with my understanding of what you were trying to do by adding a delay after the successful completion of a submission.

However, when we have a form with multiple submissions for the same item on load (the scenario we discussed), some devices/browsers are submitting both requests simultaneously and not waiting for the first request to finish. I don't see this behavior on my laptop (these occur in a waterfall style like the others), but Jon sees them occurring at the same time on his. We also both reproduce the symptoms (missing value saved) when we use our phones (iPhone Safari and Android Chrome).

Here is Jon's view of the original form (note the two submissions at the same time):
![1](https://user-images.githubusercontent.com/25179620/132623353-87cb871d-8af3-4701-9519-86eb2482f2f0.png)
![2](https://user-images.githubusercontent.com/25179620/132623358-30d48f82-235b-4453-9332-d69f603120e2.png)
![3](https://user-images.githubusercontent.com/25179620/132623369-10629d7a-e0a6-474a-a516-da0fe129270d.png)
![4](https://user-images.githubusercontent.com/25179620/132623376-f2c6b2cc-0849-4734-8c31-caa8f2ce7ca7.png)


On the devices that have the above problem, we also observe a bug with the following form:
[default-calc.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7133420/default-calc.xform.txt)

This item should submit back its default value first and then submit back its calculated value. On devices showing the simultaneous calls, there is only one submission for the calculated value, and the default value is not submitted at all. This seems like a different issue, but it is correlated with the same devices that show the simultaneous submissions for a single item.

**Comment by MartijnR** [comment]
Thanks. I see something interesting in the code, that may lead to understanding and fixing this. Will let you know when something is ready to test.

**Comment by MartijnR** [comment]
I was able to reproduce the issue. Instead of a targeted minimal fix, I realized it would be much easier to rewrite the queue submission logic (and greatly simplified it). 

The good news is that the issue is fixed. Everything is sequential now. The bad news is that testing for other regressions will be more important. I would focus on:

- do all values get submitted?
- is the status text on the top left of the form correct?

* [ ] if this fix is approved, make sure to add it to master too.

**Comment by pbowen-oc** [comment]
@MartijnR - It appears that the data is generally submitting, but we are having issues. The previous console logging that showed the submission queue was quite helpful for diagnosing form problems and would be useful here as well.

The main issue we are seeing now is that clicking Close or Complete is causing an error for any view except read-only.

New Form Close (submissions occurred):
![Screenshot 2021-09-10 002358](https://user-images.githubusercontent.com/25179620/132799949-4a484d80-1c34-4136-9403-4ead35feb154.png)

Complete (submissions occurred)
![Screenshot 2021-09-10 002701](https://user-images.githubusercontent.com/25179620/132799988-e9790ff8-25eb-46a9-947a-b339858e07ef.png)

Review-Only mode Close (no queries were entered so there were no submissions):
![Screenshot 2021-09-10 002501](https://user-images.githubusercontent.com/25179620/132800063-0ba31293-694c-4caf-bfec-fe0558d28a6e.png)

This is independent of form as seen on this 1 item form with no logic:
![Screenshot 2021-09-10 003816](https://user-images.githubusercontent.com/25179620/132800587-02d0cce5-1bd5-4643-b5e0-796428196a5b.png)

![Screenshot 2021-09-10 003838](https://user-images.githubusercontent.com/25179620/132800607-3514c78b-b4ea-49e9-8bb9-0475bbb6762c.png)

**Comment by MartijnR** [comment]
Thanks. Sorry about that. It is fixed now in latest commit. (Will send email about this too).

**Comment by jmcinerney** [comment]
Thanks Martijn, this is looking good now. Could you please tag this change?

**Comment by MartijnR** [comment]
Great! It is now tagged with `2.5.6.oc-14`.

**Comment by MartijnR** [comment]
* [ ] add fix to master too.

**Comment by pbowen-oc** [comment]
@MartijnR - Most cases are passing, but we are seeing a bug related to relevant logic.

Test form:
[vitals-grid-v11-small.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7163547/vitals-grid-v11-small.xml.txt)

Steps:
1. Make the group relevant.
2. Enter data into it.
3. Make the group not relevant.
4. Close the form

Expected:
The form should prompt the user to confirm adding autoqueries for the non-relevant items, submit them, and close the form.

Actual:
We're getting a submission error:
![alert-1](https://user-images.githubusercontent.com/25179620/133295824-d05ebad3-8615-4539-9938-68a9e25c7bf2.png)

In the full form we took this section from, we were also getting a related message in some cases:
![alert-2](https://user-images.githubusercontent.com/25179620/133295912-86fc0777-c2d5-4417-bd48-d8f90f98dbb2.png)

Related to this, could we get logging back for showing the contents of the queue?

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/KmTmlCrq?ecid=1

**Comment by MartijnR** [comment]
@pbowen-oc the form in the screenshots is not grid-v11-small. It looks different and I cannot reproduce the issue.

I added back logging, this time after each successful fieldsubmission (did not tag commit).

**Comment by pbowen-oc** [comment]
@MartijnR - Here is the form that matches the screenshot - [vitals-grid-v11-small version 11.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7170905/vitals-grid-v11-small.version.11.xml.txt)

I think the other version just had the form style changed to make it easier to see. My colleague reported that she observed the same behavior on both but it was easier to see without pages style in use.

Steps:
1. Open form in Edit mode
2. Select "Yes" for "Was temperature measured?" to show fields in group that have become now relevant
3. Populate Temperature and Temperature Units fields
4. Select "No" for "Was temperature measured?"
5. Close the form with relevant errors still present
6. Click Proceed when alert appears

Expected: Form closes, queries created for fields with relevant errors

Actual: Relevant errors are submitted successfully for the temperature and units (and there are no other submission calls that failed), but an error appears about unsbubmitted data.
![Screenshot 2021-09-15 100711](https://user-images.githubusercontent.com/25179620/133458275-5b3b1cf4-38bc-4c33-a744-b245cdd8153a.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/ZPj25AOK?ecid=1

**Comment by MartijnR** [comment]
@pbowen-oc, @jmcinerney the remaining issue might be fixed in commit tagged with 2.5.6.oc-16.

* [ ] add fix to master too (once confirmed)

**Comment by pbowen-oc** [comment]
I tested this quickly and it appears to work as expected. Thanks!

**Comment by pbowen-oc** [comment]
@MartijnR - This is looking good for us. Please merge it into master.
