### ISSUE TITLE
Items with triggered calculations are being cleared when their group becomes non-relevant.

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#502]
Steps:
1. Create a form with a group with relevant logic
2. Add an item to the group that has a triggered calculation but it still user editable (i.e., not read-only)
3. Edit the form
4. Enter data to make the group become relevant
5. Trigger the item in the group to be calculated
6. Make the group non-relevant

Expected:
Since the item with the triggered calculation is user-editable, it should not be cleared when the group is made non-relevant. It should keeps its value and display a relevant error message.

Actual:
The item is being cleared.

Test Form:
[v33-ml2-sm.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7163900/v33-ml2-sm.xml.txt)

Note: We have found this case, but have not done comprehensive retesting with default and triggered calculation items that are read-only and not read-only (as well as standard calculations (always read-only)). We also haven't tested with items relevant directly and items relevant through their group.

The general expectation is that read-only items are cleared when they become non-relevant, but user-editable items do not get cleared when they become non-relevant.

**Comment by pbowen-oc** [comment]
This is present in 2.5.6.oc-12.

**Comment by MartijnR** [comment]
* [ ] try to reproduce in master
* [ ] try to reproduce in the branch

**Comment by pbowen-oc** [comment]
@MartijnR - Here is a minimal form derived from the previous one:
[v33-ml2-sm2.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7172746/v33-ml2-sm2.xml.txt)

**Comment by MartijnR** [comment]
@pbowen-oc I added a non-tagged commit with a fix to the `2.5.6.oc-12` branch. Am curious if your automated testing shows a regression (with setvalue).

* [ ] if accepted fix, also add to master

**Comment by pbowen-oc** [comment]
@MartijnR - We haven't run automation yet, but my initial testing doesn't show any issues.

**Comment by pbowen-oc** [comment]
@MartijnR - This is looking good for us. Please tag it and then merge it into master.
