### ISSUE TITLE
Items with choice filters and relevant logic don't work correctly in repeating groups

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#503]
Steps:
1. Create a form with a selection item (item2) in a repeating group
2. Give the item a choice filter based on an item (item1) in the repeating group and relevant logic based on an item (item1) in the repeating group
3. Enter data into item1 in the first repeat occurrence. Observe that the item2 in the first occurrence shows appropriate options for the choice filter.
4. Add another repeat occurrence
5. Enter data info item1 in the second occurrence (a different value than was entered in occurrence 1). Observe that the item2 in the second occurrence shows appropriate options for the choice filter.

Expected:
In occurrence 1, item2 should still show the correct options based on the value of item1 in that occurrence.

Actual:
In occurrence 1, item2 shows options that match the choice filter based on values of item1 across all repeat occurrences.

Example form:
[RCFT1.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7179475/RCFT1.xml.txt)

This form takes values 1-10 in the first item and shows a choice option with the same label in the second item. The values for the first item in repeat occurrences after the first effectively bleed over into the first occurrence.
![Screenshot 2021-09-16 122423](https://user-images.githubusercontent.com/25179620/133650327-23918e6b-496e-4720-a1fc-5552fe1e7a4d.png)

Note: If the relevant logic is removed, the issue does not occur.

**Comment by pbowen-oc** [comment]
This occurs in 2.5.6.oc-12, 2.5.6.oc-16, and the latest version of master we are testing.

**Comment by MartijnR** [comment]
* [ ] test in enketo-core
* [ ] if applicable, create issue in enketo-core
* [ ] create PR in enketo-core

**Comment by MartijnR** [comment]
@pbowen-oc, it would be helpful to merge the latest enketo-express (3.x.x.) since this fix will require an enketo-core update.

**Comment by pbowen-oc** [comment]
@MartijnR - We will stay on the older version for now but can pull the fix out and use it on our older branch.

**Comment by MartijnR** [comment]
Merged in Enketo Core master now: https://github.com/enketo/enketo-core/commit/74f085c395bbbd749b99fed2165be7b461ea822f. 

For cherrypicking you could only include the changes in dom-utils.js (the rest is testing).

**Comment by pbowen-oc** [comment]
Looks good in testing.
