### ISSUE TITLE
Constraint not firing as expected in Preview mode

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#505]
Working as expected in 2.5.6.oc-17. Failing in Preview Mode (but not Edit mode) in 2.8.0-1015-gedb3b97.

Steps:
1. Open the attached form in Preview mode - [Constraint Test 1.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7256627/Constraint.Test.1.xform.txt)
2. Leave the first item blank and enter anything except 1 in the second item OR enter a value in the first item and enter any value less than 200 in the second item

Expected:
A constraint message appears on the second item.

Actual:
No constraint message appears.

This is working as expected in Edit mode.

Preview Mode:
![Screenshot 2021-09-30 001308](https://user-images.githubusercontent.com/25179620/135386768-43513b91-4ec0-40e1-8d29-f1194328bd84.png)
![Screenshot 2021-09-30 001327](https://user-images.githubusercontent.com/25179620/135386780-c5df288f-c99a-4bf7-95b2-1bea8d600bad.png)

**Comment by MartijnR** [comment]
* [ ] reproduce in enketo-express-oc
* [ ] reproduce in enketo-express

**Comment by MartijnR** [comment]
@powen-oc, could you please share a preview URL that this issue occurs on?

**Comment by pbowen-oc** [comment]
@MartijnR - I can't reproduce it now either. I don't know if that is due to the specific commit we are running now or if there was a misconfiguration on our Preview server before. In any case, it doesn't look like there's anything to fix at this point.
