### ISSUE TITLE
Decimal-date-time function behaving differently under new evaluator

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#507]
When using the old evaluator, the decimal-date-time() function produced a decimal result that reflected the user's timezone. In the new evaluator, this function is producing an integer result that appears to be disregarding timezone.

Test form:
[decimal-date-time test.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7288207/decimal-date-time.test.xform.txt)

Testing in Eastern Time with a date during EDT:
Old Evaluator (2.5.6.oc-17 tag):
![Screenshot 2021-10-05 135822](https://user-images.githubusercontent.com/25179620/136078843-78e6ace3-3cf4-42bc-a71a-89db8c9eccd1.png)

New Evaluator (2.8.0.oc branch commit b46afc503663639d97f6a77000289c27d4d326ce):
![Screenshot 2021-10-05 140102](https://user-images.githubusercontent.com/25179620/136078988-10ce891c-46fa-4e20-890e-731b56c3937a.png)

Testing in Eastern Time with a date during EST:
Old Evaluator:
![Screenshot 2021-10-05 135907](https://user-images.githubusercontent.com/25179620/136078924-63e52bd6-1446-40b0-be72-e35f81eec180.png)

New Evaluator:
![Screenshot 2021-10-05 140330](https://user-images.githubusercontent.com/25179620/136079006-3aa69fce-9050-4202-945c-edb51223bc52.png)

Testing performed in Windows Chrome. Also reported in Firefox (unknown OS).

Overall, there would be a lot of benefit to having a function like this that disregards the browser's timezone setting and treats the raw date value as UTC+0 (as it appears to be doing here). However, this change to the existing decimal-date-time() function has broken existing logic on our forms.

**Comment by pbowen-oc** [comment]
@MartijnR - I am assuming this is only related to the client timezone configuration. If you think it could be related to a server configuration and you don't see the issue yourself, please let me know.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/nfsz1eAL?ecid=1

**Comment by MartijnR** [comment]
reported issue here: https://github.com/enketo/openrosa-xpath-evaluator/issues/135

**Comment by pbowen-oc** [comment]
Looks good in testing.
