### ISSUE TITLE
Calculate item with trigger doesn't work (error in console)

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#508]
This is failing in 2.5.6.oc-17 and the 2.8.0.oc branch.

Steps:
1. Open the attached form - [Trigger on calculate item.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7296239/Trigger.on.calculate.item.xform.txt)
2. Enter a value for the date item

Expected:
The triggered calculate item evaluates and the value is displayed in the note item.

Actual:
Console error and no calculated value.
![Screenshot 2021-10-06 141518](https://user-images.githubusercontent.com/25179620/136261031-ba079cf1-e086-42fd-9fc7-a9eb2a690977.png)

![Screenshot 2021-10-06 141606](https://user-images.githubusercontent.com/25179620/136261041-aa6f7bcb-5ece-4aad-aaf4-2d4163f9366a.png)

**Comment by MartijnR** [comment]
* [ ] reproduce with latest master
* [ ] reproduce with latest enketo-core

**Comment by pbowen-oc** [comment]
Looks good in testing.
