### ISSUE TITLE
Date function behaving differently under new evaluator

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#509]
Similar to #507, but for the date() function

The old evaluator date() function returns a date with time and time zone. The new evaluator returns only a date with no time or time zone.

Test Form:
[date function test.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7325916/date.function.test.xform.txt)

Old Evaluator:
![Screenshot 2021-10-11 195917](https://user-images.githubusercontent.com/25179620/136869724-e319ea99-c824-48e1-876c-e5ffaa67e3ae.png)

New Evaluator
![Screenshot 2021-10-11 195934](https://user-images.githubusercontent.com/25179620/136869733-fd75ced2-2fe2-4e43-9d71-226f6919a793.png)

**Comment by pbowen-oc** [comment]
For integer input:
Old Evaluator:
![Screenshot 2021-11-03 145146](https://user-images.githubusercontent.com/25179620/140174469-53eab773-c94c-48ad-a12b-f928023fdd86.png)

New Evaluator:
![Screenshot 2021-11-03 145216](https://user-images.githubusercontent.com/25179620/140174451-1171442a-fd07-418f-9396-71bf66ae8f80.png)

The behavior here on the old evaluator is consistent with date functionality in general in the old evaluator (where date values include time/timezone) and so existing forms were designed for this behavior.

**Comment by MartijnR** [comment]
This commit contains a fix: https://github.com/enketo/openrosa-xpath-evaluator/pull/144/commits/5adf55fada215c3dfcf2cb7619af14541567925c  You could point to it in your enketo-core branch to start testing if desired.

Note that that PR is built on top the other already-approved but not yet merged fix (so that fix would be included).

**Comment by pbowen-oc** [comment]
Looks good in testing.
