### ISSUE TITLE
Format-date function behaving differently under new evaluator

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#510]
The format-date() function is not working consistently in the new evaluator as in the old evaluator.

Test Form:
[format-date function test2.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7326216/format-date.function.test2.xform.txt)

If an integer value is entered (such as"2003"), the new evaluator treats it like a decimal-date-time value and creates a date object based on that. The old evaluator, however, treats that same value as a simple date value (year old) and creates a date object based on that.

Old Evaluator (expected):
![Screenshot 2021-10-11 211323](https://user-images.githubusercontent.com/25179620/136876221-6298a9aa-5e18-44dd-8d34-16ebc9a985b4.png)

New Evaluator
![Screenshot 2021-10-11 211303](https://user-images.githubusercontent.com/25179620/136876218-cf5b3446-47c4-4dc8-b706-be46f870bde8.png)

Note that a value like "2003-01" produces the same result in both cases.

**Comment by MartijnR** [comment]
Oddly, I only see the old (correct) behavior where a number is cast to a date (number of days since epoch) with the new evaluator.

fwiw, the correct thing to do for "2003-01" is to fail to parse, I think (returning `""`), since there is no expectation that this is can be converted to a date

**Comment by pbowen-oc** [comment]
@MartijnR - I rechecked this and realized I mixed up the old and new behavior when posting this. The old evaluator treated "2003" as a the year 2003. I will update the description above.

**Comment by MartijnR** [comment]
Thanks. That's too bad, because I think the old behavior was a bug.

* [ ] check what ODK Collect does

**Comment by pbowen-oc** [comment]
We decided to keep the new behavior here to help standardize the behavior.
