### ISSUE TITLE
Choice with dynamic labels and choice filters not working

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#511]
Present in 2.5.6.oc-17 and 2.8.0.oc branch. Possibly related to #503 but not tested with that code yet.

Steps:
1. Add the attached form to a study and publish it - [Dynamic Label Choice Filter bug.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7362102/Dynamic.Label.Choice.Filter.bug.xform.txt)
2. Open the form in edit mode
3. Enter a value for specimen ID (such as "abc")

Expected:
The first radio button below the repeat should display "#" and then the value entered (such as "#abc").

Actual:
The radio button just displays "#".

![Screenshot 2021-10-18 010918](https://user-images.githubusercontent.com/25179620/137675834-de7d1207-b90b-475a-9a7a-3e98076501cf.png)

Add correct screenshot with "def" in second repeat.
![Screenshot 2021-10-18 011001](https://user-images.githubusercontent.com/25179620/137675855-9b32eecd-9284-4e79-892e-ee6ac7aa9c84.png)

Steps:
3. Add a second repeat. Note that the radio button for the first repeat now displays the expected label.
4. Enter a value for specimen ID in the second repeat (such as "def")

Expected:
The second radio button for the second repeat should be populated with correct label (such as "#def").

Actual:
The radio button has the label "#". Unlike for the first repeat, even if another repeat is added, this label does not get updated to the correct form.

**Comment by MartijnR** [comment]
dev notes:
* branch `fix/temp-oc-511` in enketo-core
* remaining issue is that the outputs in repeats don't update when the referenced value changes. This is probably a wider issue with outputs, not related to itemsets specifically.

**Comment by MartijnR** [comment]
PR https://github.com/enketo/enketo-core/pull/846

**Comment by pbowen-oc** [comment]
Looks good in testing.
