### ISSUE TITLE
Date arithmetic results in different data type in new evaluator

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#516]
The old evaluator returned a numeric value for date + integer. The new evaluator returns a date value for the same expression.

[date plus zero.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/7457812/date.plus.zero.xform.txt)

Old Evaluator:
![Screenshot 2021-11-02 001304](https://user-images.githubusercontent.com/25179620/139786232-ea6b1e59-7119-464a-aad2-13bd61bfd471.png)

New Evaluator:
![Screenshot 2021-11-02 001317](https://user-images.githubusercontent.com/25179620/139786239-764973b8-3d8d-4a33-9ac0-109ab8adac85.png)

**Comment by MartijnR** [comment]
* [ ] check what ODK Collect does

**Comment by pbowen-oc** [comment]
We observed the same discrepancy with date1 - date2. In the old evaluator, it returns the number of days between the dates. In the new evaluator it returns a nonsensical date. I'll add a test form and screenshots for this scenario.

**Comment by MartijnR** [comment]
Thanks. Makes sense that for similar dates, it would return a value a short time after 1-1-1970. Will add that.

* [ ] add additional example for same bug

**Comment by MartijnR** [comment]
There is a PR for this! Things seem to be a little quiet in Enketo Dev world at the moment, so if eager you could perhaps deploy that PR branch for testing.

**Comment by pbowen-oc** [comment]
We are seeing an issue with this. Date1 - Date2 is now producing a number, but not exactly as expected. October 10, 2021 - October 1, 2021 is producing 9.208 days (9 days and 5 hours) rather than 9 days as the old evaluator did. It looks like the timezone is being factored in somehow, but only for one of the dates.

I'll add an example form and screenshots a little later.

**Comment by pbowen-oc** [comment]
@MartijnR - Here is an example for the issue in my last comment:

Test form:
[date-subtract-date-sm.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/7864726/date-subtract-date-sm.xml.txt)

Screenshot (legacy on left, new evaluator on right):
![Screenshot 2022-01-13 122601](https://user-images.githubusercontent.com/25179620/149379202-32275521-9aa0-4122-8505-23d4e3dbad94.png)

**Comment by MartijnR** [comment]
https://github.com/enketo/openrosa-xpath-evaluator/issues/146

**Comment by MartijnR** [comment]
I created a fix PR. I'll update the other outstanding [PR 144](https://github.com/enketo/openrosa-xpath-evaluator/pull/144) so you can start testing with it.

**Comment by MartijnR** [comment]
Here it is: https://github.com/enketo/openrosa-xpath-evaluator/pull/148. Please remind me to mark that PR as final if your testing finds no issues.

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks!

**Comment by MartijnR** [comment]
There is a discussion about what the behavior should be when arithmetic exceeds DST boundaries though...

**Comment by pbowen-oc** [comment]
For us, we don't expect values with erroneous timezones or two values with different timezones (other than DST vs ST) so I don't think the implementation would matter (unless I am missing the implication).

The testing looks good so far. We're continuing, but this is likely done and ready to have a final PR.

**Comment by pbowen-oc** [comment]
Looks good in testing.
