### ISSUE TITLE
The query view is truncated when viewing query from query table 

### ISSUE THREAD

**Issue by theywa** [OpenClinica/enketo-express-oc#518]
**To Reproduce**
When the user clicks the view query from the query table, the query window position appears truncated from the bottom and does not show complete query history. When the user closes the query and opens it again, the query window positions itself correctly
[OC-16450](https://jira.openclinica.com/browse/OC-16450)

**Screenshots**
![screenshot-1](https://user-images.githubusercontent.com/13865076/140318581-6dabda07-8e7e-485a-bd8a-a324035913ef.png)

**Comment by theywa** [comment]
@MartijnR, @pbowen-oc  ~ CMIIW,  I assume this is another timing issue. In this case, the height of the query widget is longer than the page, and when the auto-scrolling to the linked question happens the query widget is (might be)not fully loaded so the scroll position is stuck at the (original)end of the page. I create a PR that added a delay to fix the issue.

**Comment by pbowen-oc** [comment]
Looks good in testing.
