### ISSUE TITLE
UI Language not switching immediately

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#531]
@MartijnR - I have a question and an issue to report. I am using version 2.8.0.oc-9.

2. When opening a multi-language form (such as this one: [language test2.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/8065941/language.test2.xml.txt) ) it opens with the form content and UI synced as expected. However, when I change to a different language using the language selector, the form content changes as expected but the UI remains on the old language. If I change the language selector again, the form content changes as expected, but the UI changes to the previous selection. In other words, after initial load, the UI is always out of sync with the form content/selector (specifically, it is on the previous language selection).

Form first opened (languages synced):
![Screenshot 2022-02-14 234019](https://user-images.githubusercontent.com/25179620/153996037-6c7626f2-2c56-4077-be71-c82ad2136664.png)

Language changed (UI has not changed):
![Screenshot 2022-02-14 234037](https://user-images.githubusercontent.com/25179620/153996052-83153c3c-1ff1-4130-8ecc-dad5826a1780.png)

Language changed (UI has changed, but to the previous selection):
![Screenshot 2022-02-14 234105](https://user-images.githubusercontent.com/25179620/153996072-f4004527-1d0b-47b1-abbb-0f6ed180172d.png)

_Originally posted by @pbowen-oc in https://github.com/OpenClinica/enketo-express-oc/issues/95#issuecomment-1039862760_

**Comment by MartijnR** [comment]
Can reproduce in master with http://localhost:8005/single/fs/i/Q93yp13x?ecid=1. Cannot reproduce in enketo/enketo-express

**Comment by pbowen-oc** [comment]
Looks good in testing.
