### ISSUE TITLE
Update Submission Error message for Anonymous forms

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#533]
**Is your feature request related to a problem? Please describe.**
When the submission fails due to an error response from the server, we would like to replace the existing error message. Please see attachment for current error message.

**Describe the solution you'd like**
New error message: "There was a problem with your submission. Please try again or contact the Study Team if this persists."

**Describe alternatives you've considered**
N/A

**Additional context**
Related to #253 

![Error_message_Enketo](https://user-images.githubusercontent.com/87195434/157313992-2798c653-a240-4675-a5b7-a4bf6737d6c3.png)

**Comment by MartijnR** [comment]
* [ ] check if translation-additions.json can overwrite strings in translation.json
* [ ] change string

**Comment by Apotischman** [comment]
This has been tested and can be closed.
