### ISSUE TITLE
Strict Constraint not being respected in Form

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#535]
**Describe the bug**
When a user enters a value that violates a constraint, the form allows the value.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Load a form that has an item which has a constraint-type = strict
2. Enter a value that violates the constraint
3. Notice the error in the console
4. 

**Expected behavior**
The value should be rejected and there should be a pop-up box with an error message

**Screenshots**
XForm
[XForm_Constraints_not_respected.txt](https://github.com/OpenClinica/enketo-express-oc/files/8255760/XForm_Constraints_not_respected.txt)

Console
![Constraint_missing_console_error_image](https://user-images.githubusercontent.com/87195434/158435653-d768d51e-7cd3-458e-b009-8b14f93824df.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/gVc0J3UZ?ecid=a

**Comment by Apotischman** [comment]
This has passed testing.

**Comment by Apotischman** [comment]
Based on testing, all strict/non-strict constraints, required fields and relevant logic is working correctly.
