### ISSUE TITLE
Export Button not working

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#536]
**Describe the bug**
When a record is queued for submission, clicking the Export button does not do anything, nor does it update the console/network tabs within developer tools.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Ensure that the computer is not connected to the internet
2. Load a form that has been cached
3. Open the developer tools
4. Fill out the form
5. Click close or save draft
6. Open Queue side window
7. Notice that there should be a form queued
8. Click Export Button
9. Notice that nothing is exported
10. Notice that clicking the Export button does not update the Network or Console tabs

**Expected behavior**
The form should be exported

**Screenshots**
![Export_not_working](https://user-images.githubusercontent.com/87195434/158442813-15a469a4-b17c-4862-b34b-2adcb5fe3d7a.png)

**Comment by MartijnR** [comment]
* [ ] reproducible in ee?
* [ ]

**Comment by Apotischman** [comment]
Export is now working, based on Testing.
