### ISSUE TITLE
required not working in offline-capable views

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#537]

**Comment by MartijnR** [comment]
and constraint also not?

**Comment by pbowen-oc** [comment]
We'd like constraint, required, and relevant to be treated as standard errors and prevent submission.

**Comment by MartijnR** [comment]
http://localhost:8005/x/full/participant/10dc8d2efaa47e7feade75db34923dc0?ecid=a

**Comment by MartijnR** [comment]
I'm deducing that strictViolations do not need to be considered upon submit in the anonymous Participate views. Please let me know if that is not correct.

**Comment by pbowen-oc** [comment]
@MartijnR - My last comment was probably misleading. If an item has a strict constraint or required in the XForm, we want it to be treated as strict. We don't want the form engine to automatically treat any standard constraint or required checks as strict.

**Comment by MartijnR** [comment]
Thanks. They'll still be treated differently, I think, but upon Submit there is no difference between strict and non-strict if I understand correctly.

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks, that makes sense.

I don't think we discussed this explicitly, but if offline mode would be able to add autoqueries, then we'd want to allow that for non-strict constraint and required. We don't have a strong requirement to support that and I'm assuming that is not implemented now, so tat would mean strict and not strict should all work the same way: block submission.

**Comment by Apotischman** [comment]
Non-Strict Constraint should prevent the user from being able to submit
![image](https://user-images.githubusercontent.com/87195434/162279901-3e7b997a-65a5-4acc-a8f8-91ffdef3b3db.png)

Xform: 
[Offline_Not_Strict.txt](https://github.com/OpenClinica/enketo-express-oc/files/8445867/Offline_Not_Strict.txt)


Required Items should prevent the user from being able to submit if they are not filled out
XForm: 
[Offline_Required.txt](https://github.com/OpenClinica/enketo-express-oc/files/8445870/Offline_Required.txt)

**Comment by MartijnR** [comment]
see email "#537 - Required & Constraints" on 4/7 for live links

**Comment by MartijnR** [comment]
I've concluded you're not using the latest javascript code. I cannot reproduce these issues.

The cause is likely this: https://github.com/OpenClinica/enketo-express-oc/issues/543#issuecomment-1083546389

**Comment by Apotischman** [comment]
Based on testing, all strict/non-strict constraints, required fields and relevant logic is working correctly.
