### ISSUE TITLE
offline-capable view not working offline

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#540]
navigator.serviceWorker.controller is null

It looks like the problem with the version number not showing in the sidebar may be an indication that the app is not actually offline-capable.

To investigate.

**Comment by MartijnR** [comment]
Looks like the serviceWorker scope needs to be changed from /x/ to /full/participant/x/

**Comment by MartijnR** [comment]
I needed to change the Enketo webform URL for the new anonymous participate views. The API is unchanged and will return the new URLs.

**Comment by MartijnR** [comment]
still todo:

* [ ] does the HTML page itself update correctly (when e.g. HTML syntax changes and Enketo is rebuilt)?

**Comment by pbowen-oc** [comment]
Thanks! We hadn't gone into full testing yet to catch this so this early catch definitely helps!

**Comment by Apotischman** [comment]
Based on testing, this is now working.
