### ISSUE TITLE
"Save Draft" button on every page - Offline Mode only

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#544]
**Is your feature request related to a problem? Please describe.**
The user should be able to click the "Save Draft" button on every page. Currently they are only on the last page.

**Describe the solution you'd like**
The "Save Draft" button should be on every page with the current functionality.

**Describe alternatives you've considered**
N/A

**Additional context**

2nd to last page
![image](https://user-images.githubusercontent.com/87195434/161265517-c5ebc755-1276-4785-8b52-0c052350e450.png)

Last page
![image](https://user-images.githubusercontent.com/87195434/161265578-2e738d7c-9c37-484e-8b73-f580c1a0a739.png)

**Comment by pbowen-oc** [comment]
@MartijnR - I updated the description to note that only the Save Draft button would be on every page and it would maintain the current functionality of Save Draft.

**Comment by MartijnR** [comment]
http://localhost:8005/x/full/participant/0f40ff9f4da575c6007c42748e697bf0?ecid=a

**Comment by Apotischman** [comment]
This has been tested and can be marked as complete.
