### ISSUE TITLE
Nested group with relevant logic not letting form be completed unless the group is relevant

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#547]
Steps:
1. Open this form with a nested group with relevant logic -
[relevant nested group.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/8461136/relevant.nested.group.xml.txt)
2. Enter a value in the first item
3. Click the complete button and select Confirm

Expected:
The form should be completed since there are no edit checks active.

Actual:
The form shows an error message that errors need to be resolved. There are no errors visible in the UI (and shouldn't be any not visible since there are no checks on the form.

![Screenshot 2022-04-11 005621](https://user-images.githubusercontent.com/25179620/162667783-14bb674e-9ee1-469b-a4fc-cd463230f75e.png)
 
Note: Exposing the nested group by making a selection for the second item prevents the above error.

This is a new issue since 2.8.0.oc-9.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/QZgccFyR?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
