### ISSUE TITLE
Unable to upload file larger than 10MB

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#548]
**Describe the bug**
We are normally able to upload files that are a little less than 100MB. Right now, we are only able to upload files that are less than 10MB

**To Reproduce**

1. Access the URL of an Offline Form that contains a file upload field
2. Select a file larger than 10MB
3. Click Submit
![Upload_Error](https://user-images.githubusercontent.com/87195434/162786038-12fa5de0-7fc1-47e1-a547-8781b6e4ed00.png)

XForm:
[XForm_File_Upload.txt](https://github.com/OpenClinica/enketo-express-oc/files/8466024/XForm_File_Upload.txt)

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by pbowen-oc** [comment]
@MartijnR - This is observed with all of our form views, not just the offline view.

**Comment by MartijnR** [comment]
http://localhost:8005/single/full/participant/f52f9376520cce0d021c16e9ced949804c6ba90f207456800db039552db9b237?ecid=1

**Comment by MartijnR** [comment]
Afaik there is no issue on the Enketo side with files > 10Mb. Best to investigate what happens on OC side.

**Comment by pbowen-oc** [comment]
@Apotischman - The 413 (payload too large) error indicates the payload is too large. This would be on the OC side.
