### ISSUE TITLE
Update Alert Message to Refresh Screen

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#549]
**Is your feature request related to a problem? Please describe.**
If a user access an Offline Form for the first time, they will receive a notification in the top ribbon of the browser. It will automatically close after 20 seconds.

**Describe the solution you'd like**
The notification should only close when the user closes it, as opposed to automatically closing. We are unsure the difference between the 2 attached notifications:
"A new version of this form has been downloaded. Refresh this page to load the updated version."
"A new version of this application has been downloaded. Refresh this page to load the updated version."

**Additional context**
![New_Version_notification](https://user-images.githubusercontent.com/87195434/162796509-8c4163ad-e0b0-4436-8953-e08114377909.png)

![Mobile_notification](https://user-images.githubusercontent.com/87195434/162796667-db06b5b3-2983-4e18-a3af-6837d807079f.png)

**Comment by MartijnR** [comment]
The application is the software. The form is just the form that's loaded into the software.

When you change something in the form (in the XLSform) you'll see the second message. If we fix a bug or add a feature to Enketo, it's the application itself that is updated.


* [ ] remove auto-closing functionality of the app-update alert
* [ ] remove auto-closing functionality of the form-update alert

**Comment by MartijnR** [comment]
I should add that the bar is meant for mobile devices (non-touch screens), and the modal for non-mobile (touch screen) devices . Both messages should appears in either the bar or the modal dialog on a particular device (not a mix). We can change that too if you wish.

**Comment by Apotischman** [comment]
I think the modal and non-modal are fine. The messages disappear after 20 seconds or so, and we'd like to force the user to click "OK" or the "X" as opposed to a countdown that automatically closes the message.

**Comment by Apotischman** [comment]
This has been updated and confirmed.
