### ISSUE TITLE
Embedded images not appearing after submission in Offline mode

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#553]
**Describe the bug**
After a user submits a form in offline mode, the embedded image disappears. 

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

XForm: 
[XForm_ImageTest.txt](https://github.com/OpenClinica/enketo-express-oc/files/8513752/XForm_ImageTest.txt)

1. Go to Offline URL
2. Fill out form
3. Click submit
4. Notice the embedded image disappears

**Expected behavior**
The image should persist

**Screenshots**
Before and after submission
![Before_After](https://user-images.githubusercontent.com/87195434/164024811-92a96be3-d1f3-426c-bd3c-e1bef1fcbaff.png)

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by MartijnR** [comment]
http://localhost:8005/x/full/participant/9c4e3730b579618300560a13971d7f2e?ecid=1

**Comment by Apotischman** [comment]
Fixed based on recent testing
