### ISSUE TITLE
Upload button disabled erroneously for offline

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#554]
**Describe the bug**
Upload button is disabled even though a user has queued forms and is online

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

https://user-images.githubusercontent.com/87195434/164253886-14f1034b-7869-426f-85fd-631047d4528b.mp4

1. Cache the offline form
2. Disconnect the device from the internet
3. Load the cached form
4. Fill out the form and submit
5. Open the side panel and notice that the form is queued and the Upload button is disabled
6. Connect the device to the internet
7. Open the side panel and notice that the form is queued and the Upload button is still disabled

**Expected behavior**
A user should be able to try to Upload the forms on demand when connected to the internet

**Screenshots**

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by Apotischman** [comment]
Definitely related (if not exactly the same) as enketo#43

**Comment by MartijnR** [comment]
Time to fix it after 4 years! :D

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-express/pull/410

**Comment by MartijnR** [comment]
* [ ] in fork, the warning dialog is not shown when clicking upload when offline

**Comment by Apotischman** [comment]
Based on testing, this can be completed.
