### ISSUE TITLE
Bold is bolding all words instead of designated words

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#556]
**Describe the bug**
When bolding some words, all of the words get bolded as opposed to the intended ones.

**To Reproduce**
[Bold_issue_Xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/8542816/Bold_issue_Xform.txt)

**Expected behavior**
Only the intended words should get bolded. Also

**Screenshots**
Correct:
<img width="1139" alt="bold-note_correct" src="https://user-images.githubusercontent.com/87195434/164765336-47586793-b197-4152-a078-5c2509731bc3.png">

Incorrect:
<img width="1158" alt="bold-note_incorrect" src="https://user-images.githubusercontent.com/87195434/164765348-ee414f98-09dc-4577-830f-33c161799db7.png">

**Comment by MartijnR** [comment]
* [x] reproduce in fork - yes
* [ ] reproduce in enketo-transformer

**Comment by Apotischman** [comment]
This is now working, based on testing.
