### ISSUE TITLE
"Save Draft" button missing on all Offline Pages

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#558]
**Describe the bug**
"Save Draft" button missing on all Offline Pages

**To Reproduce**
1: Open an offline form
2: Notice the "Save Draft" button is not available

**Expected behavior**
Save Draft button is available

**Screenshots**
![Save_Draft_Missing](https://user-images.githubusercontent.com/87195434/165581282-71aec8cd-2a96-47f5-aabe-d692f24a6abd.png)

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by MartijnR** [comment]
multi-page, Grid theme: http://localhost:8005/x/full/participant/0f40ff9f4da575c6007c42748e697bf0?ecid=a
single page, OC theme: http://localhost:8005/x/full/participant/10dc8d2efaa47e7feade75db34923dc0?ecid=a

**Comment by MartijnR** [comment]
I can only reproduce this issue by changing the Enketo config to ` "disable save as draft": true,`

My best guess is that somehow your Enketo configuration changed. If that's not it, please send a live link with this issue so I can see if the HTML for that button is missing. If it is not missing it would be some CSS (build) issue perhaps, but that is very unlikely.

**Comment by pbowen-oc** [comment]
It looks like this is working for us now, so it may have been a build issue. We'll test further to see.

**Comment by Apotischman** [comment]
The Save Draft button is missing again.

**Comment by MartijnR** [comment]
Thanks for sending the form @Apotischman.

I confirmed that the HTML for the button is missing. This can have only one reason and it's the Enketo configuration.

**Comment by pbowen-oc** [comment]
This was a build issue on our end
