### ISSUE TITLE
Failed to Fetch error when external file is missing

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#560]
**Describe the bug**
When loading a form that is missing an external list, the form will not load altogether.

**To Reproduce**

![failed_to_fetch](https://user-images.githubusercontent.com/87195434/165827855-4a626a57-8ef3-4579-8f72-dcb8696e469e.png)

[External_Items.txt](https://github.com/OpenClinica/enketo-express-oc/files/8585657/External_Items.txt)

This was missing: src="jr://file-csv/medication_list.csv"/>

**Expected behavior**
The form should load, but should also display the following error
![hold_on_a_second](https://user-images.githubusercontent.com/87195434/165829961-b351a57c-62d7-4749-afd5-387ed1305c93.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/38Pcgl3b?ecid=1

**Comment by MartijnR** [comment]
Created issue https://github.com/enketo/enketo-express/issues/422

* [ ] create PR for fix

**Comment by MartijnR** [comment]
@Apotischman, @pbowen-oc If I remember correctly OC just always wants to show the errors for missing data in all form views (including previews), but load the forms themselves. The only difference between the non-preview and preview views is that non-preview views should remove the submit buttons for serious errors like these. Is that correct?

**Comment by pbowen-oc** [comment]
@MartijnR - When a form fails to load properly such as due to a missing/invalid external instance, we show a different message where "Saving..." would be displayed (it is something like "Saving disabled") and remove the Close/Complete buttons.

**Comment by MartijnR** [comment]
Ah yes, thanks!

**Comment by Apotischman** [comment]
This can be closed due to successful testing post deployment.
