### ISSUE TITLE
Embedded video on mobile device fails

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#563]
For iOS and Android: If you cache a form that includes an embedded video, and refresh the screen before the video is done loading, the video will always show a broken link. 

Open a browser tab on your mobile device
Enter the URL, click enter
Click "Let's Go"
Before the video is done caching. refresh the screen
Notice that the video will not load

This was only tested because the "Refresh" message appeared. I will test my browser again to see whether or not the issue occurs when the browser has already accessed the latest version.

**Comment by MartijnR** [comment]
* [ ] test with the enketo URL directly (not the 'Let's Go button)
* [ ] is it a browser 'feature'? If so, we probably cannot do anything.

**Comment by MartijnR** [comment]
Could somebody please test if they can reproduce the issue with this page? https://codepen.io/MartijnR/full/vqqrqv

(This will eliminate anything to with Enketo)

**Comment by Apotischman** [comment]
Is there another website you can provide that we can test?

**Comment by pbowen-oc** [comment]
@MartijnR - I also can't interrupt this while it is loading. In trying to reproduce this several times and clearing my iPad Safari cache in between, I see that codepen.io only has 2.2 MB of data stored on my device after fully loading this page.

I also reproduce it trivially with the "hotsauce" form that Ariel sent. I simply started loading the form and refresh before the video is loaded. It appears that it is attempting to read the video from cache even though it isn't there on subsequent loads. We are attempting to get the browser network calls to verify this.

**Comment by MartijnR** [comment]
dev console screenshots sent by email on 5/5/22 ("RE: 563").


<img width="330" alt="Screen Shot 2022-05-06 at 1 48 37 PM" src="https://user-images.githubusercontent.com/627350/167188040-3bcffa72-fb01-4bcd-9f13-fdd801d90dfc.png">

> It appears that it is attempting to read the video from cache even though it isn't there on subsequent loads.

It looks like that is correct.

**Comment by MartijnR** [comment]
* [ ] try to reproduce on desktop, e..g by throttling connection

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-express/issues/419
