### ISSUE TITLE
Form with signature widget opens canvas in wrong position on iPhones

### ISSUE THREAD

**Issue by theywa** [OpenClinica/enketo-express-oc#577]
[OC-18128](https://jira.openclinica.com/browse/OC-18128)

1. Using Safari on an iPhone, open a form containing a signature widget and another item (such as this one -  
[Signature.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/8853252/Signature.xml.txt)
). The form needs to be opened via Participate or directly from the Participant Matrix (not from the PDP or as a PublicURL form).
2. In the form, tap to edit the signature. Note that the signature canvas opens as an overlay above the form. It is at the top of the screen and the left arrow "return to form" button is visible directly above the signature canvas:
![Image from iOS (2)](https://user-images.githubusercontent.com/13865076/172382625-343c5bd2-5232-4d19-a7aa-7793d7ec0eed.png)
3. Tap the left arrow to return to the form.
4. Tap to focus on the non-signature item.
5. Tap out and tap to edit the signature.

Expected:
The signature canvas opens as in Step 2 above with the left arrow to return to the form visible.

Actual:
The signature canvas opens scrolled up too high such that the left arrow is off the top of the screen.
![Image from iOS (3)](https://user-images.githubusercontent.com/13865076/172382806-eedc139c-7111-4c7e-ac4e-b502368077a6.png)

Hi @MartijnR ~ I think this issue happens because pinch-zoom is automatically triggered when tapping on the input text in (step 4) that's why the position of the left arrow is off the screen. Or if the user manually does pinch-zoom and then opens the signature item, the issue also happen. Only in the iframe website that opened in the mobile browser does not happen in mobile view.

I tried using scrollIntoView, scrollTop, and update viewPort content like this(override the enable method in draw-widget) 

````
        if ( this.props.touch && this.$widget.is( '.full-screen' ) )  {  
             that.$widget[ 0 ].scrollIntoView( true );
             that.$widget.find( '.hide-canvas-btn' )[ 0 ].scrollIntoView( true );
             document.body.scrollTop = 0;
             that.$widget.find( '.hide-canvas-btn' )[ 0 ].scrollTop = 0;
             const viewportmeta = document.querySelector('meta[name=viewport]');
             viewportmeta.setAttribute('content', "width=device-width, initial-scale=0, minimum-scale=0, maximum-scale=0");
	     window.parent.scrollTo({
	         top: 0,
		 behavior: 'auto'
	     });
        }
````

but not work in safari IOS. 
this line 
````
 that.$widget.find( '.hide-canvas-btn' )[ 0 ].scrollIntoView( true );
````
is working in android chrome
I also found a similar issue https://github.com/enketo/enketo-core/issues/626
Do you have any thoughts or suggestions or workaround that you might think can fix this issue?
Thanks in advance

**Comment by MartijnR** [comment]
> Only in the iframe website that opened in the mobile browser does not happen in mobile view.

Just to clarify, this only happens when the survey is inside an iframe, right? You cannot reproduce with https://enke.to/widgets, right?

**Comment by MartijnR** [comment]
cannot reproduce on iPad with example form above and http://192.168.68.101:8005/dev?iframe=http://192.168.68.101:8005/single/fs/i/9y8ge9GQ?ecid=1

**Comment by theywa** [comment]
> > Only in the iframe website that opened in the mobile browser does not happen in mobile view.
> 
> Just to clarify, this only happens when the survey is inside an iframe, right? You cannot reproduce with https://enke.to/widgets, right?
> 
> https://stackoverflow.com/questions/45235739/iframe-scrolling-issue-in-ios (no solution)

yes, that is correct

**Comment by theywa** [comment]
> I cannot reproduce on iPad with example form above and http://192.168.68.101:8005/dev?iframe=http://192.168.68.101:8005/single/fs/i/9y8ge9GQ?ecid=1
> 
> @theywa, this fork has a special dev page to mimic the iframe parentwindow used in OC. Here are the styles used: https://github.com/OpenClinica/enketo-express-oc/blob/master/app/views/surveys/dev.pug. You can load a form like this: http://localhost:8005/dev?iframe=http://localhost:8005/single/fs/i/aaaaaaaa.
> 
> Are you able to reproduce the issue on your iPhone like this? If not, that may lead to a solution (in the parent window css rules). If you can can you please send me the local URL you use (maybe it's not single/fs/i)?

@MartijnR ~ I'm sorry to bother you, I also can't reproduce it on local. You are right this issue in parent window css, I tried adding 
>  position: fixed;
on the iframe tag and that line seems fixed the issue, do you think that would cause any problem in future?
Also thank you for the information about the how to debug enketo-express in iframe, I'll use it for future similar issue. And because this issue not on enketo-express-oc side, should we close this issue?

**Comment by MartijnR** [comment]
> n the iframe tag and that line seems to fix the issue, do you think that would cause any problem in the future?

Not sure. If it works with a long form and a short form on both desktop and mobile, it seems safe.

Interestingly, the dev page in enketo-express doesn't seem to have this CSS rule.

> about how to debug enketo-express in an iframe, I'll use it for future similar issues

Yes, me too. I had totally forgotten about it until yesterday!

> should we close this issue?

Yes
