### ISSUE TITLE
Signature item handling

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#581]
An item with the bind::oc:external value ‘signature’, will have one possible response. When this response is checked, it must: 

1. Evaluate the form for errors as if the Complete button has been clicked. If there are errors, display the standard message blocking the user from completing the form
2. If the form is valid, make a call that the item has been checked

On the OC side this causes a dialog to appear, which can be cancelled, if that occurs OC may notify enketo the user is returning to the form, in this case when the user is returned to the form enketo unchecks the checkbox item. Ideally this should trigger any logic associated with that item.

**Comment by MartijnR** [comment]
Do not submit data if the value is "signature".

**Comment by MartijnR** [comment]
Enketo checks whether it is a single-option select_multiple

Add validation in Enketo Validate?

**Comment by MartijnR** [comment]
If Enketo doesn't receive a 'receive and modal opened' message within a certain time, it should show something to the user and perhaps uncheck the question?

**Comment by MartijnR** [comment]
events:

* **signature-request**: Enketo sends this to the parentWindow to trigger the signature dialog
* **signature-request-received**: OC sends back to Enketo to indicate the message was received and a dialog is shown
* **signature-request-failed: OC sends back to Enketo to indicate that something went wrong (e.g. user clicked close on dialog)

**Comment by MartijnR** [comment]
* [ ] publish new version of Enketo Validate (haven't done in case XForm syntax is still going to change)

**Comment by malcjackson** [comment]
Hi Martijn,

Our developer has been working on this on our end and we are running into an issue where the error modal indicating no response was received after the signature item is checked displays 100% of the time. To aid in troubleshooting we were wondering if you could take a look and see if there's anything obviously wrong. Here is an image of the code in our UI to check for this: 
![image](https://user-images.githubusercontent.com/59966090/189431520-86a60236-ac52-4b3c-905f-1012b85c495f.png)

**Comment by MartijnR** [comment]
@malcjackson, I'm guessing there may be multiple iframes on the page you are developing. In that case `document.querySelector('iframe')` will only select the first `iframe` which may not be the one containing the Enketo Form.

If that's not the issue, can you confirm if you receive the `signature-request` message from the Enketo form?

**Comment by malcjackson** [comment]
Thanks @MartijnR , the developer checked and has this response: "There are not multiple iframes on the page. I tried even giving a unique id to iframe, and then posting message "signature-request-received" to that iframe but that didn't work also"

**Comment by malcjackson** [comment]
Thanks @MartijnR 

1. We are receiving it
2. That is correct
3. There is an error in the console but it appears when the form is opened, before the item is checked. Nothing new appears in the console after the item is checked:
![image](https://user-images.githubusercontent.com/59966090/191272537-70de7279-5a14-4d8a-8d4d-0367372f8a55.png)

Here is the network tab after clicking the item, nothing sticks out here:
![image](https://user-images.githubusercontent.com/59966090/191272880-bcfbf67c-58ce-4068-a40f-451696fc0499.png)

**Comment by MartijnR** [comment]
Thank you!

I think the issue is with the second argument (targetOrigin) of postMessage (on the OC side). You could quickly confirm that by changing `location.href` to `'*'` (see https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). 

If that fixes it we need to change the **unsafe** `'*'` to the target which is the URL of the Enketo form. You may have to play around with that a bit.

**Comment by MartijnR** [comment]
Martijn to look into why timeout is not cleared when signature-request-failed is received from OC

**Comment by malcjackson** [comment]
@MartijnR @pbowen-oc in the case of {event: 'signature-request-failed'}, could we update this to not show a message, and simply uncheck the box?

Alternatively, is there an approach we can take on our end (e.g. make a different response) that would result in the box getting unchecked, but no additional dialog appearing?

**Comment by pbowen-oc** [comment]
Looks good in testing
