### ISSUE TITLE
Navigation and Close buttons misaligned on Completed forms

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#593]
When opening a form that is already complete (i.e., no Complete button displayed), the bottom Next and Back Navigation buttons are misaligned. Also, the Close button is missing from page 1 (of a two page form)

Page 1:
![Screenshot 2022-09-14 152727](https://user-images.githubusercontent.com/25179620/190248046-2233adf7-86f0-4820-b140-8fc14fea9ddd.png)

Page 2:
![Screenshot 2022-09-14 152701](https://user-images.githubusercontent.com/25179620/190248082-11cd1abf-af29-4162-9d6a-6c9951c70967.png)

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=RequiredItem&ecid=1&instance_id=a&instance=<data xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"   xmlns:enk=\"http://enketo.org/xforms\" ><MHX enk:last-used-ordinal=\"1\"  enk:ordinal=\"1\" ><diagnosis>Diag</diagnosis><rating></rating><diagnosis_comment>{\"queries\":[],\"logs\":[{\"type\":\"audit\",\"message\":\"Value changed from \\\"\\\" to \\\"Diag\\\"\",\"user\":\"root\",\"date_time\":\"2021-04-10 12:35:44.317 -04:00\"}]}</diagnosis_comment><rating_comment></rating_comment></MHX><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></data>" http://localhost:8005/oc/api/v1/instance/edit
```

**Comment by MartijnR** [comment]
@pbowen-oc, could you please share the webform URL (path only is fine) so I can be sure I am looking at the right view?

**Comment by pbowen-oc** [comment]
@MartijnR - This is still occurring. The URL this form is using is /edit/fs/rfc/c/i/

XForm (not minimized)
[demoform.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/10739617/demoform.xform.txt)

Note that the buttons looks correct to me for this form using /single/fs/c/i/ and /edit/fs/dn/c/i/

**Comment by MartijnR** [comment]
```bash
curl --user changed: -d "server_url=https://enketo-aggregate.appspot.com&form_id=vitals&instance=<demo-vitals-grid-v9 xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"><page1><temp_yn>1</temp_yn></page1></demo-vitals-grid-v9>&instance_id=someUUID&ecid=a&instance_attachments[test.jpg]=http://www.kobotoolbox.org/sites/toolbox/themes/Rise_sub/logo.png" http://localhost:8005/oc/api/v1/instance/edit/rfc
```

**Comment by pbowen-oc** [comment]
Looks good in testing
