### ISSUE TITLE
Month Defaulting for YYYY/MM field

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#599]
**Describe the bug**
When a user selects just the year and clicks tab, it defaults to the year specified, and "01". We are expecting the field to automatically clear if the user tabs out of the field before entering in the month.
[Date_Only.txt](https://github.com/OpenClinica/enketo-express-oc/files/9964398/Date_Only.txt)

**To Reproduce**

[Date_Only.txt](https://github.com/OpenClinica/enketo-express-oc/files/9964399/Date_Only.txt)

**Comment by MartijnR** [comment]
Looks like an issue in the 'bootstrap-datepicker' library we're using (forceParse = false). This may make it hard to fix. Tbc

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/943

**Comment by MartijnR** [comment]
pending internal PR: https://github.com/OpenClinica/enketo-express-oc/pull/642

**Comment by pbowen-oc** [comment]
Looks good in testing
