### ISSUE TITLE
Include item name of checked signature item in call for signature confirmation

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#618]
Related to issue #581 
We would like the call sent by enketo to study runner application when the signature item from #581 is checked to include an additional piece of information, the item name of the box that was checked.

We need to store this on the OC side of things, and this will allow us to do so.

**Comment by pbowen-oc** [comment]
@MartijnR - We'll hold off on this for now. No changes needed at this time.

**Comment by pbowen-oc** [comment]
Closing since this is not currently needed.
