### ISSUE TITLE
Upon Editing completed form and closing it, confirm completion popup is appearing

### ISSUE THREAD

**Issue by dduval11** [OpenClinica/enketo-express-oc#624]
Steps:
1. Open already completed form
2. Change a data value and entered RFC as requested
3. Click Close button

Expected:
The form is closed without further prompting.

Actual:
The form prompts to confirm marking the form as complete. It is already complete in this view, so it should to have a prompt for this.

**Comment by pbowen-oc** [comment]
Closing as duplicate of #626.
