### ISSUE TITLE
Completion confirmation dialog appears when closing an already completed form

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#626]
**Describe the bug**
When opening a completed form and then closing it, a confirmation dialog is displayed as if the form is being completed for the first time.

**To Reproduce**
Complete the attached form. Reopen it in edit mode, edit date, then close the form again, providing any required reasons for change. The confirmation dialog for initial completion of the form appears.

**Expected behavior**
The form closes.

Attach xform for affected form

Steps:
1. Open already completed form
2. Change a data value and entered RFC as requested
3. Click Close button

Expected:
The form is closed without further prompting.

Actual:
The form prompts to confirm marking the form as complete. It is already complete in this view, so it should to have a prompt for this.

**Comment by dduval11** [comment]
please see xform attached 
[medical_history.xls](https://github.com/OpenClinica/enketo-express-oc/files/10689273/medical_history.xls)

**Comment by dduval11** [comment]
[pop_up_xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/10689915/pop_up_xform.txt)
xform for this . thanks

**Comment by malcjackson** [comment]
https://user-images.githubusercontent.com/59966090/220698963-8724f0e4-b573-4a15-b5e8-888bfbf672ad.mp4

With the fix in place we are seeing the dialog appear very briefly and then go away as the form closes. In the above video you can see this starting about ~25 seconds in.

**Comment by pbowen-oc** [comment]
@malcjackson - This is expected. This is a different popup that is just there briefly while the form is closing and submitting any remaining values from the queue.

**Comment by pbowen-oc** [comment]
Looks good in testing
