### ISSUE TITLE
Tags didn't not come through from enketo/enketo-validate

### ISSUE THREAD

**Issue by kkrumlian** [OpenClinica/enketo-express-oc#628]
Hey @MartijnR the tags didn't come through from https://github.com/enketo/enketo-validate/tags -> https://github.com/OpenClinica/enketo-validate/tags. 

Can you push those through please. 
Thank you
Krikor

**Comment by MartijnR** [comment]
Ah, it seems those are not included when merging via GitHub. I'll try the other way by creating a branch first and using SourceTree, and will create another PR.
