### ISSUE TITLE
Enketo returning form in the wrong language in /survey/view/pdf

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#630]
**Describe the bug**
When I call a form via API with a language attribute embedded in the call, I'm getting the form in the wrong language. I have 2 xforms that are identical except for the version name. Version 2 always returns French, regardless of what language I am passing. Version "no select" always returns English, regardless of language what I am passing. I tried reducing the size of the xform to see what might be causing the issue, but I was unable to shorten it further. 

API Endpoint: [api/v1/survey/view/pdf?lang=de](https://formprint.openclinica-dev.io/oc/api/v1/survey/view/pdf?lang=de)
Works for Instance API Endoint: [api/v1/instance/view/pdf?lang=de](https://formprint.openclinica-dev.io/oc/api/v1/instance/view/pdf?lang=de)

**To Reproduce**
[Xform_version_no_select.txt](https://github.com/OpenClinica/enketo-express-oc/files/10708847/Xform_version_no_select.txt)
[Xform_Version2.txt](https://github.com/OpenClinica/enketo-express-oc/files/10708848/Xform_Version2.txt)

**Comment by pbowen-oc** [comment]
@MartijnR - It looks like this was missed in #606.

**Comment by pbowen-oc** [comment]
After further investigation, this looks like an issue on our end. Closing.
