### ISSUE TITLE
Close button for complete form views has extra checkmark

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#633]
Steps:
1. Open a complete form in edit mode (such as /edit/fs/rfc/c/i/)

Expected:
Only one button will be present and it will be labeled "Close".

Actual:
The button has a checkmark before the "Close" label.
![Screenshot 2023-02-13 234932](https://user-images.githubusercontent.com/25179620/218642445-20d08911-f7d4-4b44-b122-8a16a11e36af.png)

**Comment by pbowen-oc** [comment]
Note: Our Complete buttons have the checkmark, but our Close buttons do not.

**Comment by MartijnR** [comment]
* [ ] remove icon on fake Close buttons (that are actually cComplete buttons)

**Comment by pbowen-oc** [comment]
Looks good in testing
