### ISSUE TITLE
Repeating groups after the first have error messages in English regardless of form language

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#636]
**Describe the bug**
When a form with repeating groups is used in a non-english locale, the first repeating group's errors are in the form's language, and subsequent groups have english error messages.

**To Reproduce**
Xform where this was reproducible:
[repeaterrors.txt](https://github.com/OpenClinica/enketo-express-oc/files/10737994/repeaterrors.txt)

Open in german, add multiple repeating groups, enter numbers below 100 to trigger constraint errors.

**Expected behavior**
All messages should be in german

**Screenshots**
<img width="1553" alt="form-lang-err-repeats-3 (1)" src="https://user-images.githubusercontent.com/59966090/218894387-c843f293-657a-49a1-ace5-f743c899d24c.png">

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/cpEbFWCm?ecid=a&lang=de

**Comment by MartijnR** [comment]
* [ ] post issue - https://github.com/enketo/enketo-express/issues/526
* [ ] create PR
* [ ] merge

**Comment by pbowen-oc** [comment]
Looks good in testing
