### ISSUE TITLE
Enketo express still showing version as 5.0.2 after upgrade to 6.0

### ISSUE THREAD

**Issue by kkrumlian** [OpenClinica/enketo-express-oc#645]
OpenClinica is running! Please access OpenClinica forms from your OpenClinica installation.

version: 5.0.2-1154-g43def9c

**Comment by MartijnR** [comment]
Thanks. I'm seeing the same. I don't quite know what caused this. Possibly the tag was added in enketo-express after I created the PR. Will create another PR to hopefully fix it.
