### ISSUE TITLE
Form preview not processing constraints, relevant on groups, and strict required correctly

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#647]
Form previews (/preview/i/) have several issues with logic not processing or be reflected as expected:
1. No constraint error messages are appearing for any items
2. Relevant error messages for relevant expressions on groups are not displaying error messages. Note that relevant errors on items with relevant logic appears to be firing as expected.
3. Strict required items are allowing their value to be cleared. This should be prevented with a popup message. Note that these items are showing a required error message on the form after the value is cleared.
![Screenshot 2023-02-16 234312](https://user-images.githubusercontent.com/25179620/219553171-9fa712e5-23d6-44b8-bc24-9ab48eb1e60d.png)

**Comment by pbowen-oc** [comment]
@MartijnR - Let me know if an XForm is needed for this.

**Comment by MartijnR** [comment]
preview: http://localhost:8005/preview/i/ed22e40ed7c5916d64e799be4d36335d
regular: http://localhost:8005/single/fs/i/YYp2?ecid=1

**Comment by pbowen-oc** [comment]
@MartijnR - It looks like the constraints are working in Preview mode now, but we are seeing unexpected behavior that entering data for an item (or a value being calculated) is actually attempting a data submission.
![Screenshot 2023-02-24 154029](https://user-images.githubusercontent.com/25179620/221287808-f050ff1c-f2be-46ca-a31b-7a60fc651a53.png)

**Comment by MartijnR** [comment]
That's not good. Sorry about that.

**Comment by MartijnR** [comment]
I don't immediately see a use case for the 'Saving is disabled' message (readonly views have a different message). @pbowen-oc, do you perhaps know of a use case where that message should be shown?

**Comment by pbowen-oc** [comment]
@MartijnR - I think the use case for that was when the form failed to load properly and we prevented submissions and hid the Close button (and Complete button?) to ensure that data wasn't sent back and that the user was more likely to understand why. In the past, users had seen an initial loading error, closed that popup window, and still expected the form to work fully.
