### ISSUE TITLE
Completing a form offers autoqueries for relevant errors

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#658]
Steps:
1. Open a non-complete form
2. Add item data
3. Make some of the item data be non-relevant (so a relevant error occurs)
4. Click the Complete button on the form

Expected:
Since adding a query cannot resolve a relevant error, the user will not be permitted to complete the form until they manually address the issue. The user should not be offered the choice to add autoqueries.

Actual:
The user is being prompted to add autoqueries. If the user Proceeds, autoqueries are added, but the form correctly does not close.

This is what the user sees upon clicking Complete where there is a relevant error:
![Screenshot 2023-03-01 132539](https://user-images.githubusercontent.com/25179620/222233483-7e403d4f-4c4e-4818-84d5-a877dd5b3a45.png)

Clicking Proceed then shows this:
![Screenshot 2023-03-01 132608](https://user-images.githubusercontent.com/25179620/222233534-fa2f7808-f24e-4203-975a-d1198cccff40.png)

The user should be seeing a message like for strict required/constraint when they click Complete:
![Screenshot 2023-03-01 132723](https://user-images.githubusercontent.com/25179620/222233645-7c2ae543-a98f-4519-bdca-98cf6e25a973.png)

Note that when the user is editing a form that is already complete, then clicking the Close button (i.e., the modified Complete button), then the user should be prompted to add autoqueries if the items with relevant errors do not already have open queries.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/pMWLRJo1?ecid=a

**Comment by MartijnR** [comment]
This is caused by the earlier fix for #649 (where we changed things to show those relevantErrors only for Participate)

* [ ] fix
* [ ] check for regressions of original issue #649

**Comment by kkrumlian** [comment]
So this issue is still open ?

**Comment by pbowen-oc** [comment]
Looks good in testing
