### ISSUE TITLE
Signature error message is triggered in preview mode

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#667]
When a form including the signature item added in #581 and viewing it in Preview mode, clicking the signature item and waiting, or Validating the form is triggering the "Signature service...etc." error dialog.

We'd like Preview mode to accommodate this item type and not generate any error based on the call not being sent or a response received by enketo. An otherwise valid form should not expect a response and produce this error when in Preview mode, and when clicking Validate should not produce an error because of the signature item.

The video below shows this behavior. The full video is long but the relevant section starts at about ~50 seconds.

https://user-images.githubusercontent.com/59966090/225420216-e70c075c-3d90-4a0b-b098-bd3a74ca158b.mp4

**Comment by MartijnR** [comment]
* [ ] disable external signature behavior in previews
