### ISSUE TITLE
OC only: load errors

### ISSUE THREAD

**Issue by enketo-issue-mover** [OpenClinica/enketo-express-oc#68]
_From @MartijnR on October 11, 2017 19:25_

Scenario 1:
Form cannot be loaded
"Survey with this ID not found" error. Exit button will redirect back to OC. No other close button (no x button).

Scenario 2:
Form is loaded, but there are loadErrors (such as XPath formula or not being able to download data).
Turn off fieldsubmissions (e.g. for calculated items). Tbc because we need to classify errors as serious or not serious (goto errors, or user list downoading e.g.)

_Copied from original issue: kobotoolbox/enketo-express#837_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on October 11, 2017 19:33_

Might be more robust to use the better-safe-than-sorry approach and disable all functionality, including fieldsubmissions and buttons, if there is a load error, with the only exception being a hidden goto field.

**Comment by pbowen-oc** [comment]
This functionality has already been implemented (disable submissions if there is a load error).
