### ISSUE TITLE
Issues with 6.2.0 changes - Form opens up with errors

### ISSUE THREAD

**Issue by kkrumlian** [OpenClinica/enketo-express-oc#695]
After merging 6.2.0 we are seeing a few issues when opening forms. Screenshots below reflect what we are seeing.

**Comment by kkrumlian** [comment]
![OpenClinica Participate 2023-09-28 11 AM-31-28](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/96ba49a6-00b7-4fe9-bb88-5d6612f53948)
![OpenClinica 2023-09-28 11 AM-33-38](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/aca96909-fbd1-40a1-9fc2-c8f82c6222d1)

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=cascading&ecid=1&instance=\
<cascading xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"false\">\
<page1><cascade1>1</cascade1><cascade2>1</cascade2><cascade3>1</cascade3></page1>\
<meta><instanceID>uuid:1234</instanceID></meta></cascading>\
&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit/incomplete/rfc
```

**Comment by MartijnR** [comment]
first merge https://github.com/OpenClinica/enketo-express-oc/pull/697

then https://github.com/OpenClinica/enketo-express-oc/pull/696
