### ISSUE TITLE
Switch to monorepo - first phase

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#717]
Potentially a significant amount of work

* [x] create fork : https://github.com/OpenClinica/enketo-oc
* [x] copy customized files, see current diff here: https://github.com/kobotoolbox/enketo-express/compare/master...OpenClinica:enketo-express-oc:master and create combined customizations commit
* [x] fix paths in OC theme and other theme files
* [x] check js build for enketo-webform-oc
* [x] check package.json alias solution (e.g. for xpath extensions)
* [x] fix any other build errors
* [x] get `yarn workspace enketo-express test` working including the specs that OC added
* [x] check CI
* [x] change info in package.json

**Comment by kkrumlian** [comment]
What are the components that would be included in this?

**Comment by kkrumlian** [comment]
> I think all OC customizations so far will be combined in one big commit.
Is there a way to preserve the history ... Not sure how git those that ?

**Comment by kkrumlian** [comment]
When making changes for our repo ... How often would we have to make breaking changes in upstream aka enketo/enketo repo.

**Comment by kkrumlian** [comment]
How active do you think the contributions from other members will be to the upstream repo.

**Comment by MartijnR** [comment]
> Is there a way to preserve the history ... Not sure how git those that ?

I think I would have to remove the enketo-express package and re-add the enketo-express-oc package. That would then no longer allow us to update it from enketo/enketo.

> How often would we have to make breaking changes in upstream aka enketo/enketo repo.

I don't understand. 

> How active do you think the contributions from other members will be to the upstream repo.

I may not understand the question. The enketo/* repositories are just reorganized differently. That doesn't have an impact on contributions. It/they will remain under active development by ODK & co.

**Comment by MartijnR** [comment]
**DRAFT** Highlights for OC devops:
- using yarn instead of npm
- consider using volta for node version management (not sure if meant just for development)
- modern node and npm versions! 
-
